/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { GasFeeController } from './GasFeeController';

/**
 * Resets the polling interval by stopping and restarting polling
 * with the existing poll tokens.
 */
export type GasFeeControllerResetPollingAction = {
  type: `GasFeeController:resetPolling`;
  handler: GasFeeController['resetPolling'];
};

/**
 * Fetches gas fee estimates.
 *
 * @param options - The gas fee estimate options.
 * @returns The gas fee estimates.
 */
export type GasFeeControllerFetchGasFeeEstimatesAction = {
  type: `GasFeeController:fetchGasFeeEstimates`;
  handler: GasFeeController['fetchGasFeeEstimates'];
};

/**
 * Gets gas fee estimates and starts polling for updates.
 *
 * @param pollToken - An existing poll token to reuse, or undefined to
 * generate a new one.
 * @returns The poll token that can be used to stop polling.
 */
export type GasFeeControllerGetGasFeeEstimatesAndStartPollingAction = {
  type: `GasFeeController:getGasFeeEstimatesAndStartPolling`;
  handler: GasFeeController['getGasFeeEstimatesAndStartPolling'];
};

/**
 * Remove the poll token, and stop polling if the set of poll tokens is empty.
 *
 * @param pollToken - The poll token to disconnect.
 */
export type GasFeeControllerDisconnectPollerAction = {
  type: `GasFeeController:disconnectPoller`;
  handler: GasFeeController['disconnectPoller'];
};

/**
 * Stops polling for gas fee estimates and clears all poll tokens.
 */
export type GasFeeControllerStopPollingAction = {
  type: `GasFeeController:stopPolling`;
  handler: GasFeeController['stopPolling'];
};

/**
 * Gets the estimated time for a transaction based on the given gas parameters.
 *
 * @param maxPriorityFeePerGas - The maximum priority fee per gas in GWEI.
 * @param maxFeePerGas - The maximum fee per gas in GWEI.
 * @returns The estimated time bounds, or an empty object if fee market
 * estimates are not available.
 */
export type GasFeeControllerGetTimeEstimateAction = {
  type: `GasFeeController:getTimeEstimate`;
  handler: GasFeeController['getTimeEstimate'];
};

/**
 * Union of all GasFeeController action types.
 */
export type GasFeeControllerMethodActions =
  | GasFeeControllerResetPollingAction
  | GasFeeControllerFetchGasFeeEstimatesAction
  | GasFeeControllerGetGasFeeEstimatesAndStartPollingAction
  | GasFeeControllerDisconnectPollerAction
  | GasFeeControllerStopPollingAction
  | GasFeeControllerGetTimeEstimateAction;
