/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { AnalyticsDataRegulationService } from './AnalyticsDataRegulationService';

/**
 * Creates a DELETE_ONLY regulation for the given analyticsId.
 *
 * @param analyticsId - The analytics ID of the user for whom to create the deletion task.
 * @returns Promise resolving to a successful deletion regulation response.
 * @throws Error if the request fails or the response is invalid.
 */
export type AnalyticsDataRegulationServiceCreateDataDeletionTaskAction = {
  type: `AnalyticsDataRegulationService:createDataDeletionTask`;
  handler: AnalyticsDataRegulationService['createDataDeletionTask'];
};

/**
 * Checks the status of a regulation by ID.
 *
 * @param regulationId - The regulation ID to check.
 * @returns Promise resolving to a successful regulation status response.
 * @throws Error if the request fails or the response is invalid.
 */
export type AnalyticsDataRegulationServiceCheckDataDeleteStatusAction = {
  type: `AnalyticsDataRegulationService:checkDataDeleteStatus`;
  handler: AnalyticsDataRegulationService['checkDataDeleteStatus'];
};

/**
 * Union of all AnalyticsDataRegulationService action types.
 */
export type AnalyticsDataRegulationServiceMethodActions =
  | AnalyticsDataRegulationServiceCreateDataDeletionTaskAction
  | AnalyticsDataRegulationServiceCheckDataDeleteStatusAction;
