/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { AnalyticsDataRegulationController } from './AnalyticsDataRegulationController';

/**
 * Creates a new delete regulation for the user.
 * This is necessary to respect the GDPR and CCPA regulations.
 *
 * @returns Promise containing the status of the request with regulateId
 * @throws Error if analytics ID is missing or if the service call fails
 */
export type AnalyticsDataRegulationControllerCreateDataDeletionTaskAction = {
  type: `AnalyticsDataRegulationController:createDataDeletionTask`;
  handler: AnalyticsDataRegulationController['createDataDeletionTask'];
};

/**
 * Check the latest delete regulation status.
 *
 * @returns Promise containing the timestamp, delete status and collected data flag
 */
export type AnalyticsDataRegulationControllerCheckDataDeleteStatusAction = {
  type: `AnalyticsDataRegulationController:checkDataDeleteStatus`;
  handler: AnalyticsDataRegulationController['checkDataDeleteStatus'];
};

/**
 * Update the data recording flag if needed.
 * This method should be called after tracking events to ensure
 * the data recording flag is properly updated for data deletion workflows.
 *
 * The flag can only be set to `true` (indicating data has been collected).
 * It cannot be explicitly set to `false` - it is only reset to `false` when
 * a new deletion task is created via `createDataDeletionTask`.
 *
 */
export type AnalyticsDataRegulationControllerUpdateDataRecordingFlagAction = {
  type: `AnalyticsDataRegulationController:updateDataRecordingFlag`;
  handler: AnalyticsDataRegulationController['updateDataRecordingFlag'];
};

/**
 * Union of all AnalyticsDataRegulationController action types.
 */
export type AnalyticsDataRegulationControllerMethodActions =
  | AnalyticsDataRegulationControllerCreateDataDeletionTaskAction
  | AnalyticsDataRegulationControllerCheckDataDeleteStatusAction
  | AnalyticsDataRegulationControllerUpdateDataRecordingFlagAction;
