import { generateCodeownersFileContent } from './generate.js';
import type { CodeownersConfig } from './types.js';

describe('generateCodeownersFileContent', () => {
  it('renders the preamble, Packages section, and Overrides section', () => {
    const config: CodeownersConfig = {
      packages: {
        'b-controller': { teams: ['@MetaMask/b-team'] },
        'a-controller': {
          teams: ['@MetaMask/b-team', '@MetaMask/a-team'],
          initializationPath: 'a-controller',
        },
        wallet: { teams: ['@MetaMask/core-platform'] },
      },
      overrides: [
        { pattern: '/.github/', owners: ['@MetaMask/core-platform'] },
        {
          pattern: '/packages/b-controller/src/special',
          owners: ['@MetaMask/a-team', '@MetaMask/core-platform'],
        },
      ],
    };

    const content = generateCodeownersFileContent(config);

    expect(content).toBe(
      `# NOTE: This file is autogenerated.
# Don't modify this file directly; instead, modify \`codeowners.ts\` and re-run \`yarn codeowners:generate\`.

# Packages
# --------

### a-controller
/packages/a-controller                 @MetaMask/a-team @MetaMask/b-team
/packages/a-controller/CHANGELOG.md    @MetaMask/a-team @MetaMask/b-team @MetaMask/core-platform
/packages/a-controller/package.json    @MetaMask/a-team @MetaMask/b-team @MetaMask/core-platform
/packages/a-controller/tsconfig.*      @MetaMask/a-team @MetaMask/b-team @MetaMask/core-platform
/packages/a-controller/typedoc.json    @MetaMask/a-team @MetaMask/b-team @MetaMask/core-platform

### b-controller
/packages/b-controller                 @MetaMask/b-team
/packages/b-controller/CHANGELOG.md    @MetaMask/b-team @MetaMask/core-platform
/packages/b-controller/package.json    @MetaMask/b-team @MetaMask/core-platform
/packages/b-controller/tsconfig.*      @MetaMask/b-team @MetaMask/core-platform
/packages/b-controller/typedoc.json    @MetaMask/b-team @MetaMask/core-platform

### wallet
/packages/wallet                                               @MetaMask/core-platform
/packages/wallet/src/initialization/instances/a-controller/    @MetaMask/a-team @MetaMask/b-team
/packages/wallet/CHANGELOG.md                                  @MetaMask/core-platform
/packages/wallet/package.json                                  @MetaMask/core-platform
/packages/wallet/tsconfig.*                                    @MetaMask/core-platform
/packages/wallet/typedoc.json                                  @MetaMask/core-platform

# Overrides
# ---------

/.github/                             @MetaMask/core-platform
/packages/b-controller/src/special    @MetaMask/a-team @MetaMask/core-platform`,
    );
  });
});
