import { assembleCodeownersSections } from './assemble.js';
import { renderCodeownersSection } from './render.js';
import type { CodeownersConfig } from './types.js';

/**
 * The lines that appear before the CODEOWNERS rules.
 */
const CODEOWNERS_PRELUDE = `
# NOTE: This file is autogenerated.
# Don't modify this file directly; instead, modify \`codeowners.ts\` and re-run \`yarn codeowners:generate\`.
`.trim();

/**
 * Generates the content of the CODEOWNERS file from configuration.
 *
 * @param config - The CODEOWNERS configuration.
 * @returns The full CODEOWNERS file contents.
 */
export function generateCodeownersFileContent(
  config: CodeownersConfig,
): string {
  const sectionLines = assembleCodeownersSections(config).map((section) =>
    renderCodeownersSection(section),
  );

  return [CODEOWNERS_PRELUDE, ...sectionLines].join('\n\n');
}
