/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { StorageService } from './StorageService';

/**
 * Store large JSON data in storage.
 *
 * ⚠️ **Designed for large values (100KB+), not many small ones.**
 * Each storage operation has I/O overhead. For best performance,
 * store one large object rather than many small key-value pairs.
 *
 * @example Good: Store entire cache as one value
 * ```typescript
 * await service.setItem('TokenList', 'cache', { '0x1': [...], '0x38': [...] });
 * ```
 *
 * @example Avoid: Many small values
 * ```typescript
 * // ❌ Don't do this - too many small writes
 * await service.setItem('TokenList', 'cache:0x1', [...]);
 * await service.setItem('TokenList', 'cache:0x38', [...]);
 * ```
 *
 * @param namespace - Controller namespace (e.g., 'SnapController').
 * @param key - Storage key (e.g., 'npm:@metamask/example-snap:sourceCode').
 * @param value - JSON data to store (should be 100KB+ for optimal use).
 */
export type StorageServiceSetItemAction = {
  type: `StorageService:setItem`;
  handler: StorageService['setItem'];
};

/**
 * Retrieve JSON data from storage.
 *
 * @param namespace - Controller namespace (e.g., 'SnapController').
 * @param key - Storage key (e.g., 'npm:@metamask/example-snap:sourceCode').
 * @returns StorageGetResult: { result } if found, {} if not found, { error } on failure.
 */
export type StorageServiceGetItemAction = {
  type: `StorageService:getItem`;
  handler: StorageService['getItem'];
};

/**
 * Remove data from storage.
 *
 * @param namespace - Controller namespace (e.g., 'SnapController').
 * @param key - Storage key (e.g., 'npm:@metamask/example-snap:sourceCode').
 */
export type StorageServiceRemoveItemAction = {
  type: `StorageService:removeItem`;
  handler: StorageService['removeItem'];
};

/**
 * Get all keys for a namespace.
 * Delegates to storage adapter which handles filtering.
 *
 * @param namespace - Controller namespace (e.g., 'SnapController').
 * @returns Array of keys (without prefix) for this namespace.
 */
export type StorageServiceGetAllKeysAction = {
  type: `StorageService:getAllKeys`;
  handler: StorageService['getAllKeys'];
};

/**
 * Clear all data for a namespace.
 *
 * @param namespace - Controller namespace (e.g., 'SnapController').
 */
export type StorageServiceClearAction = {
  type: `StorageService:clear`;
  handler: StorageService['clear'];
};

/**
 * Union of all StorageService action types.
 */
export type StorageServiceMethodActions =
  | StorageServiceSetItemAction
  | StorageServiceGetItemAction
  | StorageServiceRemoveItemAction
  | StorageServiceGetAllKeysAction
  | StorageServiceClearAction;
