export const MOCK_ETHEREUM_TOKENS_METADATA = {
  data: [
    {
      address: '0xbbbbca6a901c926f240b89eacb641d8aec7aeafd',
      symbol: 'LRC',
      decimals: 18,
      occurrences: 11,
      aggregators: [
        'paraswap',
        'pmm',
        'airswapLight',
        'zeroEx',
        'bancor',
        'coinGecko',
        'zapper',
        'kleros',
        'zerion',
        'cmc',
        'oneInch',
      ],
    },
    {
      address: '0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f',
      symbol: 'SNX',
      decimals: 18,
      occurrences: 11,
      aggregators: [
        'paraswap',
        'pmm',
        'airswapLight',
        'zeroEx',
        'bancor',
        'coinGecko',
        'zapper',
        'kleros',
        'zerion',
        'cmc',
        'oneInch',
      ],
      name: 'Synthetix',
    },
    {
      address: '0x408e41876cccdc0f92210600ef50372656052a38',
      symbol: 'REN',
      decimals: 18,
      occurrences: 11,
      aggregators: [
        'paraswap',
        'pmm',
        'airswapLight',
        'zeroEx',
        'bancor',
        'coinGecko',
        'zapper',
        'kleros',
        'zerion',
        'cmc',
        'oneInch',
      ],
    },
    {
      address: '0x514910771af9ca656af840dff83e8264ecf986ca',
      symbol: 'LINK',
      decimals: 18,
      occurrences: 11,
      aggregators: [
        'paraswap',
        'pmm',
        'airswapLight',
        'zeroEx',
        'bancor',
        'coinGecko',
        'zapper',
        'kleros',
        'zerion',
        'cmc',
        'oneInch',
      ],
      name: 'Chainlink',
    },
    {
      address: '0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c',
      symbol: 'BNT',
      decimals: 18,
      occurrences: 11,
      aggregators: [
        'paraswap',
        'pmm',
        'airswapLight',
        'zeroEx',
        'bancor',
        'coinGecko',
        'zapper',
        'kleros',
        'zerion',
        'cmc',
        'oneInch',
      ],
      name: 'Bancor',
    },
  ],
  pageInfo: {
    hasNextPage: false,
    endCursor: '',
  },
};

export const MOCK_LINEA_TOKENS_METADATA = {
  data: [
    {
      address: '0xbbbbca6a901c926f240b89eacb641d8aec7aeafd',
      symbol: 'LRC',
      decimals: 18,
      occurrences: 11,
      aggregators: [
        'lineaTeam',
        'pmm',
        'airswapLight',
        'zeroEx',
        'bancor',
        'coinGecko',
        'zapper',
        'kleros',
        'zerion',
        'cmc',
        'oneInch',
      ],
    },
    {
      address: '0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f',
      symbol: 'SNX',
      decimals: 18,
      occurrences: 11,
      aggregators: [
        'lineaTeam',
        'pmm',
        'airswapLight',
        'zeroEx',
        'bancor',
        'coinGecko',
        'zapper',
        'kleros',
        'zerion',
        'cmc',
        'oneInch',
      ],
      name: 'Synthetix',
    },
    {
      address: '0x408e41876cccdc0f92210600ef50372656052a38',
      symbol: 'REN',
      decimals: 18,
      occurrences: 11,
      aggregators: [
        'lineaTeam',
        'pmm',
        'airswapLight',
        'zeroEx',
        'bancor',
        'coinGecko',
        'zapper',
        'kleros',
        'zerion',
        'cmc',
        'oneInch',
      ],
    },
    {
      address: '0x514910771af9ca656af840dff83e8264ecf986ca',
      symbol: 'LINK',
      decimals: 18,
      occurrences: 11,
      aggregators: [
        'lineaTeam',
        'pmm',
        'airswapLight',
        'zeroEx',
        'bancor',
        'coinGecko',
        'zapper',
        'kleros',
        'zerion',
        'cmc',
        'oneInch',
      ],
      name: 'Chainlink',
    },
    {
      address: '0x1f573d6fb3f13d689ff844b4ce37794d79a7ff1c',
      symbol: 'BNT',
      decimals: 18,
      occurrences: 11,
      aggregators: [
        'paraswap',
        'pmm',
        'airswapLight',
        'zeroEx',
        'bancor',
        'coinGecko',
        'zapper',
        'kleros',
        'zerion',
        'cmc',
        'oneInch',
      ],
      name: 'Bancor',
    },
  ],
  pageInfo: {
    hasNextPage: false,
    endCursor: '',
  },
};

export const MOCK_SINGLE_TOKEN_METADATA = [
  {
    aggregators: ['coinGecko', 'liFi', 'rango', 'ondo'],
    assetId: 'eip155:1/erc20:0xf6b1117ec07684d3958cad8beb1b302bfd21103f',
    decimals: 18,
    name: 'Tesla (Ondo Tokenized)',
    rwaData: {
      market: {
        nextOpen: '2026-01-07T14:31:00.000Z',
        nextClose: '2026-01-07T14:29:00.000Z',
      },
      nextPause: {
        start: '2026-01-28T21:00:00.000Z',
        end: '2026-01-29T00:30:00.000Z',
      },
      ticker: 'TSLA',
      instrumentType: 'stock',
    },
    symbol: 'TSLAON',
  },
];
