# Please see the documentation for all configuration options:
# https://docs.zizmor.sh/configuration/

rules:
  unpinned-uses:
    config:
      policies:
        # Allow `actions/*` and `MetaMask/*` to be pinned to a version instead
        # of only to a commit hash.
        actions/*: ref-pin
        MetaMask/*: ref-pin
