/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { ComplianceController } from './ComplianceController';

/**
 * Initializes the controller by fetching the blocked wallets list if it
 * is missing or stale. Call once after construction to ensure the blocklist
 * is ready for `selectIsWalletBlocked` lookups.
 */
export type ComplianceControllerInitAction = {
  type: `ComplianceController:init`;
  handler: ComplianceController['init'];
};

/**
 * Checks compliance status for a single wallet address via the API and
 * persists the result to state.
 *
 * @param address - The wallet address to check.
 * @returns The compliance status of the wallet.
 */
export type ComplianceControllerCheckWalletComplianceAction = {
  type: `ComplianceController:checkWalletCompliance`;
  handler: ComplianceController['checkWalletCompliance'];
};

/**
 * Checks compliance status for multiple wallet addresses via the API and
 * persists the results to state.
 *
 * @param addresses - The wallet addresses to check.
 * @returns The compliance statuses of the wallets.
 */
export type ComplianceControllerCheckWalletsComplianceAction = {
  type: `ComplianceController:checkWalletsCompliance`;
  handler: ComplianceController['checkWalletsCompliance'];
};

/**
 * Fetches the full list of blocked wallets from the API and persists the
 * data to state. This also updates the `blockedWalletsLastFetched` timestamp.
 *
 * @returns The blocked wallets information.
 */
export type ComplianceControllerUpdateBlockedWalletsAction = {
  type: `ComplianceController:updateBlockedWallets`;
  handler: ComplianceController['updateBlockedWallets'];
};

/**
 * Clears all compliance data from state.
 */
export type ComplianceControllerClearComplianceStateAction = {
  type: `ComplianceController:clearComplianceState`;
  handler: ComplianceController['clearComplianceState'];
};

/**
 * Union of all ComplianceController action types.
 */
export type ComplianceControllerMethodActions =
  | ComplianceControllerInitAction
  | ComplianceControllerCheckWalletComplianceAction
  | ComplianceControllerCheckWalletsComplianceAction
  | ComplianceControllerUpdateBlockedWalletsAction
  | ComplianceControllerClearComplianceStateAction;
