/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { ComplianceController } from './ComplianceController';

/**
 * Initializes the controller by fetching the blocked wallets list if it
 * is missing or stale. Call once after construction to ensure the blocklist
 * is ready for `isWalletBlocked` lookups.
 */
export type ComplianceControllerInitializeAction = {
  type: `ComplianceController:initialize`;
  handler: ComplianceController['initialize'];
};

/**
 * Checks compliance status for a single wallet address via the API and
 * persists the result to state.
 *
 * @param address - The wallet address to check.
 * @returns The compliance status of the wallet.
 */
export type ComplianceControllerCheckWalletComplianceAction = {
  type: `ComplianceController:checkWalletCompliance`;
  handler: ComplianceController['checkWalletCompliance'];
};

/**
 * Checks compliance status for multiple wallet addresses via the API and
 * persists the results to state.
 *
 * @param addresses - The wallet addresses to check.
 * @returns The compliance statuses of the wallets.
 */
export type ComplianceControllerCheckWalletsComplianceAction = {
  type: `ComplianceController:checkWalletsCompliance`;
  handler: ComplianceController['checkWalletsCompliance'];
};

/**
 * Fetches the full list of blocked wallets from the API and persists the
 * data to state. This also updates the `blockedWalletsLastFetched` timestamp.
 *
 * @returns The blocked wallets information.
 */
export type ComplianceControllerFetchBlockedWalletsAction = {
  type: `ComplianceController:fetchBlockedWallets`;
  handler: ComplianceController['fetchBlockedWallets'];
};

/**
 * Returns whether a wallet address is blocked, based on the cached
 * blocklist. This is a synchronous lookup that does not make any API calls.
 *
 * The lookup checks the proactively fetched blocklist first, then falls
 * back to the per-address compliance status map for addresses checked
 * via `checkWalletCompliance` or `checkWalletsCompliance`.
 *
 * @param address - The wallet address to check.
 * @returns `true` if the wallet is blocked according to cached data,
 * `false` otherwise.
 */
export type ComplianceControllerIsWalletBlockedAction = {
  type: `ComplianceController:isWalletBlocked`;
  handler: ComplianceController['isWalletBlocked'];
};

/**
 * Clears all compliance data from state.
 */
export type ComplianceControllerClearComplianceStateAction = {
  type: `ComplianceController:clearComplianceState`;
  handler: ComplianceController['clearComplianceState'];
};

/**
 * Union of all ComplianceController action types.
 */
export type ComplianceControllerMethodActions =
  | ComplianceControllerInitializeAction
  | ComplianceControllerCheckWalletComplianceAction
  | ComplianceControllerCheckWalletsComplianceAction
  | ComplianceControllerFetchBlockedWalletsAction
  | ComplianceControllerIsWalletBlockedAction
  | ComplianceControllerClearComplianceStateAction;
