compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

enableTelemetry: false

logFilters:
  - code: YN0004
    level: discard

nodeLinker: node-modules

plugins:
  - checksum: 88c75030dc6ecca58bc9b1674af1c59ade7ce44e567c1b2cc957f5e36ddd91f9b8719cfec072e4ba46c1c615e74181455bd516a7aafd0f7558e10f6a850944ff
    path: .yarn/plugins/@yarnpkg/plugin-allow-scripts.cjs
    spec: "https://raw.githubusercontent.com/LavaMoat/LavaMoat/f0ab3ffa3bc14cf0fcece79b41d37fb911f973a7/packages/yarn-plugin-allow-scripts/bundles/%40yarnpkg/plugin-allow-scripts.js"
