# Allowlist for Git repositories that can be used as dependencies. We set it to
# an empty array to disallow all Git dependencies, as we don't use any and they
# can be a security risk.
approvedGitRepositories: []

compressionLevel: mixed

enableGlobalCache: false

# Hardened mode to validate lockfile content against remote registries.
enableHardenedMode: true

# Disable Yarn's mirror feature to avoid writing to the global cache.
enableMirror: false

enableScripts: false

enableTelemetry: false

# Despite `enableGlobalCache` and `enableMirror` being `false`, Yarn is still
# writing to the global folder.
globalFolder: .yarn/global

logFilters:
  - code: YN0004
    level: discard

nodeLinker: node-modules

# Configure the NPM minimal age gate to 3 days, meaning packages must be at
# least 3 days old to be installed.
npmMinimalAgeGate: 4320 # 3 days (in minutes)

# Override the minimal age gate, allowing certain packages to be installed
# regardless of their publish age.
npmPreapprovedPackages:
  - "@metamask/*"
  - "@metamask-previews/*"
  - "@lavamoat/*"
  - "@ts-bridge/*"

# Protect the runtime of calls to "yarn run" scripts using a local plugin.
plugins:
  - path: ./lavamoat/plugin-allow-scripts.js
  - path: ./lavamoat/.runner-plugin.js
