# We use allow-scripts to manually enable scripts and then run them
enableScripts: false

# This is necessary right now for TypeScript to find @types/* packages
nodeLinker: node-modules

plugins:
  # Provides `yarn workspaces foreach`, etc.
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  # Provides `yarn constraints`
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

# The current version of Yarn we're using
yarnPath: .yarn/releases/yarn-3.2.1.cjs
