# We use allow-scripts to manually enable scripts and then run them
enableScripts: false

# This ensures Yarn still uses a `node_modules` directory, which is required
# right now for TypeScript to find @types/* packages
nodeLinker: node-modules

# The current version of Yarn we're using
yarnPath: .yarn/releases/yarn-3.2.1.cjs
