# We use allow-scripts to manually enable scripts and then run them
enableScripts: false

# This ignores the warnings caused by `enableScripts`
logFilters:
  - code: YN0004
    level: discard

# This ensures Yarn still uses a `node_modules` directory, which is required
# right now for TypeScript to find @types/* packages
nodeLinker: node-modules

plugins:
  # This plugin runs `allow-scripts` automatically after install
  # TODO: migrate to the "official" version of this plugin: https://github.com/LavaMoat/LavaMoat/pull/345
  - path: .yarn/plugins/plugin-allow-scripts.cjs
    spec: plugin-allow-scripts.js

yarnPath: .yarn/releases/yarn-3.2.1.cjs
