/**
 * This file is auto generated by `@metamask/messenger/generate-action-types`.
 * Do not edit manually.
 */

import type { ConfigRegistryApiService } from './config-registry-api-service';

export type ConfigRegistryApiServiceFetchConfigAction = {
  type: `ConfigRegistryApiService:fetchConfig`;
  handler: ConfigRegistryApiService['fetchConfig'];
};

/**
 * Union of all ConfigRegistryApiService action types.
 */
export type ConfigRegistryApiServiceMethodActions =
  ConfigRegistryApiServiceFetchConfigAction;
