/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { AccountsController } from './AccountsController';

/**
 * Returns the internal account object for the given account ID, if it exists.
 *
 * @deprecated This method is deprecated and will be removed in a future version.
 * Use `AccountTreeController`, `MultichainAccountService`, or the Keyring API v2 instead.
 * @param accountId - The ID of the account to retrieve.
 * @returns The internal account object, or undefined if the account does not exist.
 */
export type AccountsControllerGetAccountAction = {
  type: `AccountsController:getAccount`;
  handler: AccountsController['getAccount'];
};

/**
 * Returns the internal account objects for the given account IDs, if they exist.
 *
 * @deprecated This method is deprecated and will be removed in a future version.
 * Use `AccountTreeController`, `MultichainAccountService`, or the Keyring API v2 instead.
 * @param accountIds - The IDs of the accounts to retrieve.
 * @returns The internal account objects, or undefined if the account(s) do not exist.
 */
export type AccountsControllerGetAccountsAction = {
  type: `AccountsController:getAccounts`;
  handler: AccountsController['getAccounts'];
};

/**
 * Returns an array of all evm internal accounts.
 *
 * @deprecated This method is deprecated and will be removed in a future version.
 * Use `AccountTreeController`, `MultichainAccountService`, or the Keyring API v2 instead.
 * @returns An array of InternalAccount objects.
 */
export type AccountsControllerListAccountsAction = {
  type: `AccountsController:listAccounts`;
  handler: AccountsController['listAccounts'];
};

/**
 * Returns an array of all internal accounts.
 *
 * @deprecated This method is deprecated and will be removed in a future version.
 * Use `AccountTreeController`, `MultichainAccountService`, or the Keyring API v2 instead.
 * @param chainId - The chain ID.
 * @returns An array of InternalAccount objects.
 */
export type AccountsControllerListMultichainAccountsAction = {
  type: `AccountsController:listMultichainAccounts`;
  handler: AccountsController['listMultichainAccounts'];
};

/**
 * Returns the last selected EVM account.
 *
 * @deprecated This method is deprecated and will be removed in a future version.
 * Use `AccountTreeController`, `MultichainAccountService`, or the Keyring API v2 instead.
 * @returns The selected internal account.
 */
export type AccountsControllerGetSelectedAccountAction = {
  type: `AccountsController:getSelectedAccount`;
  handler: AccountsController['getSelectedAccount'];
};

/**
 * __WARNING The return value may be undefined if there isn't an account for that chain id.__
 *
 * Retrieves the last selected account by chain ID.
 *
 * @deprecated This method is deprecated and will be removed in a future version.
 * Use `AccountTreeController`, `MultichainAccountService`, or the Keyring API v2 instead.
 * @param chainId - The chain ID to filter the accounts.
 * @returns The last selected account compatible with the specified chain ID or undefined.
 */
export type AccountsControllerGetSelectedMultichainAccountAction = {
  type: `AccountsController:getSelectedMultichainAccount`;
  handler: AccountsController['getSelectedMultichainAccount'];
};

/**
 * Returns the account with the specified address.
 * ! This method will only return the first account that matches the address
 *
 * @deprecated This method is deprecated and will be removed in a future version.
 * Use `AccountTreeController`, `MultichainAccountService`, or the Keyring API v2 instead.
 * @param address - The address of the account to retrieve.
 * @returns The account with the specified address, or undefined if not found.
 */
export type AccountsControllerGetAccountByAddressAction = {
  type: `AccountsController:getAccountByAddress`;
  handler: AccountsController['getAccountByAddress'];
};

/**
 * Sets the selected account by its ID.
 *
 * @deprecated This method is deprecated and will be removed in a future version.
 * Use `AccountTreeController`, `MultichainAccountService`, or the Keyring API v2 instead.
 * @param accountId - The ID of the account to be selected.
 */
export type AccountsControllerSetSelectedAccountAction = {
  type: `AccountsController:setSelectedAccount`;
  handler: AccountsController['setSelectedAccount'];
};

/**
 * Sets the name of the account with the given ID.
 *
 * @deprecated This method is deprecated and will be removed in a future version.
 * Use `AccountTreeController`, `MultichainAccountService`, or the Keyring API v2 instead.
 * @param accountId - The ID of the account to set the name for.
 * @param accountName - The new name for the account.
 * @throws An error if an account with the same name already exists.
 */
export type AccountsControllerSetAccountNameAction = {
  type: `AccountsController:setAccountName`;
  handler: AccountsController['setAccountName'];
};

/**
 * Sets the name of the account with the given ID and select it.
 *
 * @deprecated This method is deprecated and will be removed in a future version.
 * Use `AccountTreeController`, `MultichainAccountService`, or the Keyring API v2 instead.
 * @param accountId - The ID of the account to set the name for and select.
 * @param accountName - The new name for the account.
 * @throws An error if an account with the same name already exists.
 */
export type AccountsControllerSetAccountNameAndSelectAccountAction = {
  type: `AccountsController:setAccountNameAndSelectAccount`;
  handler: AccountsController['setAccountNameAndSelectAccount'];
};

/**
 * Updates the metadata of the account with the given ID.
 *
 * @deprecated This method is deprecated and will be removed in a future version.
 * Use `AccountTreeController`, `MultichainAccountService`, or the Keyring API v2 instead.
 * @param accountId - The ID of the account for which the metadata will be updated.
 * @param metadata - The new metadata for the account.
 */
export type AccountsControllerUpdateAccountMetadataAction = {
  type: `AccountsController:updateAccountMetadata`;
  handler: AccountsController['updateAccountMetadata'];
};

/**
 * Updates the internal accounts list by retrieving normal and snap accounts,
 * removing duplicates, and updating the metadata of each account.
 *
 * @deprecated This method is deprecated and will be removed in a future version.
 * Use `AccountTreeController`, `MultichainAccountService`, or the Keyring API v2 instead.
 * @returns A Promise that resolves when the accounts have been updated.
 */
export type AccountsControllerUpdateAccountsAction = {
  type: `AccountsController:updateAccounts`;
  handler: AccountsController['updateAccounts'];
};

/**
 * Loads the backup state of the accounts controller.
 *
 * @deprecated This method is deprecated and will be removed in a future version.
 * Use `AccountTreeController`, `MultichainAccountService`, or the Keyring API v2 instead.
 * @param backup - The backup state to load.
 */
export type AccountsControllerLoadBackupAction = {
  type: `AccountsController:loadBackup`;
  handler: AccountsController['loadBackup'];
};

/**
 * Union of all AccountsController action types.
 */
export type AccountsControllerMethodActions =
  | AccountsControllerGetAccountAction
  | AccountsControllerGetAccountsAction
  | AccountsControllerListAccountsAction
  | AccountsControllerListMultichainAccountsAction
  | AccountsControllerGetSelectedAccountAction
  | AccountsControllerGetSelectedMultichainAccountAction
  | AccountsControllerGetAccountByAddressAction
  | AccountsControllerSetSelectedAccountAction
  | AccountsControllerSetAccountNameAction
  | AccountsControllerSetAccountNameAndSelectAccountAction
  | AccountsControllerUpdateAccountMetadataAction
  | AccountsControllerUpdateAccountsAction
  | AccountsControllerLoadBackupAction;
