/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { UiStateController } from './UiStateController';

/**
 * Updates state with whether the MetaMask UI is open.
 *
 * This method should be called when the user has opened the first window or
 * screen containing the MetaMask UI, or closed the last window or screen
 * containing the MetaMask UI.
 *
 * @param open - Whether the MetaMask UI is open.
 */
export type UiStateControllerSetUiOpenAction = {
  type: `UiStateController:setUiOpen`;
  handler: UiStateController['setUiOpen'];
};

/**
 * Union of all UiStateController action types.
 */
export type UiStateControllerMethodActions = UiStateControllerSetUiOpenAction;
