/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "MetaMask Core — Developer Documentation",
  "tagline": "Developer documentation for the MetaMask core monorepo",
  "url": "https://metamask.github.io",
  "baseUrl": "/core/",
  "onBrokenLinks": "throw",
  "onBrokenAnchors": "throw",
  "markdown": {
    "hooks": {
      "onBrokenMarkdownLinks": "throw",
      "onBrokenMarkdownImages": "throw"
    },
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "organizationName": "MetaMask",
  "projectName": "core",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "trailingSlash": true,
  "stylesheets": [
    "/core/css/fonts.css"
  ],
  "presets": [
    [
      "classic",
      {
        "docs": false,
        "blog": false,
        "theme": {
          "customCss": "/Users/elliot/code/metamask/core/website/src/scss/custom.scss"
        }
      }
    ]
  ],
  "plugins": [
    "docusaurus-plugin-sass",
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "developers",
        "path": "../docs/developers",
        "routeBasePath": "/",
        "sidebarPath": "/Users/elliot/code/metamask/core/website/sidebars.js",
        "editUrl": "https://github.com/MetaMask/core/edit/main/",
        "breadcrumbs": true,
        "showLastUpdateTime": false
      }
    ]
  ],
  "themeConfig": {
    "colorMode": {
      "defaultMode": "light",
      "respectPrefersColorScheme": true,
      "disableSwitch": false
    },
    "navbar": {
      "title": "Core Developer Docs",
      "logo": {
        "alt": "MetaMask logo",
        "src": "img/metamask-logo.svg",
        "srcDark": "img/metamask-logo-dark.svg",
        "width": 32,
        "height": 32
      },
      "hideOnScroll": false,
      "items": [
        {
          "href": "https://github.com/MetaMask/core",
          "label": "GitHub",
          "position": "right"
        }
      ]
    },
    "docs": {
      "sidebar": {
        "autoCollapseCategories": false,
        "hideable": true
      },
      "versionPersistence": "localStorage"
    },
    "footer": {
      "style": "dark",
      "logo": {
        "alt": "MetaMask logo",
        "src": "img/metamask-logo-dark.svg",
        "width": 32,
        "height": 32,
        "href": "https://metamask.io"
      },
      "links": [
        {
          "title": "Documentation",
          "items": [
            {
              "label": "Developer docs",
              "to": "/"
            }
          ]
        },
        {
          "title": "GitHub",
          "items": [
            {
              "label": "MetaMask/core",
              "href": "https://github.com/MetaMask/core"
            },
            {
              "label": "MetaMask/metamask-extension",
              "href": "https://github.com/MetaMask/metamask-extension"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "MetaMask developer docs",
              "href": "https://docs.metamask.io"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 MetaMask"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash",
        "json",
        "typescript"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "storage": {
    "type": "localStorage",
    "namespace": false
  },
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false,
      "siteStorageNamespacing": false,
      "fasterByDefault": false,
      "mdx1CompatDisabledByDefault": false
    },
    "faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false,
      "gitEagerVcs": false
    },
    "experimental_vcs": {},
    "experimental_router": "browser"
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
