name: Build, Lint, and Test

on:
  workflow_call:

jobs:
  build-lint-test:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Install Corepack via Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install Yarn
        run: corepack enable
      - name: Install Node.js ${{ matrix.node-version }} and restore Yarn cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies via Yarn
        run: yarn --immutable
      - run: yarn build
      - run: yarn lint
      - run: yarn test
      - name: Validate RC changelog
        if: ${{ startsWith(github.head_ref, 'release/') }}
        run: yarn auto-changelog validate --rc --prettier
      - name: Validate changelog
        if: ${{ !startsWith(github.head_ref, 'release/') }}
        run: yarn auto-changelog validate --prettier
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty after building"
            exit 1
          fi
  all-jobs-pass:
    name: All jobs pass
    runs-on: ubuntu-latest
    needs:
      - build-lint-test
    steps:
      - run: echo "Great success!"
