// TODO: This file is supposed to be auto generated. Verify that this generates correctly. The first iteration (seen here) was generated by agent.
/**
 * This file is auto generated.
 * Do not edit manually.
 */

import type { MoneyAccountBalanceService } from './money-account-balance-service';

/**
 * Fetches the mUSD ERC-20 balance for the given account address via RPC.
 *
 * @param accountAddress - The Money account's address.
 * @returns The mUSD balance as a raw uint256 string.
 */
export type MoneyAccountBalanceServiceGetMusdBalanceAction = {
  type: `MoneyAccountBalanceService:getMusdBalance`;
  handler: MoneyAccountBalanceService['getMusdBalance'];
};

/**
 * Fetches the musdSHFvd (Veda vault share) ERC-20 balance for the given
 * account address via RPC.
 *
 * @param accountAddress - The Money account's address.
 * @returns The musdSHFvd balance as a raw uint256 string.
 */
export type MoneyAccountBalanceServiceGetMusdSHFvdBalanceAction = {
  type: `MoneyAccountBalanceService:getMusdSHFvdBalance`;
  handler: MoneyAccountBalanceService['getMusdSHFvdBalance'];
};

/**
 * Fetches the current exchange rate from the Veda Accountant contract via RPC.
 *
 * @returns The exchange rate as a raw uint256 string.
 */
export type MoneyAccountBalanceServiceGetExchangeRateAction = {
  type: `MoneyAccountBalanceService:getExchangeRate`;
  handler: MoneyAccountBalanceService['getExchangeRate'];
};

/**
 * Computes the mUSD-equivalent value of the account's musdSHFvd holdings.
 * Internally fetches the musdSHFvd balance and exchange rate (using cached
 * values when available), then multiplies them.
 *
 * @param accountAddress - The Money account's address.
 * @returns The musdSHFvd balance, exchange rate, and computed mUSD-equivalent value.
 */
export type MoneyAccountBalanceServiceGetMusdEquivalentValueAction = {
  type: `MoneyAccountBalanceService:getMusdEquivalentValue`;
  handler: MoneyAccountBalanceService['getMusdEquivalentValue'];
};

/**
 * Fetches the vault's APY and fee breakdown from the Veda performance REST API.
 *
 * @returns The 7-day trailing net APY, fees, and per-position breakdown.
 */
export type MoneyAccountBalanceServiceGetVaultApyAction = {
  type: `MoneyAccountBalanceService:getVaultApy`;
  handler: MoneyAccountBalanceService['getVaultApy'];
};

/**
 * Union of all MoneyAccountBalanceService action types.
 */
export type MoneyAccountBalanceServiceMethodActions =
  | MoneyAccountBalanceServiceGetMusdBalanceAction
  | MoneyAccountBalanceServiceGetMusdSHFvdBalanceAction
  | MoneyAccountBalanceServiceGetExchangeRateAction
  | MoneyAccountBalanceServiceGetMusdEquivalentValueAction
  | MoneyAccountBalanceServiceGetVaultApyAction;
