/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { ProfileMetricsController } from './ProfileMetricsController';

/**
 * Skip the initial delay period by setting the end timestamp to the current time.
 * Metrics will be sent on the next poll.
 */
export type ProfileMetricsControllerSkipInitialDelayAction = {
  type: `ProfileMetricsController:skipInitialDelay`;
  handler: ProfileMetricsController['skipInitialDelay'];
};

/**
 * Union of all ProfileMetricsController action types.
 */
export type ProfileMetricsControllerMethodActions =
  ProfileMetricsControllerSkipInitialDelayAction;
