/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { ProfileMetricsService } from './ProfileMetricsService';

/**
 * Submit metrics to the API.
 *
 * @param data - The data to send in the metrics update request.
 * @returns The response from the API.
 */
export type ProfileMetricsServiceSubmitMetricsAction = {
  type: `ProfileMetricsService:submitMetrics`;
  handler: ProfileMetricsService['submitMetrics'];
};

/**
 * Union of all ProfileMetricsService action types.
 */
export type ProfileMetricsServiceMethodActions =
  ProfileMetricsServiceSubmitMetricsAction;
