/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { AccountActivityService } from './AccountActivityService';

/**
 * Subscribe to account activity (transactions and balance updates)
 * Address should be in CAIP-10 format (e.g., "eip155:0:0x1234..." or "solana:0:ABC123...")
 *
 * @param subscription - Account subscription configuration with address
 */
export type AccountActivityServiceSubscribeAction = {
  type: `AccountActivityService:subscribe`;
  handler: AccountActivityService['subscribe'];
};

/**
 * Unsubscribe from account activity for specified address
 * Address should be in CAIP-10 format (e.g., "eip155:0:0x1234..." or "solana:0:ABC123...")
 *
 * @param subscription - Account subscription configuration with address to unsubscribe
 */
export type AccountActivityServiceUnsubscribeAction = {
  type: `AccountActivityService:unsubscribe`;
  handler: AccountActivityService['unsubscribe'];
};

/**
 * Union of all AccountActivityService action types.
 */
export type AccountActivityServiceMethodActions =
  | AccountActivityServiceSubscribeAction
  | AccountActivityServiceUnsubscribeAction;
