/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { ApiPlatformClientService } from './ApiPlatformClientService';

/**
 * Returns the shared ApiPlatformClient instance.
 *
 * Use this via the messenger: `messenger.call('ApiPlatformClientService:getApiPlatformClient')`.
 *
 * @returns The ApiPlatformClient instance (accounts, prices, token, tokens).
 */
export type ApiPlatformClientServiceGetApiPlatformClientAction = {
  type: `ApiPlatformClientService:getApiPlatformClient`;
  handler: ApiPlatformClientService['getApiPlatformClient'];
};

/**
 * Union of all ApiPlatformClientService action types.
 */
export type ApiPlatformClientServiceMethodActions =
  ApiPlatformClientServiceGetApiPlatformClientAction;
