export const USER_STORAGE_VERSION = '1';

// Force cast. We don't really care about the type here since we treat it as a unique symbol
export const USER_STORAGE_VERSION_KEY: unique symbol = 'v' as never;

export const LOCALIZED_DEFAULT_ACCOUNT_NAMES = [
  'Account',
  'መለያ',
  'الحساب',
  'Профил',
  'অ্যাকাউন্ট',
  'Compte',
  'Účet',
  'Konto',
  'Λογαριασμός',
  'Cuenta',
  'حساب',
  'Tili',
  'એકાઉન્ટ',
  'חשבון',
  'अकाउंट',
  'खाता',
  'Račun',
  'Kont',
  'Fiók',
  'Akun',
  'アカウント',
  'ಖಾತೆ',
  '계정',
  'Paskyra',
  'Konts',
  'അക്കൗണ്ട്',
  'खाते',
  'Akaun',
  'Conta',
  'Cont',
  'Счет',
  'налог',
  'Akaunti',
  'கணக்கு',
  'ఖాతా',
  'บัญชี',
  'Hesap',
  'Обліковий запис',
  'Tài khoản',
  '账户',
  '帳戶',
] as const;
