/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { MultichainAssetsRatesController } from './MultichainAssetsRatesController';

/**
 * Updates token conversion rates for each non-EVM account.
 *
 * @returns A promise that resolves when the rates are updated.
 */
export type MultichainAssetsRatesControllerUpdateAssetsRatesAction = {
  type: `MultichainAssetsRatesController:updateAssetsRates`;
  handler: MultichainAssetsRatesController['updateAssetsRates'];
};

/**
 * Union of all MultichainAssetsRatesController action types.
 */
export type MultichainAssetsRatesControllerMethodActions =
  MultichainAssetsRatesControllerUpdateAssetsRatesAction;
