import type {
  ControllerGetStateAction,
  ControllerStateChangeEvent,
  StateMetadata,
} from '@metamask/base-controller';
import { BaseController } from '@metamask/base-controller';
import type { Messenger } from '@metamask/messenger';
import type {
  EscrowAssertion,
  ExportInitResult,
  SecretEscrowClient,
  WebAuthnEscrowFactor,
} from '@metamask/secret-escrow-client';
import { SecretEscrowError, SecretEscrowErrorCode } from '@metamask/secret-escrow-client';

import { controllerName } from './constants.js';
import type { SecretEscrowControllerMethodActions } from './SecretEscrowController-method-action-types.js';

/**
 * Persisted metadata for an enrolled escrow factor.
 *
 * Never includes the escrowed secret.
 */
export type SecretEscrowRecord = {
  userId: string;
  factorId: string;
  factor: WebAuthnEscrowFactor;
  enrolledAt: number;
};

/**
 * State for {@link SecretEscrowController}.
 */
export type SecretEscrowControllerState = {
  escrowRecord: SecretEscrowRecord | null;
};

/**
 * Options for constructing {@link SecretEscrowController}.
 */
export type SecretEscrowControllerOptions = {
  messenger: SecretEscrowControllerMessenger;
  state?: Partial<SecretEscrowControllerState>;
  /**
   * Escrow backend client. Use {@link MockSecretEscrowClient} until a real
   * backend is wired.
   */
  client: SecretEscrowClient;
};

export type SecretEscrowControllerGetStateAction = ControllerGetStateAction<
  typeof controllerName,
  SecretEscrowControllerState
>;

export type SecretEscrowControllerActions =
  | SecretEscrowControllerGetStateAction
  | SecretEscrowControllerMethodActions;

type AllowedActions = never;

export type SecretEscrowControllerStateChangeEvent = ControllerStateChangeEvent<
  typeof controllerName,
  SecretEscrowControllerState
>;

export type SecretEscrowControllerEvents = SecretEscrowControllerStateChangeEvent;

type AllowedEvents = never;

export type SecretEscrowControllerMessenger = Messenger<
  typeof controllerName,
  SecretEscrowControllerActions | AllowedActions,
  SecretEscrowControllerEvents | AllowedEvents
>;

const secretEscrowControllerMetadata = {
  escrowRecord: {
    persist: true,
    includeInDebugSnapshot: false,
    includeInStateLogs: false,
    usedInUi: true,
  },
} satisfies StateMetadata<SecretEscrowControllerState>;

const MESSENGER_EXPOSED_METHODS = [
  'isEnrolled',
  'enroll',
  'startExport',
  'completeExport',
  'revoke',
  'clearState',
] as const;

/**
 * Returns default state for {@link SecretEscrowController}.
 *
 * @returns Fresh empty state.
 */
export function getDefaultSecretEscrowControllerState(): SecretEscrowControllerState {
  return { escrowRecord: null };
}

/**
 * Selectors for {@link SecretEscrowControllerState}.
 */
export const secretEscrowControllerSelectors = {
  selectIsEnrolled: (state: SecretEscrowControllerState): boolean =>
    state.escrowRecord !== null,
  selectEscrowRecord: (
    state: SecretEscrowControllerState,
  ): SecretEscrowRecord | null => state.escrowRecord,
};

/**
 * Orchestrates WebAuthn-gated secret escrow enrollment and export for
 * social-login passkey recovery.
 *
 * The controller persists only public factor metadata. Secrets returned from
 * `enroll` / `completeExport` must be consumed immediately by the caller
 * (e.g. to wrap a wallet password) and cleared.
 */
export class SecretEscrowController extends BaseController<
  typeof controllerName,
  SecretEscrowControllerState,
  SecretEscrowControllerMessenger
> {
  readonly #client: SecretEscrowClient;

  constructor({ messenger, state, client }: SecretEscrowControllerOptions) {
    super({
      messenger,
      metadata: secretEscrowControllerMetadata,
      name: controllerName,
      state: {
        ...getDefaultSecretEscrowControllerState(),
        ...state,
      },
    });
    this.#client = client;
    this.messenger.registerMethodActionHandlers(
      this,
      MESSENGER_EXPOSED_METHODS,
    );
  }

  /**
   * Whether an escrow factor is enrolled in local state.
   *
   * @returns True when {@link SecretEscrowControllerState.escrowRecord} is set.
   */
  isEnrolled(): boolean {
    return this.state.escrowRecord !== null;
  }

  /**
   * Registers a WebAuthn factor with the escrow and persists local metadata.
   *
   * @param params - Enrollment parameters.
   * @param params.userId - Stable escrow user id.
   * @param params.factorId - Factor id (e.g. `"passkey"`).
   * @param params.factor - Public WebAuthn factor metadata.
   * @param params.secret - Optional 32-byte secret; generated by escrow when omitted.
   * @returns The escrowed secret (caller must clear after use).
   */
  async enroll(params: {
    userId: string;
    factorId: string;
    factor: WebAuthnEscrowFactor;
    secret?: Uint8Array;
  }): Promise<Uint8Array> {
    if (this.state.escrowRecord) {
      throw new SecretEscrowError('Secret escrow already enrolled', {
        code: SecretEscrowErrorCode.AlreadyRegistered,
      });
    }

    const { secret } = await this.#client.register({
      userId: params.userId,
      factorId: params.factorId,
      factor: params.factor,
      secret: params.secret,
    });

    this.update((state) => {
      state.escrowRecord = {
        userId: params.userId,
        factorId: params.factorId,
        factor: structuredClone(params.factor),
        enrolledAt: Date.now(),
      };
    });

    return secret;
  }

  /**
   * Starts an export ceremony and returns the challenge for WebAuthn `get()`.
   *
   * @returns Export challenge.
   */
  async startExport(): Promise<ExportInitResult> {
    const record = this.#requireEnrolled();
    return this.#client.exportInit({
      userId: record.userId,
      factorId: record.factorId,
    });
  }

  /**
   * Completes export with a WebAuthn assertion and returns the escrowed secret.
   *
   * @param assertion - Assertion from `navigator.credentials.get()` (or mock).
   * @returns Released secret (caller must clear after use).
   */
  async completeExport(assertion: EscrowAssertion): Promise<Uint8Array> {
    const record = this.#requireEnrolled();
    const { secret } = await this.#client.exportComplete({
      userId: record.userId,
      factorId: record.factorId,
      assertion,
    });
    return secret;
  }

  /**
   * Revokes escrow material remotely and clears local enrollment state.
   */
  async revoke(): Promise<void> {
    const record = this.state.escrowRecord;
    if (record) {
      await this.#client.revoke({ userId: record.userId });
    }
    this.clearState();
  }

  /**
   * Clears local enrollment state without calling the escrow backend.
   *
   * Prefer {@link revoke} when the remote record should also be deleted.
   */
  clearState(): void {
    this.update((state) => {
      state.escrowRecord = null;
    });
  }

  #requireEnrolled(): SecretEscrowRecord {
    const { escrowRecord } = this.state;
    if (!escrowRecord) {
      throw new SecretEscrowError('Secret escrow is not enrolled', {
        code: SecretEscrowErrorCode.NotRegistered,
      });
    }
    return escrowRecord;
  }
}
