/**
 * This file is auto generated.
 * Do not edit manually.
 */

import type { SecretEscrowController } from './SecretEscrowController';

/**
 * Whether an escrow factor is enrolled in local state.
 *
 * @returns True when {@link SecretEscrowControllerState.escrowRecord} is set.
 */
export type SecretEscrowControllerIsEnrolledAction = {
  type: `SecretEscrowController:isEnrolled`;
  handler: SecretEscrowController['isEnrolled'];
};

/**
 * Lists enrolled public factors from local state.
 *
 * @returns Factor id → public metadata map.
 */
export type SecretEscrowControllerListFactorsAction = {
  type: `SecretEscrowController:listFactors`;
  handler: SecretEscrowController['listFactors'];
};

/**
 * Generates a 32-byte wallet secret `S` suitable for escrow registration.
 *
 * @returns Fresh random secret (caller must clear after use).
 */
export type SecretEscrowControllerGenerateWalletSecretAction = {
  type: `SecretEscrowController:generateWalletSecret`;
  handler: SecretEscrowController['generateWalletSecret'];
};

/**
 * Registers the first factor and escrows wallet secret `S`.
 *
 * Additional factors use {@link addFactor} (1-of-N).
 *
 * @param params - Creation parameters.
 * @param params.userId - Stable escrow user id.
 * @param params.factorId - Factor id (e.g. `"password"` or `"passkey"`).
 * @param params.factor - Factor payload (password includes plaintext once).
 * @param params.secret - Optional 32-byte `S`; generated when omitted.
 * @returns The escrowed wallet secret (caller must clear after use).
 */
export type SecretEscrowControllerCreateWithWalletSecretAction = {
  type: `SecretEscrowController:createWithWalletSecret`;
  handler: SecretEscrowController['createWithWalletSecret'];
};

/**
 * Adds another factor to an existing escrow enrollment (1-of-N).
 *
 * @param params - Add-factor parameters.
 * @param params.factorId - New factor id.
 * @param params.factor - Factor payload.
 */
export type SecretEscrowControllerAddFactorAction = {
  type: `SecretEscrowController:addFactor`;
  handler: SecretEscrowController['addFactor'];
};

/**
 * Replaces the wrapped wallet password ciphertext under the given escrow
 * secret `S` (e.g. after rotating the vault password during onboarding).
 *
 * @param params - Rewrap parameters.
 * @param params.password - New wallet password to wrap.
 * @param params.secret - Escrow-released wallet secret `S`.
 */
export type SecretEscrowControllerUpdateWrappedPasswordAction = {
  type: `SecretEscrowController:updateWrappedPassword`;
  handler: SecretEscrowController['updateWrappedPassword'];
};

/**
 * Registers the first factor, escrows wallet secret `S`, and wraps the wallet
 * password under `S` for TOPRF coexistence during migration.
 *
 * @param params - Creation parameters including plaintext password to wrap.
 * @param params.userId - Stable escrow user id.
 * @param params.factorId - Factor id (e.g. `"password"` or `"passkey"`).
 * @param params.factor - Factor payload.
 * @param params.password - Wallet password to wrap.
 * @param params.secret - Optional 32-byte `S`; generated when omitted.
 */
export type SecretEscrowControllerCreateWithWalletSecretAndWrapPasswordAction =
  {
    type: `SecretEscrowController:createWithWalletSecretAndWrapPassword`;
    handler: SecretEscrowController['createWithWalletSecretAndWrapPassword'];
  };

/**
 * Registers a WebAuthn factor with the escrow and persists local metadata.
 *
 * @deprecated Prefer {@link createWithWalletSecret} for new flows.
 * @param params - Enrollment parameters.
 * @param params.userId - Stable escrow user id.
 * @param params.factorId - Factor id (e.g. `"passkey"`).
 * @param params.factor - Public WebAuthn factor metadata.
 * @param params.secret - Optional 32-byte secret; generated by escrow when omitted.
 * @returns The escrowed secret (caller must clear after use).
 */
export type SecretEscrowControllerEnrollAction = {
  type: `SecretEscrowController:enroll`;
  handler: SecretEscrowController['enroll'];
};

/**
 * Enrolls a WebAuthn factor and wraps the wallet password under the escrow
 * secret for later Social + Passkey recovery.
 *
 * Legacy coexistence bridge while TOPRF remains password-based.
 *
 * @param params - Enrollment parameters including plaintext password.
 * @param params.userId - Stable escrow user id.
 * @param params.factorId - Factor id (e.g. `"passkey"`).
 * @param params.factor - Public WebAuthn factor metadata.
 * @param params.password - Wallet password to wrap (TOPRF factor).
 * @param params.secret - Optional 32-byte secret; generated by escrow when omitted.
 */
export type SecretEscrowControllerEnrollAndWrapPasswordAction = {
  type: `SecretEscrowController:enrollAndWrapPassword`;
  handler: SecretEscrowController['enrollAndWrapPassword'];
};

/**
 * Restores local enrollment from a remote escrow that persists public
 * metadata (e.g. the file-backed mock HTTP server).
 *
 * No-op when already enrolled locally or when the client cannot fetch
 * enrollment metadata. Used after wallet wipe + social rehydration.
 *
 * @param userId - Stable escrow user id.
 * @returns True when local state was hydrated from remote.
 */
export type SecretEscrowControllerHydrateFromRemoteAction = {
  type: `SecretEscrowController:hydrateFromRemote`;
  handler: SecretEscrowController['hydrateFromRemote'];
};

/**
 * Starts an export ceremony and returns the challenge for the factor proof.
 *
 * @param factorId - Optional factor id; defaults to the enrolled default.
 * @returns Export challenge.
 */
export type SecretEscrowControllerStartExportAction = {
  type: `SecretEscrowController:startExport`;
  handler: SecretEscrowController['startExport'];
};

/**
 * Completes export with a WebAuthn assertion for the default factor.
 *
 * Legacy helper — prefer {@link unlockWithFactor} for multi-factor flows.
 *
 * @param assertion - Assertion from `navigator.credentials.get()` (or mock).
 * @returns Released secret (caller must clear after use).
 */
export type SecretEscrowControllerCompleteExportAction = {
  type: `SecretEscrowController:completeExport`;
  handler: SecretEscrowController['completeExport'];
};

/**
 * Completes export for any enrolled factor (1-of-N) and returns wallet secret `S`.
 *
 * Caller must have already called {@link startExport} for the same factor.
 *
 * @param params - Unlock parameters.
 * @param params.factorId - Factor to prove.
 * @param params.proof - Factor proof (webauthn assertion or password).
 * @returns Released wallet secret (caller must clear after use).
 */
export type SecretEscrowControllerUnlockWithFactorAction = {
  type: `SecretEscrowController:unlockWithFactor`;
  handler: SecretEscrowController['unlockWithFactor'];
};

/**
 * Recovers the wrapped wallet password after a successful WebAuthn assertion.
 *
 * Legacy coexistence bridge only.
 *
 * @param assertion - Assertion from `navigator.credentials.get()` (or mock).
 * @param factorId - Optional factor id; defaults to the enrolled default.
 * @returns Plaintext wallet password (caller must clear after use).
 */
export type SecretEscrowControllerRecoverPasswordAction = {
  type: `SecretEscrowController:recoverPassword`;
  handler: SecretEscrowController['recoverPassword'];
};

/**
 * Revokes escrow material remotely and clears local enrollment state.
 */
export type SecretEscrowControllerRevokeAction = {
  type: `SecretEscrowController:revoke`;
  handler: SecretEscrowController['revoke'];
};

/**
 * Clears local enrollment state without calling the escrow backend.
 *
 * Prefer {@link revoke} when the remote record should also be deleted.
 */
export type SecretEscrowControllerClearStateAction = {
  type: `SecretEscrowController:clearState`;
  handler: SecretEscrowController['clearState'];
};

/**
 * Union of all SecretEscrowController action types.
 */
export type SecretEscrowControllerMethodActions =
  | SecretEscrowControllerIsEnrolledAction
  | SecretEscrowControllerListFactorsAction
  | SecretEscrowControllerGenerateWalletSecretAction
  | SecretEscrowControllerCreateWithWalletSecretAction
  | SecretEscrowControllerAddFactorAction
  | SecretEscrowControllerUpdateWrappedPasswordAction
  | SecretEscrowControllerCreateWithWalletSecretAndWrapPasswordAction
  | SecretEscrowControllerEnrollAction
  | SecretEscrowControllerEnrollAndWrapPasswordAction
  | SecretEscrowControllerHydrateFromRemoteAction
  | SecretEscrowControllerStartExportAction
  | SecretEscrowControllerCompleteExportAction
  | SecretEscrowControllerUnlockWithFactorAction
  | SecretEscrowControllerRecoverPasswordAction
  | SecretEscrowControllerRevokeAction
  | SecretEscrowControllerClearStateAction;
