/**
 * This file is auto generated.
 * Do not edit manually.
 */

import type { SecretEscrowController } from './SecretEscrowController';

/**
 * Whether an escrow factor is enrolled in local state.
 *
 * @returns True when {@link SecretEscrowControllerState.escrowRecord} is set.
 */
export type SecretEscrowControllerIsEnrolledAction = {
  type: `SecretEscrowController:isEnrolled`;
  handler: SecretEscrowController['isEnrolled'];
};

/**
 * Registers a WebAuthn factor with the escrow and persists local metadata.
 *
 * @param params - Enrollment parameters.
 * @param params.userId - Stable escrow user id.
 * @param params.factorId - Factor id (e.g. `"passkey"`).
 * @param params.factor - Public WebAuthn factor metadata.
 * @param params.secret - Optional 32-byte secret; generated by escrow when omitted.
 * @returns The escrowed secret (caller must clear after use).
 */
export type SecretEscrowControllerEnrollAction = {
  type: `SecretEscrowController:enroll`;
  handler: SecretEscrowController['enroll'];
};

/**
 * Enrolls a WebAuthn factor and wraps the wallet password under the escrow
 * secret for later Social + Passkey recovery.
 *
 * @param params - Enrollment parameters including plaintext password.
 * @param params.userId - Stable escrow user id.
 * @param params.factorId - Factor id (e.g. `"passkey"`).
 * @param params.factor - Public WebAuthn factor metadata.
 * @param params.password - Wallet password to wrap (TOPRF factor).
 * @param params.secret - Optional 32-byte secret; generated by escrow when omitted.
 */
export type SecretEscrowControllerEnrollAndWrapPasswordAction = {
  type: `SecretEscrowController:enrollAndWrapPassword`;
  handler: SecretEscrowController['enrollAndWrapPassword'];
};

/**
 * Starts an export ceremony and returns the challenge for WebAuthn `get()`.
 *
 * @returns Export challenge.
 */
export type SecretEscrowControllerStartExportAction = {
  type: `SecretEscrowController:startExport`;
  handler: SecretEscrowController['startExport'];
};

/**
 * Completes export with a WebAuthn assertion and returns the escrowed secret.
 *
 * @param assertion - Assertion from `navigator.credentials.get()` (or mock).
 * @returns Released secret (caller must clear after use).
 */
export type SecretEscrowControllerCompleteExportAction = {
  type: `SecretEscrowController:completeExport`;
  handler: SecretEscrowController['completeExport'];
};

/**
 * Recovers the wrapped wallet password after a successful WebAuthn assertion.
 *
 * @param assertion - Assertion from `navigator.credentials.get()` (or mock).
 * @returns Plaintext wallet password (caller must clear after use).
 */
export type SecretEscrowControllerRecoverPasswordAction = {
  type: `SecretEscrowController:recoverPassword`;
  handler: SecretEscrowController['recoverPassword'];
};

/**
 * Revokes escrow material remotely and clears local enrollment state.
 */
export type SecretEscrowControllerRevokeAction = {
  type: `SecretEscrowController:revoke`;
  handler: SecretEscrowController['revoke'];
};

/**
 * Clears local enrollment state without calling the escrow backend.
 *
 * Prefer {@link revoke} when the remote record should also be deleted.
 */
export type SecretEscrowControllerClearStateAction = {
  type: `SecretEscrowController:clearState`;
  handler: SecretEscrowController['clearState'];
};

/**
 * Union of all SecretEscrowController action types.
 */
export type SecretEscrowControllerMethodActions =
  | SecretEscrowControllerIsEnrolledAction
  | SecretEscrowControllerEnrollAction
  | SecretEscrowControllerEnrollAndWrapPasswordAction
  | SecretEscrowControllerStartExportAction
  | SecretEscrowControllerCompleteExportAction
  | SecretEscrowControllerRecoverPasswordAction
  | SecretEscrowControllerRevokeAction
  | SecretEscrowControllerClearStateAction;
