/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { AccountTrackerController } from './AccountTrackerController';

/**
 * Updates the balances of multiple native tokens in a single batch operation.
 * This is more efficient than calling updateNativeToken multiple times as it
 * triggers only one state update.
 *
 * @param balances - Array of balance updates, each containing address, chainId, and balance.
 */
export type AccountTrackerControllerUpdateNativeBalancesAction = {
  type: `AccountTrackerController:updateNativeBalances`;
  handler: AccountTrackerController['updateNativeBalances'];
};

/**
 * Updates the staked balances of multiple accounts in a single batch operation.
 * This is more efficient than updating staked balances individually as it
 * triggers only one state update.
 *
 * @param stakedBalances - Array of staked balance updates, each containing address, chainId, and stakedBalance.
 */
export type AccountTrackerControllerUpdateStakedBalancesAction = {
  type: `AccountTrackerController:updateStakedBalances`;
  handler: AccountTrackerController['updateStakedBalances'];
};

/**
 * Union of all AccountTrackerController action types.
 */
export type AccountTrackerControllerMethodActions =
  | AccountTrackerControllerUpdateNativeBalancesAction
  | AccountTrackerControllerUpdateStakedBalancesAction;
