/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { AssetsContractController } from './AssetsContractController';

/**
 * Get a ERC20Standard instance using the relevant provider instance.
 *
 * @param networkClientId - Network Client ID used to get the provider.
 * @returns ERC20Standard instance.
 */
export type AssetsContractControllerGetERC20StandardAction = {
  type: `AssetsContractController:getERC20Standard`;
  handler: AssetsContractController['getERC20Standard'];
};

/**
 * Get a ERC721Standard instance using the relevant provider instance.
 *
 * @param networkClientId - Network Client ID used to get the provider.
 * @returns ERC721Standard instance.
 */
export type AssetsContractControllerGetERC721StandardAction = {
  type: `AssetsContractController:getERC721Standard`;
  handler: AssetsContractController['getERC721Standard'];
};

/**
 * Get a ERC1155Standard instance using the relevant provider instance.
 *
 * @param networkClientId - Network Client ID used to get the provider.
 * @returns ERC1155Standard instance.
 */
export type AssetsContractControllerGetERC1155StandardAction = {
  type: `AssetsContractController:getERC1155Standard`;
  handler: AssetsContractController['getERC1155Standard'];
};

/**
 * Get balance or count for current account on specific asset contract.
 *
 * @param address - Asset ERC20 contract address.
 * @param selectedAddress - Current account public address.
 * @param networkClientId - Network Client ID to fetch the provider with.
 * @returns Promise resolving to BN object containing balance for current account on specific asset contract.
 */
export type AssetsContractControllerGetERC20BalanceOfAction = {
  type: `AssetsContractController:getERC20BalanceOf`;
  handler: AssetsContractController['getERC20BalanceOf'];
};

/**
 * Query for the decimals for a given ERC20 asset.
 *
 * @param address - ERC20 asset contract address.
 * @param networkClientId - Network Client ID to fetch the provider with.
 * @returns Promise resolving to the 'decimals'.
 */
export type AssetsContractControllerGetERC20TokenDecimalsAction = {
  type: `AssetsContractController:getERC20TokenDecimals`;
  handler: AssetsContractController['getERC20TokenDecimals'];
};

/**
 * Query for the name for a given ERC20 asset.
 *
 * @param address - ERC20 asset contract address.
 * @param networkClientId - Network Client ID to fetch the provider with.
 * @returns Promise resolving to the 'decimals'.
 */
export type AssetsContractControllerGetERC20TokenNameAction = {
  type: `AssetsContractController:getERC20TokenName`;
  handler: AssetsContractController['getERC20TokenName'];
};

/**
 * Enumerate assets assigned to an owner.
 *
 * @param address - ERC721 asset contract address.
 * @param selectedAddress - Current account public address.
 * @param index - An NFT counter less than `balanceOf(selectedAddress)`.
 * @param networkClientId - Network Client ID to fetch the provider with.
 * @returns Promise resolving to token identifier for the 'index'th asset assigned to 'selectedAddress'.
 */
export type AssetsContractControllerGetERC721NftTokenIdAction = {
  type: `AssetsContractController:getERC721NftTokenId`;
  handler: AssetsContractController['getERC721NftTokenId'];
};

/**
 * Enumerate assets assigned to an owner.
 *
 * @param tokenAddress - ERC721 asset contract address.
 * @param userAddress - Current account public address.
 * @param tokenId - ERC721 asset identifier.
 * @param networkClientId - Network Client ID to fetch the provider with.
 * @returns Promise resolving to an object containing the token standard and a set of details which depend on which standard the token supports.
 */
export type AssetsContractControllerGetTokenStandardAndDetailsAction = {
  type: `AssetsContractController:getTokenStandardAndDetails`;
  handler: AssetsContractController['getTokenStandardAndDetails'];
};

/**
 * Query for tokenURI for a given ERC721 asset.
 *
 * @param address - ERC721 asset contract address.
 * @param tokenId - ERC721 asset identifier.
 * @param networkClientId - Network Client ID to fetch the provider with.
 * @returns Promise resolving to the 'tokenURI'.
 */
export type AssetsContractControllerGetERC721TokenURIAction = {
  type: `AssetsContractController:getERC721TokenURI`;
  handler: AssetsContractController['getERC721TokenURI'];
};

/**
 * Query for name for a given asset.
 *
 * @param address - ERC721 or ERC20 asset contract address.
 * @param networkClientId - Network Client ID to fetch the provider with.
 * @returns Promise resolving to the 'name'.
 */
export type AssetsContractControllerGetERC721AssetNameAction = {
  type: `AssetsContractController:getERC721AssetName`;
  handler: AssetsContractController['getERC721AssetName'];
};

/**
 * Query for symbol for a given asset.
 *
 * @param address - ERC721 or ERC20 asset contract address.
 * @param networkClientId - Network Client ID to fetch the provider with.
 * @returns Promise resolving to the 'symbol'.
 */
export type AssetsContractControllerGetERC721AssetSymbolAction = {
  type: `AssetsContractController:getERC721AssetSymbol`;
  handler: AssetsContractController['getERC721AssetSymbol'];
};

/**
 * Query for owner for a given ERC721 asset.
 *
 * @param address - ERC721 asset contract address.
 * @param tokenId - ERC721 asset identifier.
 * @param networkClientId - Network Client ID to fetch the provider with.
 * @returns Promise resolving to the owner address.
 */
export type AssetsContractControllerGetERC721OwnerOfAction = {
  type: `AssetsContractController:getERC721OwnerOf`;
  handler: AssetsContractController['getERC721OwnerOf'];
};

/**
 * Query for tokenURI for a given asset.
 *
 * @param address - ERC1155 asset contract address.
 * @param tokenId - ERC1155 asset identifier.
 * @param networkClientId - Network Client ID to fetch the provider with.
 * @returns Promise resolving to the 'tokenURI'.
 */
export type AssetsContractControllerGetERC1155TokenURIAction = {
  type: `AssetsContractController:getERC1155TokenURI`;
  handler: AssetsContractController['getERC1155TokenURI'];
};

/**
 * Query for balance of a given ERC 1155 token.
 *
 * @param userAddress - Wallet public address.
 * @param nftAddress - ERC1155 asset contract address.
 * @param nftId - ERC1155 asset identifier.
 * @param networkClientId - Network Client ID to fetch the provider with.
 * @returns Promise resolving to the 'balanceOf'.
 */
export type AssetsContractControllerGetERC1155BalanceOfAction = {
  type: `AssetsContractController:getERC1155BalanceOf`;
  handler: AssetsContractController['getERC1155BalanceOf'];
};

/**
 * Transfer single ERC1155 token.
 *
 * @param nftAddress - ERC1155 token address.
 * @param senderAddress - ERC1155 token sender.
 * @param recipientAddress - ERC1155 token recipient.
 * @param nftId - ERC1155 token id.
 * @param qty - Quantity of tokens to be sent.
 * @param networkClientId - Network Client ID to fetch the provider with.
 * @returns Promise resolving to the 'transferSingle' ERC1155 token.
 */
export type AssetsContractControllerTransferSingleERC1155Action = {
  type: `AssetsContractController:transferSingleERC1155`;
  handler: AssetsContractController['transferSingleERC1155'];
};

/**
 * Get the token balance for a list of token addresses in a single call. Only non-zero balances
 * are returned.
 *
 * @param selectedAddress - The address to check token balances for.
 * @param tokensToDetect - The token addresses to detect balances for.
 * @param networkClientId - Network Client ID to fetch the provider with.
 * @returns The list of non-zero token balances.
 */
export type AssetsContractControllerGetBalancesInSingleCallAction = {
  type: `AssetsContractController:getBalancesInSingleCall`;
  handler: AssetsContractController['getBalancesInSingleCall'];
};

/**
 * Get the staked ethereum balance for multiple addresses in a single call.
 *
 * @param addresses - The addresses to check staked ethereum balance for.
 * @param networkClientId - Network Client ID to fetch the provider with.
 * @returns The hex staked ethereum balance for address.
 */
export type AssetsContractControllerGetStakedBalanceForChainAction = {
  type: `AssetsContractController:getStakedBalanceForChain`;
  handler: AssetsContractController['getStakedBalanceForChain'];
};

/**
 * Union of all AssetsContractController action types.
 */
export type AssetsContractControllerMethodActions =
  | AssetsContractControllerGetERC20StandardAction
  | AssetsContractControllerGetERC721StandardAction
  | AssetsContractControllerGetERC1155StandardAction
  | AssetsContractControllerGetERC20BalanceOfAction
  | AssetsContractControllerGetERC20TokenDecimalsAction
  | AssetsContractControllerGetERC20TokenNameAction
  | AssetsContractControllerGetERC721NftTokenIdAction
  | AssetsContractControllerGetTokenStandardAndDetailsAction
  | AssetsContractControllerGetERC721TokenURIAction
  | AssetsContractControllerGetERC721AssetNameAction
  | AssetsContractControllerGetERC721AssetSymbolAction
  | AssetsContractControllerGetERC721OwnerOfAction
  | AssetsContractControllerGetERC1155TokenURIAction
  | AssetsContractControllerGetERC1155BalanceOfAction
  | AssetsContractControllerTransferSingleERC1155Action
  | AssetsContractControllerGetBalancesInSingleCallAction
  | AssetsContractControllerGetStakedBalanceForChainAction;
