/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { TokenDetectionController } from './TokenDetectionController';

/**
 * Allows controller to make active and passive polling requests
 */
export type TokenDetectionControllerEnableAction = {
  type: `TokenDetectionController:enable`;
  handler: TokenDetectionController['enable'];
};

/**
 * Blocks controller from making network calls
 */
export type TokenDetectionControllerDisableAction = {
  type: `TokenDetectionController:disable`;
  handler: TokenDetectionController['disable'];
};

/**
 * Start polling for detected tokens.
 */
export type TokenDetectionControllerStartAction = {
  type: `TokenDetectionController:start`;
  handler: TokenDetectionController['start'];
};

/**
 * Stop polling for detected tokens.
 */
export type TokenDetectionControllerStopAction = {
  type: `TokenDetectionController:stop`;
  handler: TokenDetectionController['stop'];
};

/**
 * For each token in the token list provided by the TokenListController, checks the token's balance for the selected account address on the active network.
 * On mainnet, if token detection is disabled in preferences, ERC20 token auto detection will be triggered for each contract address in the legacy token list from the @metamask/contract-metadata repo.
 *
 * @param options - Options for token detection.
 * @param options.chainIds - The chain IDs of the network client to use.
 * @param options.selectedAddress - the selectedAddress against which to detect for token balances.
 * @param options.forceRpc - Force RPC-based token detection for all specified chains,
 * bypassing external services check and ensuring RPC is used even for chains
 * that might otherwise be handled by the Accounts API.
 */
export type TokenDetectionControllerDetectTokensAction = {
  type: `TokenDetectionController:detectTokens`;
  handler: TokenDetectionController['detectTokens'];
};

/**
 * Add tokens detected from websocket balance updates
 * This method:
 * - Checks if useTokenDetection preference is enabled (skips if disabled)
 * - Checks if external services are enabled (skips if disabled)
 * - Tokens are expected to be in the tokensChainsCache with full metadata
 * - Balance fetching is skipped since balances are provided by the websocket
 * - Ignored tokens have been filtered out by the caller
 *
 * @param options - The options object
 * @param options.tokensSlice - Array of token addresses detected from websocket (already filtered to exclude ignored tokens)
 * @param options.chainId - Hex chain ID
 * @returns Promise that resolves when tokens are added
 */
export type TokenDetectionControllerAddDetectedTokensViaWsAction = {
  type: `TokenDetectionController:addDetectedTokensViaWs`;
  handler: TokenDetectionController['addDetectedTokensViaWs'];
};

/**
 * Add tokens detected from polling balance updates
 * This method:
 * - Checks if useTokenDetection preference is enabled (skips if disabled)
 * - Checks if external services are enabled (skips if disabled)
 * - Filters out tokens already in allTokens or allIgnoredTokens
 * - Tokens are expected to be in the tokensChainsCache with full metadata
 * - Balance fetching is skipped since balances are provided by the caller
 *
 * @param options - The options object
 * @param options.tokensSlice - Array of token addresses detected from polling
 * @param options.chainId - Hex chain ID
 * @returns Promise that resolves when tokens are added
 */
export type TokenDetectionControllerAddDetectedTokensViaPollingAction = {
  type: `TokenDetectionController:addDetectedTokensViaPolling`;
  handler: TokenDetectionController['addDetectedTokensViaPolling'];
};

/**
 * Union of all TokenDetectionController action types.
 */
export type TokenDetectionControllerMethodActions =
  | TokenDetectionControllerEnableAction
  | TokenDetectionControllerDisableAction
  | TokenDetectionControllerStartAction
  | TokenDetectionControllerStopAction
  | TokenDetectionControllerDetectTokensAction
  | TokenDetectionControllerAddDetectedTokensViaWsAction
  | TokenDetectionControllerAddDetectedTokensViaPollingAction;
