/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { TokenBalancesController } from './TokenBalancesController';

export type TokenBalancesControllerGetChainPollingConfigAction = {
  type: `TokenBalancesController:getChainPollingConfig`;
  handler: TokenBalancesController['getChainPollingConfig'];
};

export type TokenBalancesControllerUpdateChainPollingConfigsAction = {
  type: `TokenBalancesController:updateChainPollingConfigs`;
  handler: TokenBalancesController['updateChainPollingConfigs'];
};

/**
 * Union of all TokenBalancesController action types.
 */
export type TokenBalancesControllerMethodActions =
  | TokenBalancesControllerGetChainPollingConfigAction
  | TokenBalancesControllerUpdateChainPollingConfigsAction;
