/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { NameController } from './NameController';

/**
 * Set the user specified name for a value.
 *
 * @param request - Request object.
 * @param request.name - Name to set.
 * @param request.sourceId - Optional ID of the source of the proposed name.
 * @param request.type - Type of value to set the name for.
 * @param request.value - Value to set the name for.
 * @param request.variation - Variation of the raw value to set the name for. The chain ID if the type is Ethereum address.
 */
export type NameControllerSetNameAction = {
  type: `NameController:setName`;
  handler: NameController['setName'];
};

/**
 * Generate the proposed names for a value using the name providers and store them in the state.
 *
 * @param request - Request object.
 * @param request.value - Value to update the proposed names for.
 * @param request.type - Type of value to update the proposed names for.
 * @param request.sourceIds - Optional array of source IDs to limit which sources are used by the providers. If not provided, all sources in all providers will be used.
 * @param request.variation - Variation of the raw value to update proposed names for. The chain ID if the type is Ethereum address.
 * @returns The updated proposed names for the value.
 */
export type NameControllerUpdateProposedNamesAction = {
  type: `NameController:updateProposedNames`;
  handler: NameController['updateProposedNames'];
};

/**
 * Union of all NameController action types.
 */
export type NameControllerMethodActions =
  | NameControllerSetNameAction
  | NameControllerUpdateProposedNamesAction;
