import type {
  AccountGroupId,
  Bip44Account,
  MultichainAccountWalletId,
  MultichainAccountWallet as MultichainAccountWalletDefinition,
  MultichainAccountWalletStatus,
} from '@metamask/account-api';
import {
  AccountWalletType,
  getGroupIndexFromMultichainAccountGroupId,
  isMultichainAccountGroupId,
  toDefaultAccountGroupId,
  toMultichainAccountWalletId,
} from '@metamask/account-api';
import type { TraceCallback, TraceRequest } from '@metamask/controller-utils';
import { AccountCreationType } from '@metamask/keyring-api';
import type { EntropySourceId, KeyringAccount } from '@metamask/keyring-api';
import { assert } from '@metamask/utils';
import { Mutex } from 'async-mutex';

import { toProviderDataTraces, traceFallback, TraceName } from './analytics';
import { reportError } from './errors';
import type { Logger } from './logger';
import {
  createModuleLogger,
  ERROR_PREFIX,
  projectLogger as log,
  WARNING_PREFIX,
} from './logger';
import type { GroupState } from './MultichainAccountGroup';
import { MultichainAccountGroup } from './MultichainAccountGroup';
import type { ServiceState, StateKeys } from './MultichainAccountService';
import type { Bip44AccountProvider } from './providers';
import { EvmAccountProvider } from './providers/EvmAccountProvider';
import type { MultichainAccountServiceMessenger } from './types';
import {
  assertGroupIndexIsValid,
  assertGroupIndexRangeIsValid,
  GroupIndexRange,
  toErrorMessage,
} from './utils';

/**
 * The context for a provider discovery.
 */
type AccountProviderDiscoveryContext<
  Account extends Bip44Account<KeyringAccount>,
> = {
  provider: Bip44AccountProvider<Account>;
  stopped: boolean;
  groupIndex: number;
  accounts: Account[];
};

export type WalletState = ServiceState[StateKeys['entropySource']];

// type alias to make clear this state is generated by discovery
type DiscoveredGroupsState = WalletState;

/**
 * A multichain account wallet that holds multiple multichain accounts (one multichain account per
 * group index).
 */
export class MultichainAccountWallet<
  Account extends Bip44Account<KeyringAccount>,
> implements MultichainAccountWalletDefinition<Account> {
  readonly #lock = new Mutex();

  readonly #id: MultichainAccountWalletId;

  readonly #providers: Bip44AccountProvider<Account>[];

  readonly #entropySource: EntropySourceId;

  readonly #accountGroups: Map<number, MultichainAccountGroup<Account>>;

  readonly #messenger: MultichainAccountServiceMessenger;

  readonly #trace: TraceCallback;

  readonly #log: Logger;

  #initialized = false;

  #status: MultichainAccountWalletStatus;

  constructor({
    providers,
    entropySource,
    messenger,
    trace,
  }: {
    providers: Bip44AccountProvider<Account>[];
    entropySource: EntropySourceId;
    messenger: MultichainAccountServiceMessenger;
    trace?: TraceCallback;
  }) {
    this.#id = toMultichainAccountWalletId(entropySource);
    this.#providers = providers;
    this.#entropySource = entropySource;
    this.#messenger = messenger;
    this.#accountGroups = new Map();
    this.#trace = trace ?? traceFallback;

    this.#log = createModuleLogger(log, `[${this.#id}]`);

    // Initial synchronization (don't emit events during initialization).
    this.#status = 'uninitialized';
  }

  /**
   * Initialize the wallet and construct the internal representation of multichain account groups.
   *
   * @param walletState - The wallet state.
   */
  init(walletState: WalletState): void {
    this.#log('Initializing wallet state...');
    for (const [groupIndexString, groupState] of Object.entries(walletState)) {
      // Have to convert to number because the state keys become strings when we construct the state object in the service
      const groupIndex = Number(groupIndexString);
      const group = new MultichainAccountGroup({
        groupIndex,
        wallet: this,
        providers: this.#providers,
        messenger: this.#messenger,
      });

      this.#log(`Creating new group for index ${groupIndex}...`);

      group.init(groupState);

      this.#accountGroups.set(groupIndex, group);
    }
    if (!this.#initialized) {
      this.#initialized = true;
      this.#status = 'ready';
    }

    this.#log('Finished initializing wallet state...');
  }

  /**
   * Gets the multichain account wallet ID.
   *
   * @returns The multichain account wallet ID.
   */
  get id(): MultichainAccountWalletId {
    return this.#id;
  }

  /**
   * Gets the multichain account wallet type, which is always {@link AccountWalletType.Entropy}.
   *
   * @returns The multichain account wallet type.
   */
  get type(): AccountWalletType.Entropy {
    return AccountWalletType.Entropy;
  }

  /**
   * Gets the multichain account wallet entropy source.
   *
   * @returns The multichain account wallet entropy source.
   */
  get entropySource(): EntropySourceId {
    return this.#entropySource;
  }

  /**
   * Gets the multichain account wallet current status.
   *
   * @returns The multichain account wallet current status.
   */
  get status(): MultichainAccountWalletStatus {
    return this.#status;
  }

  /**
   * Set the wallet status and run the associated operation callback.
   *
   * @param status - Wallet status associated with this operation.
   * @param operation - Operation to run.
   * @returns The operation's result.
   * @throws {Error} If the wallet is already running a mutable operation.
   */
  async #withLock<Return>(
    status: MultichainAccountWalletStatus,
    operation: () => Promise<Return>,
  ): Promise<Return> {
    const release = await this.#lock.acquire();
    try {
      this.#log(`Locking wallet with status "${status}"...`);
      this.#status = status;
      this.#messenger.publish(
        'MultichainAccountService:walletStatusChange',
        this.id,
        this.#status,
      );
      return await operation();
    } finally {
      this.#status = 'ready';
      this.#messenger.publish(
        'MultichainAccountService:walletStatusChange',
        this.id,
        this.#status,
      );
      release();
      this.#log(`Releasing wallet lock (was "${status}")`);
    }
  }

  /**
   * Gets the providers and ensure the EVM provider is located at index 0.
   *
   * @returns The account providers.
   */
  #getProviders(): Bip44AccountProvider<Account>[] {
    const [evmProvider, ...otherProviders] = this.#providers;
    assert(
      evmProvider instanceof EvmAccountProvider,
      'EVM account provider must be first',
    );

    return [evmProvider, ...otherProviders];
  }

  /**
   * Create accounts for a given provider and group index range.
   *
   * @param provider - The provider to create accounts for.
   * @param from - The starting group index (inclusive).
   * @param to - The ending group index (inclusive).
   * @returns The created accounts.
   */
  async #createAccountsRangeForProvider(
    provider: Bip44AccountProvider<Account>,
    from: number,
    to: number,
  ): Promise<Bip44Account<Account>[]> {
    const isBatching = to > from;

    try {
      return await provider.createAccounts({
        type: AccountCreationType.Bip44DeriveIndexRange,
        entropySource: this.#entropySource,
        range: {
          from,
          to,
        },
      });
    } catch (error) {
      reportError(
        this.#messenger,
        `Unable to create ${isBatching ? 'some accounts (batch)' : 'some accounts'} with provider "${provider.getName()}"`,
        error,
        {
          range: { from, to },
          provider: provider.getName(),
          isBatching,
        },
      );
      throw error;
    }
  }

  /**
   * Create or update a multichain account group state for a given group index and group state.
   *
   * @param groupIndex The group's index.
   * @param groupState The group's state to create or update the group with.
   * @returns The created or updated multichain account group.
   */
  #createOrUpdateMultichainAccountGroup(
    groupIndex: number,
    groupState: GroupState,
  ): MultichainAccountGroup<Account> {
    let group = this.#accountGroups.get(groupIndex);
    if (group) {
      // NOTE: This will publish an update event automatically.
      group.update(groupState);

      this.#log(`Group updated: [${group.id}]`);
    } else {
      group = new MultichainAccountGroup({
        wallet: this,
        providers: this.#providers,
        groupIndex,
        messenger: this.#messenger,
      });
      group.init(groupState);

      this.#accountGroups.set(groupIndex, group);

      this.#log(`Group created: [${group.id}]`);

      if (this.#initialized) {
        this.#messenger.publish(
          'MultichainAccountService:multichainAccountGroupCreated',
          group,
        );
      }
    }

    return group;
  }

  /**
   * Build group state for a range of group indices by calling all providers in parallel.
   *
   * This is a non-locking shared core used by both creation and alignment paths.
   *
   * @param from - Starting group index (inclusive).
   * @param to - Ending group index (inclusive).
   * @param providers - The providers to create accounts for.
   * @returns The collected group state and any provider failure messages.
   */
  async #buildGroupStateForRange(
    from: number,
    to: number,
    providers: Bip44AccountProvider<Account>[],
  ): Promise<{
    groupStateByGroupIndex: Map<number, GroupState>;
    failures: string[];
  }> {
    const groupStateByGroupIndex = new Map<number, GroupState>();

    const results = await Promise.allSettled(
      providers.map(async (provider) => {
        const providerName = provider.getName();
        const accounts = await this.#createAccountsRangeForProvider(
          provider,
          from,
          to,
        );
        accounts.forEach((account) => {
          const { groupIndex } = account.options.entropy;
          let groupState = groupStateByGroupIndex.get(groupIndex);
          if (!groupState) {
            groupState = {};
            groupStateByGroupIndex.set(groupIndex, groupState);
          }
          if (!groupState[providerName]) {
            groupState[providerName] = [];
          }
          groupState[providerName].push(account.id);
        });
      }),
    );

    const failures = providers.reduce((messages: string[], provider, index) => {
      const result = results[index];
      if (result?.status === 'rejected') {
        messages.push(
          `[${provider.getName()}] ${toErrorMessage(result.reason)}`,
        );
      }
      return messages;
    }, []);

    return { groupStateByGroupIndex, failures };
  }

  /**
   * Internal method to create a range of multichain account groups.
   *
   * This method acquires the wallet lock internally and creates accounts for all
   * given providers synchronously. Callers decide which providers to pass.
   *
   * @param range - The range of group indices to create.
   * @param range.from - Starting group index to create (inclusive).
   * @param range.to - Maximum group index to create (inclusive).
   * @param providers - The providers to create accounts for.
   * @returns Array of created multichain account groups.
   */
  async #createMultichainAccountGroupsRange(
    { from: rangeFrom, to }: Required<GroupIndexRange>,
    providers: Bip44AccountProvider<Account>[],
  ): Promise<MultichainAccountGroup<Account>[]> {
    return await this.#withLock('in-progress:create-accounts', async () => {
      const groups: MultichainAccountGroup<Account>[] = [];

      // Get existing groups (fromGroupIndex to nextGroupIndex - 1).
      let from = rangeFrom;
      for (; from <= to; from++) {
        const group = this.getMultichainAccountGroup(from);
        if (group) {
          groups.push(group);
        } else {
          break; // Assuming we have no gap, if the group does not exist, we can stop and create the remaining ones.
        }
      }

      // Create new groups now.
      if (from <= to) {
        this.#log(`Creating groups from index ${from} to ${to}...`);

        const { groupStateByGroupIndex, failures } =
          await this.#buildGroupStateForRange(from, to, providers);

        // Check for provider failures — always treated as hard errors.
        if (failures.length) {
          throw new Error(
            failures.reduce(
              (message, failure) => `${message}\n- ${failure}`,
              'Unable to create some accounts. Providers threw the following errors:',
            ),
          );
        }

        // Create or update groups from the collected state.
        for (let groupIndex = from; groupIndex <= to; groupIndex++) {
          const groupState = groupStateByGroupIndex.get(groupIndex);

          if (groupState) {
            const group = this.#createOrUpdateMultichainAccountGroup(
              groupIndex,
              groupState,
            );

            groups.push(group);
          } else {
            this.#log(
              `${WARNING_PREFIX} Failed to create new group for group index: ${groupIndex} because no accounts were created for it`,
            );
          }
        }
      }

      return groups;
    });
  }

  /**
   * Align accounts for a range of group indices (non-locking).
   *
   * Calls all providers in parallel via the batch API. Provider failures are
   * logged as warnings (best-effort); no error is thrown.
   *
   * @param range - The range of group indices to align.
   * @param range.from - Starting group index (inclusive).
   * @param range.to - Ending group index (inclusive).
   * @param providers - The providers to align accounts for.
   * @param options - Options.
   * @param options.trace - Trace options.
   * @param options.trace.data - Optional trace data.
   */
  async #alignAccountsForRange(
    { from, to }: Required<GroupIndexRange>,
    providers: Bip44AccountProvider<Account>[],
    options: { trace?: { data?: TraceRequest['data'] } } = {},
  ): Promise<void> {
    await this.#trace(
      {
        name: TraceName.WalletAlignment,
        data: {
          from,
          to,
          ...toProviderDataTraces(providers),
          ...options.trace?.data,
        },
      },
      async () => {
        const { groupStateByGroupIndex, failures } =
          await this.#buildGroupStateForRange(from, to, providers);

        if (failures.length) {
          const error = failures.reduce(
            (message, failure) => `${message}\n- ${failure}`,
            'Unable to align some accounts. Providers threw the following errors:',
          );
          console.warn(error);
          this.#log(`${WARNING_PREFIX} ${error}`);
        }

        for (let groupIndex = from; groupIndex <= to; groupIndex++) {
          const groupState = groupStateByGroupIndex.get(groupIndex);
          if (groupState) {
            this.#createOrUpdateMultichainAccountGroup(groupIndex, groupState);
          }
        }
      },
    );
  }

  /**
   * Gets multichain account for a given ID.
   * The default group ID will default to the multichain account with index 0.
   *
   * @param id - Account group ID.
   * @returns Account group.
   */
  getAccountGroup(
    id: AccountGroupId,
  ): MultichainAccountGroup<Account> | undefined {
    // We consider the "default case" to be mapped to index 0.
    if (id === toDefaultAccountGroupId(this.id)) {
      return this.#accountGroups.get(0);
    }

    // If it is not a valid ID, we cannot extract the group index
    // from it, so we fail fast.
    if (!isMultichainAccountGroupId(id)) {
      return undefined;
    }

    const groupIndex = getGroupIndexFromMultichainAccountGroupId(id);
    return this.#accountGroups.get(groupIndex);
  }

  /**
   * Gets all multichain accounts. Similar to {@link MultichainAccountWallet.getMultichainAccountGroups}.
   *
   * @returns The multichain accounts.
   */
  getAccountGroups(): MultichainAccountGroup<Account>[] {
    return this.getMultichainAccountGroups();
  }

  /**
   * Gets multichain account group for a given index.
   *
   * @param groupIndex - Multichain account index.
   * @returns The multichain account associated with the given index.
   */
  getMultichainAccountGroup(
    groupIndex: number,
  ): MultichainAccountGroup<Account> | undefined {
    return this.#accountGroups.get(groupIndex);
  }

  /**
   * Gets all multichain account groups.
   *
   * @returns The multichain accounts.
   */
  getMultichainAccountGroups(): MultichainAccountGroup<Account>[] {
    return Array.from(this.#accountGroups.values()); // TODO: Prevent copy here.
  }

  /**
   * Gets next group index for this wallet.
   *
   * @returns The next group index of this wallet.
   */
  getNextGroupIndex(): number {
    // We do not check for gaps.
    return (
      Math.max(
        -1, // So it will default to 0 if no groups.
        ...this.#accountGroups.keys(),
      ) + 1
    );
  }

  /**
   * Creates a multichain account group for a given group index.
   *
   * NOTE: This operation WILL lock the wallet's mutex.
   *
   * @param groupIndex - The group index to use.
   * @param options - Options to configure the account creation.
   * @param options.waitForAllProvidersToFinishCreatingAccounts - Whether to wait for all
   * account providers to finish creating their accounts before returning. If `false`, only
   * the EVM provider is used and non-EVM account creation is deferred via
   * {@link MultichainAccountWallet.alignAccountsOf}. Defaults to `false`.
   * @throws If groupIndex is greater than the next available group index.
   * @throws If any account provider fails to create accounts.
   * @returns The multichain account group for this group index.
   */
  async createMultichainAccountGroup(
    groupIndex: number,
    options: {
      waitForAllProvidersToFinishCreatingAccounts?: boolean;
    } = {},
  ): Promise<MultichainAccountGroup<Account>> {
    // Use this to avoid having it as `boolean | undefined`.
    const waitForAllProvidersToFinishCreatingAccounts =
      options.waitForAllProvidersToFinishCreatingAccounts ?? false;

    return await this.#trace(
      {
        name: TraceName.WalletCreateMultichainAccountGroup,
        data: {
          groupIndex,
          waitForAllProvidersToFinishCreatingAccounts,
        },
      },
      async () => {
        assertGroupIndexIsValid(groupIndex, this.getNextGroupIndex());

        // If the group already exists, return it.
        const existingGroup = this.getMultichainAccountGroup(groupIndex);
        if (existingGroup) {
          this.#log(
            `Trying to re-create existing group: [${existingGroup.id}] (idempotent)`,
          );
          return existingGroup;
        }

        // Create a single group with a range of 1 (so we can reuse the batch creation logic) for the
        // given group index.
        const groups = await this.#createMultichainAccountGroups(
          { from: groupIndex, to: groupIndex },
          options,
        );

        const group = groups[0];
        assert(group, `Expected group at index ${groupIndex} to exist`);
        return group;
      },
    );
  }

  /**
   * Creates multiple multichain account groups up to maxGroupIndex.
   *
   * NOTE: This operation WILL lock the wallet's mutex.
   *
   * @param range - The range of group indices to create.
   * @param range.from - Starting group index to create (inclusive) (defaults to 0).
   * @param range.to - Maximum group index to create (inclusive).
   * @param options - Options to configure the account creation.
   * @param options.waitForAllProvidersToFinishCreatingAccounts - Whether to wait for all
   * account providers to finish creating their accounts before returning. If `false`, only
   * the EVM provider is used and non-EVM account creation is deferred via
   * {@link MultichainAccountWallet.alignAccounts}. Defaults to false.
   * @throws If range is invalid (e.g. from is greater than to, from or to is negative, etc.).
   * @returns Array of created multichain account groups.
   */
  async createMultichainAccountGroups(
    { from = 0, to }: GroupIndexRange,
    options: {
      waitForAllProvidersToFinishCreatingAccounts?: boolean;
    } = {},
  ): Promise<MultichainAccountGroup<Account>[]> {
    // Use this to avoid having it as `boolean | undefined`.
    const waitForAllProvidersToFinishCreatingAccounts =
      options.waitForAllProvidersToFinishCreatingAccounts ?? false;

    return await this.#trace(
      {
        name: TraceName.WalletCreateMultichainAccountGroups,
        data: {
          from,
          to,
          waitForAllProvidersToFinishCreatingAccounts,
        },
      },
      async () =>
        await this.#createMultichainAccountGroups({ from, to }, options),
    );
  }

  /**
   * Creates multiple multichain account groups up to maxGroupIndex.
   *
   * NOTE: This operation WILL lock the wallet's mutex.
   *
   * @param range - The range of group indices to create.
   * @param range.from - Starting group index to create (inclusive).
   * @param range.to - Maximum group index to create (inclusive).
   * @param options - Options to configure the account creation.
   * @param options.waitForAllProvidersToFinishCreatingAccounts - Whether to wait for all
   * account providers to finish creating their accounts before returning. If `false`, only
   * the EVM provider is used and non-EVM account creation is deferred via
   * {@link MultichainAccountWallet.alignAccounts}. Defaults to false.
   * @throws If range is invalid (e.g. from is greater than to, from or to is negative, etc.).
   * @returns Array of created multichain account groups.
   */
  async #createMultichainAccountGroups(
    { from, to }: Required<GroupIndexRange>,
    options: {
      waitForAllProvidersToFinishCreatingAccounts?: boolean;
    },
  ): Promise<MultichainAccountGroup<Account>[]> {
    assertGroupIndexRangeIsValid({ from, to });
    assertGroupIndexIsValid(from, this.getNextGroupIndex());

    const waitForAllProvidersToFinishCreatingAccounts =
      options.waitForAllProvidersToFinishCreatingAccounts ?? false;

    const [evmProvider, ...otherProviders] = this.#getProviders();
    const providers = waitForAllProvidersToFinishCreatingAccounts
      ? this.#providers
      : [evmProvider];

    const groups = await this.#createMultichainAccountGroupsRange(
      { from, to },
      providers,
    );

    // We need to run a post-alignment since non-EVM accounts have not
    // been created yet.
    if (!waitForAllProvidersToFinishCreatingAccounts) {
      const alignOtherAccounts = async (): Promise<void> => {
        this.#log(`Aligning accounts... (post)`);

        await this.#withLock('in-progress:alignment', async () => {
          await this.#alignAccountsForRange({ from, to }, otherProviders, {
            trace: {
              data: {
                post: true, // Tag to identify post-alignment traces in analytics.
              },
            },
          });
        });

        this.#log('Aligned accounts! (post)');
      };

      // eslint-disable-next-line no-void
      void alignOtherAccounts().catch((error) => {
        const errorMessage = `Unable to align non-EVM accounts from group index ${from} to ${to}`;
        this.#log(
          `${ERROR_PREFIX} ${errorMessage}: ${toErrorMessage(error)} (post)`,
        );
        console.error(errorMessage, error);
      });
    }

    return groups;
  }

  /**
   * Creates the next multichain account group.
   *
   * @throws If any of the account providers fails to create their accounts.
   * @returns The multichain account group for the next group index available.
   */
  async createNextMultichainAccountGroup(): Promise<
    MultichainAccountGroup<Account>
  > {
    return this.createMultichainAccountGroup(this.getNextGroupIndex(), {
      waitForAllProvidersToFinishCreatingAccounts: true,
    });
  }

  /**
   * Align all accounts from each existing multichain account groups.
   *
   * NOTE: This operation WILL lock the wallet's mutex.
   */
  async alignAccounts(): Promise<void> {
    const nextGroupIndex = this.getNextGroupIndex();

    if (nextGroupIndex > 0) {
      this.#log('Aligning accounts...');

      const from = 0;
      const to = nextGroupIndex - 1;

      await this.#withLock(
        'in-progress:alignment',
        async () =>
          await this.#alignAccountsForRange({ from, to }, this.#providers),
      );

      this.#log('Aligned!');
    }
  }

  /**
   * Align a specific multichain account group.
   *
   * NOTE: This operation WILL lock the wallet's mutex.
   *
   * @param groupIndex - The group index to align.
   */
  async alignAccountsOf(groupIndex: number): Promise<void> {
    const group = this.getMultichainAccountGroup(groupIndex);

    if (group) {
      this.#log(`Aligning accounts for group "${group.id}"...`);

      await this.#withLock(
        'in-progress:alignment',
        async () =>
          await this.#alignAccountsForRange(
            { from: groupIndex, to: groupIndex },
            this.#providers,
            { trace: { data: { groupIndex } } },
          ),
      );

      this.#log(`Aligned accounts for group "${group.id}"!`);
    }
  }

  /**
   * Discover and create accounts for all providers.
   *
   * NOTE: This operation WILL lock the wallet's mutex.
   *
   * @returns The discovered accounts for each provider.
   */
  async discoverAccounts(): Promise<Account[]> {
    return this.#withLock('in-progress:discovery', async () => {
      // Start with the next available group index (so we can resume the discovery
      // from there).
      let maxGroupIndex = this.getNextGroupIndex();
      const discoveredGroupsState: DiscoveredGroupsState = {};

      const addDiscoveryResultToState = (
        result: Account[],
        providerName: string,
        groupIndex: number,
      ) => {
        const accountIds = result.map((account) => account.id);
        discoveredGroupsState[groupIndex] ??= {};
        discoveredGroupsState[groupIndex][providerName] = accountIds;
      };

      // One serialized loop per provider; all run concurrently
      const runProviderDiscovery = async (
        context: AccountProviderDiscoveryContext<Account>,
      ): Promise<void> => {
        const providerName = context.provider.getName();
        const message = (stepName: string, groupIndex: number) =>
          `[${providerName}] Discovery ${stepName} for group index: ${groupIndex}`;

        while (!context.stopped) {
          // Fast‑forward to current high‑water mark
          const targetGroupIndex = Math.max(context.groupIndex, maxGroupIndex);

          log(message('started', targetGroupIndex));

          let accounts: Account[] = [];
          try {
            accounts = await context.provider.discoverAccounts({
              entropySource: this.#entropySource,
              groupIndex: targetGroupIndex,
            });
          } catch (error) {
            context.stopped = true;

            log(
              message(
                `failed (with: "${toErrorMessage(error)}")`,
                targetGroupIndex,
              ),
            );

            reportError(
              this.#messenger,
              `Unable to discover accounts with provider "${providerName}"`,
              error,
              {
                provider: providerName,
                groupIndex: targetGroupIndex,
              },
            );
            break;
          }

          if (!accounts.length) {
            log(
              message('stopped (no accounts got discovered)', targetGroupIndex),
            );
            context.stopped = true;
            break;
          }

          log(message('**succeeded**', targetGroupIndex));

          context.accounts = context.accounts.concat(accounts);

          addDiscoveryResultToState(accounts, providerName, targetGroupIndex);

          const nextGroupIndex = targetGroupIndex + 1;
          context.groupIndex = nextGroupIndex;

          if (nextGroupIndex > maxGroupIndex) {
            maxGroupIndex = nextGroupIndex;
          }
        }
      };

      const providerContexts: AccountProviderDiscoveryContext<Account>[] =
        this.#providers.map((provider) => ({
          provider,
          stopped: false,
          groupIndex: maxGroupIndex,
          accounts: [],
        }));

      // Start discovery for each providers.
      await Promise.all(providerContexts.map(runProviderDiscovery));

      // Create discovered groups
      for (const [groupIndexString, groupState] of Object.entries(
        discoveredGroupsState,
      )) {
        const groupIndex = Number(groupIndexString);
        const group = new MultichainAccountGroup({
          wallet: this,
          providers: this.#providers,
          groupIndex,
          messenger: this.#messenger,
        });
        group.init(groupState);
        this.#accountGroups.set(groupIndex, group);
      }

      // Align missing accounts from group. This is required to create missing account from non-discovered
      // indexes for some providers.
      const nextGroupIndex = this.getNextGroupIndex();
      if (nextGroupIndex > 0) {
        await this.#alignAccountsForRange(
          { from: 0, to: nextGroupIndex - 1 },
          this.#providers,
          {
            trace: {
              data: {
                discovery: true, // Tag to identify discovery-alignment traces in analytics.
              },
            },
          },
        );
      }

      return providerContexts.flatMap((context) => context.accounts);
    });
  }
}
