/* eslint-disable jsdoc/tag-lines */
// Auto-generated from OpenAPI spec - naming follows API schema conventions
/* eslint-disable @typescript-eslint/naming-convention */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 * Script: `npx openapi-typescript <PATH TO NOTIFICATION API SPEC> -o ./schema.d.ts`
 */

export type paths = {
  '/api/v3/notifications': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** List both platform and on-chain notifications for a certain user/address(es) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['NotificationInputV3'];
        };
      };
      responses: {
        /** @description Notifications listed successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['NotificationOutputV3'];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v3/notifications/mark-as-read': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Mark notifications as read */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            ids?: string[];
          };
        };
      };
      responses: {
        /** @description Successfully marked notifications as read */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
};
export type webhooks = Record<string, never>;
export type components = {
  schemas: {
    NotificationInputV3: {
      /** @example en-US */
      locale: string;
      addresses: string[];
      platform: 'extension' | 'mobile';
    };
    NotificationOutputV3: (
      | components['schemas']['PlatformNotification']
      | components['schemas']['OnChainNotification']
    )[];
    PlatformNotification: {
      /**
       * Format: uuid
       * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
       */
      id: string;
      /** @enum {string} */
      notification_type: 'platform';
      /** @example false */
      unread: boolean;
      template: components['schemas']['LocalizedNotification'];
      /**
       * Format: date-time
       * @example 2025-10-09T09:45:34.202Z
       */
      created_at: string;
    };
    LocalizedNotification: {
      image_url: string;
      cta?: components['schemas']['LocalizedNotificationCTA'];
      title: string;
      body: string;
    };
    LocalizedNotificationCTA: {
      content: string;
      link: string;
    };
    OnChainNotification: {
      /**
       * Format: uuid
       * @example 3fa85f64-5717-4562-b3fc-2c963f66afa6
       */
      id: string;
      /** @enum {string} */
      notification_type: 'on-chain';
      /** @example false */
      unread: boolean;
      /**
       * Format: date-time
       * @example 2025-10-09T09:45:34.202Z
       */
      created_at: string;
      payload: components['schemas']['OnChainPayload'];
    };
    OnChainPayload: {
      /** @example 1 */
      chain_id: number;
      /** @example 17485840 */
      block_number: number;
      block_timestamp: string;
      /** @example 0x881D40237659C251811CEC9c364ef91dC08D300C */
      tx_hash: string;
      address: string;
      network?: components['schemas']['NetworkMetadata'];
      data?:
        | components['schemas']['Data_MetamaskSwapCompleted']
        | components['schemas']['Data_LidoStakeReadyToBeWithdrawn']
        | components['schemas']['Data_LidoStakeCompleted']
        | components['schemas']['Data_LidoWithdrawalRequested']
        | components['schemas']['Data_LidoWithdrawalCompleted']
        | components['schemas']['Data_RocketPoolStakeCompleted']
        | components['schemas']['Data_RocketPoolUnstakeCompleted']
        | components['schemas']['Data_ETHSent']
        | components['schemas']['Data_ETHReceived']
        | components['schemas']['Data_ERC20Sent']
        | components['schemas']['Data_ERC20Received']
        | components['schemas']['Data_ERC721Sent']
        | components['schemas']['Data_ERC721Received']
        | components['schemas']['Data_ERC1155Sent']
        | components['schemas']['Data_ERC1155Received'];
    };
    Data_MetamaskSwapCompleted: {
      /** @enum {string} */
      kind: 'metamask_swap_completed';
      network_fee: components['schemas']['NetworkFee'];
      /** Format: decimal */
      rate: string;
      token_in: components['schemas']['Token'];
      token_out: components['schemas']['Token'];
    };
    Data_LidoStakeCompleted: {
      /** @enum {string} */
      kind: 'lido_stake_completed';
      network_fee: components['schemas']['NetworkFee'];
      stake_in: components['schemas']['Stake'];
      stake_out: components['schemas']['Stake'];
    };
    Data_LidoWithdrawalRequested: {
      /** @enum {string} */
      kind: 'lido_withdrawal_requested';
      network_fee: components['schemas']['NetworkFee'];
      stake_in: components['schemas']['Stake'];
      stake_out: components['schemas']['Stake'];
    };
    Data_LidoStakeReadyToBeWithdrawn: {
      /** @enum {string} */
      kind: 'lido_stake_ready_to_be_withdrawn';
      /** Format: decimal */
      request_id: string;
      staked_eth: components['schemas']['Stake'];
    };
    Data_LidoWithdrawalCompleted: {
      /** @enum {string} */
      kind: 'lido_withdrawal_completed';
      network_fee: components['schemas']['NetworkFee'];
      stake_in: components['schemas']['Stake'];
      stake_out: components['schemas']['Stake'];
    };
    Data_RocketPoolStakeCompleted: {
      /** @enum {string} */
      kind: 'rocketpool_stake_completed';
      network_fee: components['schemas']['NetworkFee'];
      stake_in: components['schemas']['Stake'];
      stake_out: components['schemas']['Stake'];
    };
    Data_RocketPoolUnstakeCompleted: {
      /** @enum {string} */
      kind: 'rocketpool_unstake_completed';
      network_fee: components['schemas']['NetworkFee'];
      stake_in: components['schemas']['Stake'];
      stake_out: components['schemas']['Stake'];
    };
    Data_ETHSent: {
      /** @enum {string} */
      kind: 'eth_sent';
      network_fee: components['schemas']['NetworkFee'];
      /** Format: address */
      from: string;
      /** Format: address */
      to: string;
      amount: {
        /** Format: decimal */
        usd: string;
        /** Format: decimal */
        eth: string;
      };
    };
    Data_ETHReceived: {
      /** @enum {string} */
      kind: 'eth_received';
      network_fee: components['schemas']['NetworkFee'];
      /** Format: address */
      from: string;
      /** Format: address */
      to: string;
      amount: {
        /** Format: decimal */
        usd: string;
        /** Format: decimal */
        eth: string;
      };
    };
    Data_ERC20Sent: {
      /** @enum {string} */
      kind: 'erc20_sent';
      network_fee: components['schemas']['NetworkFee'];
      /** Format: address */
      from: string;
      /** Format: address */
      to: string;
      token: components['schemas']['Token'];
    };
    Data_ERC20Received: {
      /** @enum {string} */
      kind: 'erc20_received';
      network_fee: components['schemas']['NetworkFee'];
      /** Format: address */
      from: string;
      /** Format: address */
      to: string;
      token: components['schemas']['Token'];
    };
    Data_ERC721Sent: {
      /** @enum {string} */
      kind: 'erc721_sent';
      network_fee: components['schemas']['NetworkFee'];
      /** Format: address */
      from: string;
      /** Format: address */
      to: string;
      nft: components['schemas']['NFT'];
    };
    Data_ERC721Received: {
      /** @enum {string} */
      kind: 'erc721_received';
      network_fee: components['schemas']['NetworkFee'];
      /** Format: address */
      from: string;
      /** Format: address */
      to: string;
      nft: components['schemas']['NFT'];
    };
    Data_ERC1155Sent: {
      /** @enum {string} */
      kind: 'erc1155_sent';
      network_fee: components['schemas']['NetworkFee'];
      /** Format: address */
      from: string;
      /** Format: address */
      to: string;
      nft?: components['schemas']['NFT'];
    };
    Data_ERC1155Received: {
      /** @enum {string} */
      kind: 'erc1155_received';
      network_fee: components['schemas']['NetworkFee'];
      /** Format: address */
      from: string;
      /** Format: address */
      to: string;
      nft?: components['schemas']['NFT'];
    };
    NetworkFee: {
      /** Format: decimal */
      gas_price: string;
      /** Format: decimal */
      native_token_price_in_usd: string;
    };
    Token: {
      /** Format: address */
      address: string;
      symbol: string;
      name: string;
      /** Format: decimal */
      amount: string;
      /** Format: int32 */
      decimals: string;
      /** Format: uri */
      image: string;
      /** Format: decimal */
      usd: string;
    };
    NFT: {
      name: string;
      token_id: string;
      /** Format: uri */
      image: string;
      collection: {
        /** Format: address */
        address: string;
        name: string;
        symbol: string;
        /** Format: uri */
        image: string;
      };
    };
    Stake: {
      /** Format: address */
      address: string;
      symbol: string;
      name: string;
      /** Format: decimal */
      amount: string;
      /** Format: int32 */
      decimals: string;
      /** Format: uri */
      image: string;
      /** Format: decimal */
      usd: string;
    };
    BlockExplorer: {
      /**
       * Format: uri
       * @example https://etherscan.io
       */
      url: string;
      /** @example Etherscan */
      name: string;
    };
    NetworkMetadata: {
      /**
       * @description Human-readable network name
       * @example Ethereum
       */
      name: string;
      /**
       * @description Native token symbol
       * @example ETH
       */
      native_symbol: string;
      block_explorer: components['schemas']['BlockExplorer'];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
};
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
