version: 2.1

workflows:
  build-test:
    jobs:
      - prep-deps-build
      - test-lint:
          requires:
            - prep-deps-build
      - test-unit:
          requires:
            - prep-deps-build
      - all-tests-pass:
          requires:
            - test-lint
            - test-unit

jobs:
  prep-deps-build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            .circleci/scripts/deps-install.sh
      - run:
          name: Collect yarn install HAR logs
          command: |
            .circleci/scripts/collect-har-artifact.sh
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
          - node_modules
          - build-artifacts
          - dist

  test-lint:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn lint

  test-unit:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Unit tests
          command: yarn test:nobuild

  all-tests-pass:
    docker:
      - image: circleci/node:12
    steps:
      - run:
          name: All tests passed
          command: echo 'Great success'
