/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { OnRampService } from './OnRampService';

/**
 * Makes a request to the API in order to retrieve the user's geolocation
 * based on their IP address.
 *
 * @returns The user's country/region code (e.g., "US-UT" for Utah, USA).
 */
export type OnRampServiceGetGeolocationAction = {
  type: `OnRampService:getGeolocation`;
  handler: OnRampService['getGeolocation'];
};

/**
 * Union of all OnRampService action types.
 */
export type OnRampServiceMethodActions = OnRampServiceGetGeolocationAction;
