/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { OnRampService } from './OnRampService';

/**
 * Makes a request to the API in order to retrieve the list of supported
 * countries/regions for ramp services.
 *
 * @param abortController - Optional AbortController for request cancellation.
 * @returns An array of supported countries/regions.
 */
export type OnRampServiceGetCountriesAction = {
  type: `OnRampService:getCountries`;
  handler: OnRampService['getCountries'];
};

/**
 * Union of all OnRampService action types.
 */
export type OnRampServiceMethodActions = OnRampServiceGetCountriesAction;
