/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { RampsController } from './RampsController';

/**
 * Executes a request with caching, deduplication, and at most one in-flight
 * request per resource type.
 *
 * 1. **Same cache key in flight** – If a request with this cache key is
 * already pending, returns that promise (deduplication; no second request).
 *
 * 2. **Cache hit** – If valid, non-expired data exists in state.requests for
 * this key and forceRefresh is not set, returns that data without fetching.
 *
 * 3. **New request** – Creates an AbortController and fires the fetcher.
 * If options.resourceType is set, tags the pending request with that
 * resource type (so #abortDependentRequests can cancel it on region
 * change or cleanup) and ref-counts resource-level loading state.
 * On success or error, updates request state and resource error;
 * in finally, clears resource loading only if this request was not
 * aborted.
 *
 * @param cacheKey - Unique identifier for this request (e.g. from createCacheKey).
 * @param fetcher - Async function that performs the fetch. Receives an AbortSignal
 * that is aborted when this request is superseded by another for the same resource.
 * @param options - Optional forceRefresh, ttl, and resourceType for loading/error state.
 * @returns The result of the request (from cache, joined promise, or fetcher).
 */
export type RampsControllerExecuteRequestAction = {
  type: `RampsController:executeRequest`;
  handler: RampsController['executeRequest'];
};

/**
 * Aborts a pending request if one exists.
 *
 * @param cacheKey - The cache key of the request to abort.
 * @returns True if a request was aborted.
 */
export type RampsControllerAbortRequestAction = {
  type: `RampsController:abortRequest`;
  handler: RampsController['abortRequest'];
};

/**
 * Gets the state of a specific cached request.
 *
 * @param cacheKey - The cache key to look up.
 * @returns The request state, or undefined if not cached.
 */
export type RampsControllerGetRequestStateAction = {
  type: `RampsController:getRequestState`;
  handler: RampsController['getRequestState'];
};

/**
 * Sets the user's region manually (without fetching geolocation).
 * This allows users to override the detected region.
 *
 * @param region - The region code to set (e.g., "US-CA").
 * @param options - Options for cache behavior.
 * @returns The user region object.
 */
export type RampsControllerSetUserRegionAction = {
  type: `RampsController:setUserRegion`;
  handler: RampsController['setUserRegion'];
};

/**
 * Sets the user's selected provider by ID, or clears the selection.
 * Looks up the provider from the current providers in state and automatically
 * fetches payment methods for that provider.
 *
 * @param providerId - The provider ID (e.g., "/providers/moonpay"), or null to clear.
 * @throws If region is not set, providers are not loaded, or provider is not found.
 */
export type RampsControllerSetSelectedProviderAction = {
  type: `RampsController:setSelectedProvider`;
  handler: RampsController['setSelectedProvider'];
};

/**
 * Initializes the controller by fetching the user's region from geolocation.
 * This should be called once at app startup to set up the initial region.
 *
 * Idempotent: subsequent calls return the same promise unless forceRefresh is set.
 * Skips getCountries when countries are already loaded; skips geolocation when
 * userRegion already exists.
 *
 * @param options - Options for cache behavior. forceRefresh bypasses idempotency and re-runs the full flow.
 * @returns Promise that resolves when initialization is complete.
 */
export type RampsControllerInitAction = {
  type: `RampsController:init`;
  handler: RampsController['init'];
};

/**
 * Fetches the list of supported countries.
 * The API returns countries with support information for both buy and sell actions.
 * The countries are saved in the controller state once fetched.
 *
 * @param options - Options for cache behavior.
 * @returns An array of countries.
 */
export type RampsControllerGetCountriesAction = {
  type: `RampsController:getCountries`;
  handler: RampsController['getCountries'];
};

/**
 * Fetches the list of available tokens for a given region and action.
 * The tokens are saved in the controller state once fetched.
 *
 * @param region - The region code (e.g., "us", "fr", "us-ny"). If not provided, uses the user's region from controller state.
 * @param action - The ramp action type ('buy' or 'sell').
 * @param options - Options for cache behavior and query filters.
 * @param options.provider - Provider ID(s) to filter by.
 * @returns The tokens response containing topTokens and allTokens.
 */
export type RampsControllerGetTokensAction = {
  type: `RampsController:getTokens`;
  handler: RampsController['getTokens'];
};

/**
 * Sets the user's selected token by asset ID.
 * Looks up the token from the current tokens in state and automatically
 * fetches payment methods for that token.
 *
 * @param assetId - The asset identifier in CAIP-19 format (e.g., "eip155:1/erc20:0x..."), or undefined to clear.
 * @throws If region is not set, tokens are not loaded, or token is not found.
 */
export type RampsControllerSetSelectedTokenAction = {
  type: `RampsController:setSelectedToken`;
  handler: RampsController['setSelectedToken'];
};

/**
 * Fetches the list of providers for a given region.
 * The providers are saved in the controller state once fetched.
 *
 * @param region - The region code (e.g., "us", "fr", "us-ny"). If not provided, uses the user's region from controller state.
 * @param options - Options for cache behavior and query filters.
 * @param options.provider - Provider ID(s) to filter by.
 * @param options.crypto - Crypto currency ID(s) to filter by.
 * @param options.fiat - Fiat currency ID(s) to filter by.
 * @param options.payments - Payment method ID(s) to filter by.
 * @returns The providers response containing providers array.
 */
export type RampsControllerGetProvidersAction = {
  type: `RampsController:getProviders`;
  handler: RampsController['getProviders'];
};

/**
 * Fetches the list of payment methods for a given context.
 * The payment methods are saved in the controller state once fetched.
 *
 * @param region - User's region code (e.g. "fr", "us-ny").
 * @param options - Query parameters for filtering payment methods.
 * @param options.fiat - Fiat currency code (e.g., "usd"). If not provided, uses the user's region currency.
 * @param options.assetId - CAIP-19 cryptocurrency identifier.
 * @param options.provider - Provider ID path.
 * @returns The payment methods response containing payments array.
 */
export type RampsControllerGetPaymentMethodsAction = {
  type: `RampsController:getPaymentMethods`;
  handler: RampsController['getPaymentMethods'];
};

/**
 * Sets the user's selected payment method by ID.
 * Looks up the payment method from the current payment methods in state.
 *
 * @param paymentMethodId - The payment method ID (e.g., "/payments/debit-credit-card"), or null to clear.
 * @throws If payment methods are not loaded or payment method is not found.
 */
export type RampsControllerSetSelectedPaymentMethodAction = {
  type: `RampsController:setSelectedPaymentMethod`;
  handler: RampsController['setSelectedPaymentMethod'];
};

/**
 * Fetches quotes from all providers for a given set of parameters.
 * Uses the controller's request cache; callers manage the response in local state.
 *
 * @param options - The parameters for fetching quotes.
 * @param options.region - User's region code. If not provided, uses userRegion from state.
 * @param options.fiat - Fiat currency code. If not provided, uses userRegion currency.
 * @param options.assetId - CAIP-19 cryptocurrency identifier.
 * @param options.amount - The amount (in fiat for buy, crypto for sell).
 * @param options.walletAddress - The destination wallet address.
 * @param options.paymentMethods - Array of payment method IDs. If not provided, uses paymentMethods from state.
 * @param options.providers - Optional provider IDs to filter quotes.
 * @param options.redirectUrl - Optional redirect URL after order completion.
 * @param options.action - The ramp action type. Defaults to 'buy'.
 * @param options.forceRefresh - Whether to bypass cache.
 * @param options.ttl - Custom TTL for this request.
 * @returns The quotes response containing success, sorted, error, and customActions.
 */
export type RampsControllerGetQuotesAction = {
  type: `RampsController:getQuotes`;
  handler: RampsController['getQuotes'];
};

/**
 * Adds or updates a V2 order in controller state.
 * If an order with the same providerOrderId already exists, the incoming
 * fields are merged on top of the existing order so that fields not present
 * in the update (e.g. paymentDetails from the Transak API) are preserved.
 *
 * @param order - The RampsOrder to add or update.
 */
export type RampsControllerAddOrderAction = {
  type: `RampsController:addOrder`;
  handler: RampsController['addOrder'];
};

/**
 * Removes a V2 order from controller state by providerOrderId.
 *
 * @param providerOrderId - The provider order ID to remove.
 */
export type RampsControllerRemoveOrderAction = {
  type: `RampsController:removeOrder`;
  handler: RampsController['removeOrder'];
};

/**
 * Starts polling all pending V2 orders at a fixed interval.
 * Each poll cycle iterates orders with non-terminal statuses,
 * respects pollingSecondsMinimum and backoff from error count.
 */
export type RampsControllerStartOrderPollingAction = {
  type: `RampsController:startOrderPolling`;
  handler: RampsController['startOrderPolling'];
};

/**
 * Stops order polling and clears the interval.
 */
export type RampsControllerStopOrderPollingAction = {
  type: `RampsController:stopOrderPolling`;
  handler: RampsController['stopOrderPolling'];
};

/**
 * Fetches the widget data from a quote for redirect providers.
 * Makes a request to the buyURL endpoint via the RampsService to get the
 * actual provider widget URL and optional order ID for polling.
 *
 * @param quote - The quote to fetch the widget URL from.
 * @returns Promise resolving to the full BuyWidget (url, browser, orderId), or null if not available (missing buyURL or empty url in response).
 * @throws Rethrows errors from the RampsService (e.g. HttpError, network failures) so clients can react to fetch failures.
 */
export type RampsControllerGetBuyWidgetDataAction = {
  type: `RampsController:getBuyWidgetData`;
  handler: RampsController['getBuyWidgetData'];
};

/**
 * Registers an order ID for polling until the order is created or resolved.
 * Adds a minimal stub order to controller state; the existing order polling
 * will fetch the full order when the provider has created it.
 *
 * @param params - Object containing order identifiers and wallet info.
 * @param params.orderId - Full order ID (e.g. "/providers/paypal/orders/abc123") or order code.
 * @param params.providerCode - Provider code (e.g. "paypal", "transak"), with or without /providers/ prefix.
 * @param params.walletAddress - Wallet address for the order.
 * @param params.chainId - Optional chain ID for the order.
 */
export type RampsControllerAddPrecreatedOrderAction = {
  type: `RampsController:addPrecreatedOrder`;
  handler: RampsController['addPrecreatedOrder'];
};

/**
 * Fetches an order from the unified V2 API endpoint.
 * Returns a normalized RampsOrder for all provider types (aggregator and native).
 *
 * @param providerCode - The provider code (e.g., "transak", "transak-native", "moonpay").
 * @param orderCode - The order identifier.
 * @param wallet - The wallet address associated with the order.
 * @returns The unified order data.
 */
export type RampsControllerGetOrderAction = {
  type: `RampsController:getOrder`;
  handler: RampsController['getOrder'];
};

/**
 * Extracts an order from a provider callback URL.
 * Sends the callback URL to the V2 backend for provider-specific parsing,
 * then fetches the full order. This is the V2 equivalent of the aggregator
 * SDK's `getOrderFromCallback`.
 *
 * @param providerCode - The provider code (e.g., "transak", "moonpay").
 * @param callbackUrl - The full callback URL the provider redirected to.
 * @param wallet - The wallet address associated with the order.
 * @returns The unified order data.
 */
export type RampsControllerGetOrderFromCallbackAction = {
  type: `RampsController:getOrderFromCallback`;
  handler: RampsController['getOrderFromCallback'];
};

/**
 * Sets the Transak API key used for all Transak API requests.
 *
 * @param apiKey - The Transak API key.
 */
export type RampsControllerTransakSetApiKeyAction = {
  type: `RampsController:transakSetApiKey`;
  handler: RampsController['transakSetApiKey'];
};

/**
 * Sets the Transak access token and marks the user as authenticated.
 *
 * @param token - The access token received from Transak auth.
 */
export type RampsControllerTransakSetAccessTokenAction = {
  type: `RampsController:transakSetAccessToken`;
  handler: RampsController['transakSetAccessToken'];
};

/**
 * Clears the Transak access token and marks the user as unauthenticated.
 */
export type RampsControllerTransakClearAccessTokenAction = {
  type: `RampsController:transakClearAccessToken`;
  handler: RampsController['transakClearAccessToken'];
};

/**
 * Updates the Transak authentication flag in controller state.
 *
 * @param isAuthenticated - Whether the user is authenticated with Transak.
 */
export type RampsControllerTransakSetAuthenticatedAction = {
  type: `RampsController:transakSetAuthenticated`;
  handler: RampsController['transakSetAuthenticated'];
};

/**
 * Resets all Transak state back to defaults (unauthenticated, no data).
 */
export type RampsControllerTransakResetStateAction = {
  type: `RampsController:transakResetState`;
  handler: RampsController['transakResetState'];
};

/**
 * Sends a one-time password to the user's email for Transak authentication.
 *
 * @param email - The user's email address.
 * @returns The OTP response containing a state token for verification.
 */
export type RampsControllerTransakSendUserOtpAction = {
  type: `RampsController:transakSendUserOtp`;
  handler: RampsController['transakSendUserOtp'];
};

/**
 * Verifies a one-time password and authenticates the user with Transak.
 * Updates the controller's authentication state on success.
 *
 * @param email - The user's email address.
 * @param verificationCode - The OTP code entered by the user.
 * @param stateToken - The state token from the sendUserOtp response.
 * @returns The access token for subsequent authenticated requests.
 */
export type RampsControllerTransakVerifyUserOtpAction = {
  type: `RampsController:transakVerifyUserOtp`;
  handler: RampsController['transakVerifyUserOtp'];
};

/**
 * Logs the user out of Transak. Clears authentication state and user details
 * regardless of whether the API call succeeds or fails.
 *
 * @returns A message indicating the logout result.
 */
export type RampsControllerTransakLogoutAction = {
  type: `RampsController:transakLogout`;
  handler: RampsController['transakLogout'];
};

/**
 * Fetches the authenticated user's details from Transak.
 * Updates the userDetails resource state with loading/success/error states.
 *
 * @returns The user's profile and KYC details.
 */
export type RampsControllerTransakGetUserDetailsAction = {
  type: `RampsController:transakGetUserDetails`;
  handler: RampsController['transakGetUserDetails'];
};

/**
 * Fetches a buy quote from Transak for the given parameters.
 * Updates the buyQuote resource state with loading/success/error states.
 *
 * @param fiatCurrency - The fiat currency code (e.g., "USD").
 * @param cryptoCurrency - The cryptocurrency identifier.
 * @param network - The blockchain network identifier.
 * @param paymentMethod - The payment method identifier.
 * @param fiatAmount - The fiat amount as a string.
 * @returns The buy quote with pricing and fee details.
 */
export type RampsControllerTransakGetBuyQuoteAction = {
  type: `RampsController:transakGetBuyQuote`;
  handler: RampsController['transakGetBuyQuote'];
};

/**
 * Fetches the KYC requirement for a given quote.
 * Updates the kycRequirement resource state with loading/success/error states.
 *
 * @param quoteId - The quote ID to check KYC requirements for.
 * @returns The KYC requirement status and whether the user can place an order.
 */
export type RampsControllerTransakGetKycRequirementAction = {
  type: `RampsController:transakGetKycRequirement`;
  handler: RampsController['transakGetKycRequirement'];
};

/**
 * Fetches additional KYC requirements (e.g., ID proof, address proof) for a quote.
 *
 * @param quoteId - The quote ID to check additional requirements for.
 * @returns The list of additional forms required.
 */
export type RampsControllerTransakGetAdditionalRequirementsAction = {
  type: `RampsController:transakGetAdditionalRequirements`;
  handler: RampsController['transakGetAdditionalRequirements'];
};

/**
 * Creates a new order on Transak. If an existing order conflicts (HTTP 409),
 * active orders are cancelled and the creation is retried.
 *
 * @param quoteId - The quote ID to create an order from.
 * @param walletAddress - The destination wallet address.
 * @param paymentMethodId - The payment method to use.
 * @returns The created deposit order.
 */
export type RampsControllerTransakCreateOrderAction = {
  type: `RampsController:transakCreateOrder`;
  handler: RampsController['transakCreateOrder'];
};

/**
 * Fetches an existing order from Transak by order ID.
 *
 * @param orderId - The order ID (deposit format or raw Transak format).
 * @param wallet - The wallet address associated with the order.
 * @param paymentDetails - Optional payment details to attach to the order.
 * @returns The deposit order details.
 */
export type RampsControllerTransakGetOrderAction = {
  type: `RampsController:transakGetOrder`;
  handler: RampsController['transakGetOrder'];
};

/**
 * Fetches the user's spending limits for a given currency and payment method.
 *
 * @param fiatCurrency - The fiat currency code.
 * @param paymentMethod - The payment method identifier.
 * @param kycType - The KYC level type.
 * @returns The user's limits, spending, and remaining amounts.
 */
export type RampsControllerTransakGetUserLimitsAction = {
  type: `RampsController:transakGetUserLimits`;
  handler: RampsController['transakGetUserLimits'];
};

/**
 * Requests a one-time token (OTT) for the Transak payment widget.
 *
 * @returns The OTT response containing the token.
 */
export type RampsControllerTransakRequestOttAction = {
  type: `RampsController:transakRequestOtt`;
  handler: RampsController['transakRequestOtt'];
};

/**
 * Generates a URL for the Transak payment widget with pre-filled parameters.
 *
 * @param ottToken - The one-time token for widget authentication.
 * @param quote - The buy quote to pre-fill in the widget.
 * @param walletAddress - The destination wallet address.
 * @param extraParams - Optional additional URL parameters.
 * @returns The fully constructed widget URL string.
 */
export type RampsControllerTransakGeneratePaymentWidgetUrlAction = {
  type: `RampsController:transakGeneratePaymentWidgetUrl`;
  handler: RampsController['transakGeneratePaymentWidgetUrl'];
};

/**
 * Submits the user's purpose of usage form for KYC compliance.
 *
 * @param purpose - Array of purpose strings selected by the user.
 * @returns A promise that resolves when the form is submitted.
 */
export type RampsControllerTransakSubmitPurposeOfUsageFormAction = {
  type: `RampsController:transakSubmitPurposeOfUsageForm`;
  handler: RampsController['transakSubmitPurposeOfUsageForm'];
};

/**
 * Updates the user's personal or address details on Transak.
 *
 * @param data - The user data fields to update.
 * @returns The API response data.
 */
export type RampsControllerTransakPatchUserAction = {
  type: `RampsController:transakPatchUser`;
  handler: RampsController['transakPatchUser'];
};

/**
 * Submits the user's SSN for identity verification.
 *
 * @param ssn - The Social Security Number.
 * @param quoteId - The quote ID associated with the order requiring SSN.
 * @returns The API response data.
 */
export type RampsControllerTransakSubmitSsnDetailsAction = {
  type: `RampsController:transakSubmitSsnDetails`;
  handler: RampsController['transakSubmitSsnDetails'];
};

/**
 * Confirms payment for an order after the user has completed payment.
 *
 * @param orderId - The order ID to confirm payment for.
 * @param paymentMethodId - The payment method used.
 * @returns Whether the payment confirmation was successful.
 */
export type RampsControllerTransakConfirmPaymentAction = {
  type: `RampsController:transakConfirmPayment`;
  handler: RampsController['transakConfirmPayment'];
};

/**
 * Translates generic ramps identifiers to Transak-specific identifiers.
 *
 * @param request - The translation request with optional identifiers to translate.
 * @returns The translated Transak-specific identifiers.
 */
export type RampsControllerTransakGetTranslationAction = {
  type: `RampsController:transakGetTranslation`;
  handler: RampsController['transakGetTranslation'];
};

/**
 * Checks the status of an ID proof submission for KYC.
 *
 * @param workFlowRunId - The workflow run ID to check status for.
 * @returns The current ID proof status.
 */
export type RampsControllerTransakGetIdProofStatusAction = {
  type: `RampsController:transakGetIdProofStatus`;
  handler: RampsController['transakGetIdProofStatus'];
};

/**
 * Cancels a specific Transak order.
 *
 * @param depositOrderId - The deposit order ID to cancel.
 * @returns A promise that resolves when the order is cancelled.
 */
export type RampsControllerTransakCancelOrderAction = {
  type: `RampsController:transakCancelOrder`;
  handler: RampsController['transakCancelOrder'];
};

/**
 * Cancels all active Transak orders. Individual cancellation failures
 * are collected and returned rather than thrown.
 *
 * @returns An array of errors from any failed cancellations (empty if all succeeded).
 */
export type RampsControllerTransakCancelAllActiveOrdersAction = {
  type: `RampsController:transakCancelAllActiveOrders`;
  handler: RampsController['transakCancelAllActiveOrders'];
};

/**
 * Fetches all active Transak orders for the authenticated user.
 *
 * @returns The list of active orders.
 */
export type RampsControllerTransakGetActiveOrdersAction = {
  type: `RampsController:transakGetActiveOrders`;
  handler: RampsController['transakGetActiveOrders'];
};

/**
 * Union of all RampsController action types.
 */
export type RampsControllerMethodActions =
  | RampsControllerExecuteRequestAction
  | RampsControllerAbortRequestAction
  | RampsControllerGetRequestStateAction
  | RampsControllerSetUserRegionAction
  | RampsControllerSetSelectedProviderAction
  | RampsControllerInitAction
  | RampsControllerGetCountriesAction
  | RampsControllerGetTokensAction
  | RampsControllerSetSelectedTokenAction
  | RampsControllerGetProvidersAction
  | RampsControllerGetPaymentMethodsAction
  | RampsControllerSetSelectedPaymentMethodAction
  | RampsControllerGetQuotesAction
  | RampsControllerAddOrderAction
  | RampsControllerRemoveOrderAction
  | RampsControllerStartOrderPollingAction
  | RampsControllerStopOrderPollingAction
  | RampsControllerGetBuyWidgetDataAction
  | RampsControllerAddPrecreatedOrderAction
  | RampsControllerGetOrderAction
  | RampsControllerGetOrderFromCallbackAction
  | RampsControllerTransakSetApiKeyAction
  | RampsControllerTransakSetAccessTokenAction
  | RampsControllerTransakClearAccessTokenAction
  | RampsControllerTransakSetAuthenticatedAction
  | RampsControllerTransakResetStateAction
  | RampsControllerTransakSendUserOtpAction
  | RampsControllerTransakVerifyUserOtpAction
  | RampsControllerTransakLogoutAction
  | RampsControllerTransakGetUserDetailsAction
  | RampsControllerTransakGetBuyQuoteAction
  | RampsControllerTransakGetKycRequirementAction
  | RampsControllerTransakGetAdditionalRequirementsAction
  | RampsControllerTransakCreateOrderAction
  | RampsControllerTransakGetOrderAction
  | RampsControllerTransakGetUserLimitsAction
  | RampsControllerTransakRequestOttAction
  | RampsControllerTransakGeneratePaymentWidgetUrlAction
  | RampsControllerTransakSubmitPurposeOfUsageFormAction
  | RampsControllerTransakPatchUserAction
  | RampsControllerTransakSubmitSsnDetailsAction
  | RampsControllerTransakConfirmPaymentAction
  | RampsControllerTransakGetTranslationAction
  | RampsControllerTransakGetIdProofStatusAction
  | RampsControllerTransakCancelOrderAction
  | RampsControllerTransakCancelAllActiveOrdersAction
  | RampsControllerTransakGetActiveOrdersAction;
