/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { RampsService } from './RampsService';

/**
 * Makes a request to the API in order to retrieve the user's geolocation
 * based on their IP address.
 *
 * @returns The user's country/region code (e.g., "US-UT" for Utah, USA).
 */
export type RampsServiceGetGeolocationAction = {
  type: `RampsService:getGeolocation`;
  handler: RampsService['getGeolocation'];
};

/**
 * Union of all RampsService action types.
 */
export type RampsServiceMethodActions = RampsServiceGetGeolocationAction;
