/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { RampsService } from './RampsService';

/**
 * Makes a request to the API in order to retrieve the user's geolocation
 * based on their IP address.
 *
 * @returns The user's country/region code (e.g., "US-UT" for Utah, USA).
 */
export type RampsServiceGetGeolocationAction = {
  type: `RampsService:getGeolocation`;
  handler: RampsService['getGeolocation'];
};

/**
 * Makes a request to the cached API to retrieve the list of supported countries.
 * Filters countries based on aggregator support (preserves OnRampSDK logic).
 *
 * @param action - The ramp action type ('buy' or 'sell').
 * @returns An array of countries filtered by aggregator support.
 */
export type RampsServiceGetCountriesAction = {
  type: `RampsService:getCountries`;
  handler: RampsService['getCountries'];
};

/**
 * Fetches the list of available tokens for a given region and action.
 *
 * @param region - The region code (e.g., "us", "fr", "us-ny").
 * @param action - The ramp action type ('buy' or 'sell').
 * @returns The tokens response containing topTokens and allTokens.
 */
export type RampsServiceGetTokensAction = {
  type: `RampsService:getTokens`;
  handler: RampsService['getTokens'];
};

/**
 * Fetches the list of providers for a given region.
 * Supports optional query filters: provider, crypto, fiat, payments.
 *
 * @param regionCode - The region code (e.g., "us", "fr", "us-ny").
 * @param options - Optional query parameters for filtering providers.
 * @param options.provider - Provider ID(s) to filter by.
 * @param options.crypto - Crypto currency ID(s) to filter by.
 * @param options.fiat - Fiat currency ID(s) to filter by.
 * @param options.payments - Payment method ID(s) to filter by.
 * @returns The providers response containing providers array.
 */
export type RampsServiceGetProvidersAction = {
  type: `RampsService:getProviders`;
  handler: RampsService['getProviders'];
};

/**
 * Union of all RampsService action types.
 */
export type RampsServiceMethodActions =
  | RampsServiceGetGeolocationAction
  | RampsServiceGetCountriesAction
  | RampsServiceGetTokensAction
  | RampsServiceGetProvidersAction;
