/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { AssetsController } from './AssetsController';

export type AssetsControllerGetAssetsAction = {
  type: `AssetsController:getAssets`;
  handler: AssetsController['getAssets'];
};

export type AssetsControllerGetAssetsBalanceAction = {
  type: `AssetsController:getAssetsBalance`;
  handler: AssetsController['getAssetsBalance'];
};

export type AssetsControllerGetAssetMetadataAction = {
  type: `AssetsController:getAssetMetadata`;
  handler: AssetsController['getAssetMetadata'];
};

export type AssetsControllerGetAssetsPriceAction = {
  type: `AssetsController:getAssetsPrice`;
  handler: AssetsController['getAssetsPrice'];
};

/**
 * Add a custom asset for an account.
 * Custom assets are included in subscription and fetch operations.
 * Adding a custom asset also unhides it if it was previously hidden.
 *
 * When `pendingMetadata` is provided (e.g. from the extension's pending-tokens
 * flow), the token metadata is persisted immediately into `assetsInfo` so the
 * UI can render it without waiting for the next pipeline fetch.
 *
 * @param accountId - The account ID to add the custom asset for.
 * @param assetId - The CAIP-19 asset ID to add.
 * @param pendingMetadata - Optional token metadata from the UI (pendingTokens format).
 */
export type AssetsControllerAddCustomAssetAction = {
  type: `AssetsController:addCustomAsset`;
  handler: AssetsController['addCustomAsset'];
};

/**
 * Remove a custom asset from an account.
 *
 * @param accountId - The account ID to remove the custom asset from.
 * @param assetId - The CAIP-19 asset ID to remove.
 */
export type AssetsControllerRemoveCustomAssetAction = {
  type: `AssetsController:removeCustomAsset`;
  handler: AssetsController['removeCustomAsset'];
};

/**
 * Get all custom assets for an account.
 *
 * @param accountId - The account ID to get custom assets for.
 * @returns Array of CAIP-19 asset IDs for the account's custom assets.
 */
export type AssetsControllerGetCustomAssetsAction = {
  type: `AssetsController:getCustomAssets`;
  handler: AssetsController['getCustomAssets'];
};

/**
 * Hide an asset globally.
 * Hidden assets are excluded from the asset list returned by getAssets.
 * The hidden state is stored in assetPreferences.
 *
 * @param assetId - The CAIP-19 asset ID to hide.
 */
export type AssetsControllerHideAssetAction = {
  type: `AssetsController:hideAsset`;
  handler: AssetsController['hideAsset'];
};

/**
 * Unhide an asset globally.
 *
 * @param assetId - The CAIP-19 asset ID to unhide.
 */
export type AssetsControllerUnhideAssetAction = {
  type: `AssetsController:unhideAsset`;
  handler: AssetsController['unhideAsset'];
};

/**
 * Union of all AssetsController action types.
 */
export type AssetsControllerMethodActions =
  | AssetsControllerGetAssetsAction
  | AssetsControllerGetAssetsBalanceAction
  | AssetsControllerGetAssetMetadataAction
  | AssetsControllerGetAssetsPriceAction
  | AssetsControllerAddCustomAssetAction
  | AssetsControllerRemoveCustomAssetAction
  | AssetsControllerGetCustomAssetsAction
  | AssetsControllerHideAssetAction
  | AssetsControllerUnhideAssetAction;
