/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { AssetsController } from './AssetsController';

export type AssetsControllerGetAssetsAction = {
  type: `AssetsController:getAssets`;
  handler: AssetsController['getAssets'];
};

export type AssetsControllerGetAssetsBalanceAction = {
  type: `AssetsController:getAssetsBalance`;
  handler: AssetsController['getAssetsBalance'];
};

export type AssetsControllerGetAssetMetadataAction = {
  type: `AssetsController:getAssetMetadata`;
  handler: AssetsController['getAssetMetadata'];
};

export type AssetsControllerGetAssetsPriceAction = {
  type: `AssetsController:getAssetsPrice`;
  handler: AssetsController['getAssetsPrice'];
};

/**
 * Returns exchange rates in the format expected by the bridge controller
 * (conversionRates, currencyRates, marketData, currentCurrency) so that
 * when useAssetsControllerForRates is true the bridge can use a single
 * action instead of MultichainAssetsRatesController, TokenRatesController,
 * and CurrencyRateController.
 *
 * @param options - Optional options for bridge rate conversion.
 * @param options.usdToSelectedCurrencyRate - When selectedCurrency is not 'usd', pass 1 USD = this many units of selected currency so that currencyRates and conversionRates use correct user-currency vs USD values; otherwise the bridge USD conversion will be wrong for non-USD currencies.
 * @returns Bridge-compatible exchange rate state derived from assetsPrice and selectedCurrency.
 */
export type AssetsControllerGetExchangeRatesForBridgeAction = {
  type: `AssetsController:getExchangeRatesForBridge`;
  handler: AssetsController['getExchangeRatesForBridge'];
};

/**
 * Returns state in the legacy format expected by transaction-pay-controller
 * (TokenBalancesController, AccountTrackerController, TokensController,
 * TokenRatesController, CurrencyRateController shapes) so that when
 * useAssetsController is true the transaction-pay-controller can use a
 * single action instead of five separate getState calls.
 *
 * @returns Legacy-compatible state for transaction-pay-controller.
 */
export type AssetsControllerGetStateForTransactionPayAction = {
  type: `AssetsController:getStateForTransactionPay`;
  handler: AssetsController['getStateForTransactionPay'];
};

/**
 * Add a custom asset for an account.
 * Custom assets are included in subscription and fetch operations.
 * Adding a custom asset also unhides it if it was previously hidden.
 *
 * When `pendingMetadata` is provided (e.g. from the extension's pending-tokens
 * flow), the token metadata is persisted immediately into `assetsInfo` so the
 * UI can render it without waiting for the next pipeline fetch.
 *
 * @param accountId - The account ID to add the custom asset for.
 * @param assetId - The CAIP-19 asset ID to add.
 * @param pendingMetadata - Optional token metadata from the UI (pendingTokens format).
 */
export type AssetsControllerAddCustomAssetAction = {
  type: `AssetsController:addCustomAsset`;
  handler: AssetsController['addCustomAsset'];
};

/**
 * Remove a custom asset from an account.
 *
 * @param accountId - The account ID to remove the custom asset from.
 * @param assetId - The CAIP-19 asset ID to remove.
 */
export type AssetsControllerRemoveCustomAssetAction = {
  type: `AssetsController:removeCustomAsset`;
  handler: AssetsController['removeCustomAsset'];
};

/**
 * Get all custom assets for an account.
 *
 * @param accountId - The account ID to get custom assets for.
 * @returns Array of CAIP-19 asset IDs for the account's custom assets.
 */
export type AssetsControllerGetCustomAssetsAction = {
  type: `AssetsController:getCustomAssets`;
  handler: AssetsController['getCustomAssets'];
};

/**
 * Hide an asset globally.
 * Hidden assets are excluded from the asset list returned by getAssets.
 * The hidden state is stored in assetPreferences.
 *
 * @param assetId - The CAIP-19 asset ID to hide.
 */
export type AssetsControllerHideAssetAction = {
  type: `AssetsController:hideAsset`;
  handler: AssetsController['hideAsset'];
};

/**
 * Unhide an asset globally.
 *
 * @param assetId - The CAIP-19 asset ID to unhide.
 */
export type AssetsControllerUnhideAssetAction = {
  type: `AssetsController:unhideAsset`;
  handler: AssetsController['unhideAsset'];
};

/**
 * Union of all AssetsController action types.
 */
export type AssetsControllerMethodActions =
  | AssetsControllerGetAssetsAction
  | AssetsControllerGetAssetsBalanceAction
  | AssetsControllerGetAssetMetadataAction
  | AssetsControllerGetAssetsPriceAction
  | AssetsControllerGetExchangeRatesForBridgeAction
  | AssetsControllerGetStateForTransactionPayAction
  | AssetsControllerAddCustomAssetAction
  | AssetsControllerRemoveCustomAssetAction
  | AssetsControllerGetCustomAssetsAction
  | AssetsControllerHideAssetAction
  | AssetsControllerUnhideAssetAction;
