/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { ErrorReportingService } from './error-reporting-service';

/**
 * Reports the given error to an external location.
 *
 * @param error - The error to report.
 * @deprecated This function is deprecated and will be removed in a future
 * release. Please use `Messenger.captureException` directly instead.
 */
export type ErrorReportingServiceCaptureExceptionAction = {
  type: `ErrorReportingService:captureException`;
  handler: ErrorReportingService['captureException'];
};

/**
 * Union of all ErrorReportingService action types.
 */
export type ErrorReportingServiceMethodActions =
  ErrorReportingServiceCaptureExceptionAction;
