/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { AddressBookController } from './AddressBookController';

/**
 * Returns all address book entries as an array.
 *
 * @returns Array of all address book entries.
 */
export type AddressBookControllerListAction = {
  type: `AddressBookController:list`;
  handler: AddressBookController['list'];
};

/**
 * Remove a contract entry by address.
 *
 * @param chainId - Chain id identifies the current chain.
 * @param address - Recipient address to delete.
 * @returns Whether the entry was deleted.
 */
export type AddressBookControllerDeleteAction = {
  type: `AddressBookController:delete`;
  handler: AddressBookController['delete'];
};

/**
 * Add or update a contact entry by address.
 *
 * @param address - Recipient address to add or update.
 * @param name - Nickname to associate with this address.
 * @param chainId - Chain id identifies the current chain.
 * @param memo - User's note about address.
 * @param addressType - Contact's address type.
 * @returns Boolean indicating if the address was successfully set.
 */
export type AddressBookControllerSetAction = {
  type: `AddressBookController:set`;
  handler: AddressBookController['set'];
};

/**
 * Union of all AddressBookController action types.
 */
export type AddressBookControllerMethodActions =
  | AddressBookControllerListAction
  | AddressBookControllerDeleteAction
  | AddressBookControllerSetAction;
