/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { GeolocationController } from './GeolocationController';

/**
 * Returns the cached geolocation if still valid, otherwise fetches it.
 * Concurrent calls are deduplicated to a single network request.
 *
 * @returns The ISO country code string.
 */
export type GeolocationControllerGetGeolocationAction = {
  type: `GeolocationController:getGeolocation`;
  handler: GeolocationController['getGeolocation'];
};

/**
 * Forces a fresh geolocation fetch, bypassing the cache.
 *
 * @returns The ISO country code string.
 */
export type GeolocationControllerRefreshGeolocationAction = {
  type: `GeolocationController:refreshGeolocation`;
  handler: GeolocationController['refreshGeolocation'];
};

/**
 * Union of all GeolocationController action types.
 */
export type GeolocationControllerMethodActions =
  | GeolocationControllerGetGeolocationAction
  | GeolocationControllerRefreshGeolocationAction;
