/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { AnalyticsPrivacyService } from './AnalyticsPrivacyService';

/**
 * Creates a DELETE_ONLY regulation for the given analyticsId.
 *
 * @param analyticsId - The analytics ID of the user for whom to create the deletion task.
 * @returns Promise resolving to the deletion regulation response.
 */
export type AnalyticsPrivacyServiceCreateDataDeletionTaskAction = {
  type: `AnalyticsPrivacyService:createDataDeletionTask`;
  handler: AnalyticsPrivacyService['createDataDeletionTask'];
};

/**
 * Checks the status of a regulation by ID.
 *
 * @param regulationId - The regulation ID to check.
 * @returns Promise resolving to the regulation status response.
 */
export type AnalyticsPrivacyServiceCheckDataDeleteStatusAction = {
  type: `AnalyticsPrivacyService:checkDataDeleteStatus`;
  handler: AnalyticsPrivacyService['checkDataDeleteStatus'];
};

/**
 * Union of all AnalyticsPrivacyService action types.
 */
export type AnalyticsPrivacyServiceMethodActions =
  | AnalyticsPrivacyServiceCreateDataDeletionTaskAction
  | AnalyticsPrivacyServiceCheckDataDeleteStatusAction;
