/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { AnalyticsPrivacyController } from './AnalyticsPrivacyController';

/**
 * Creates a new delete regulation for the user.
 * This is necessary to respect the GDPR and CCPA regulations.
 *
 * @returns Promise containing the status of the request with regulateId
 * @throws Error if analytics ID is missing or if the service call fails
 */
export type AnalyticsPrivacyControllerCreateDataDeletionTaskAction = {
  type: `AnalyticsPrivacyController:createDataDeletionTask`;
  handler: AnalyticsPrivacyController['createDataDeletionTask'];
};

/**
 * Check the latest delete regulation status.
 *
 * @returns Promise containing the timestamp, delete status and collected data flag
 */
export type AnalyticsPrivacyControllerCheckDataDeleteStatusAction = {
  type: `AnalyticsPrivacyController:checkDataDeleteStatus`;
  handler: AnalyticsPrivacyController['checkDataDeleteStatus'];
};

/**
 * Update the data recording flag if needed.
 * This method should be called after tracking events to ensure
 * the data recording flag is properly updated for data deletion workflows.
 *
 * The flag can only be set to `true` (indicating data has been collected).
 * It cannot be explicitly set to `false` - it is only reset to `false` when
 * a new deletion task is created via `createDataDeletionTask`.
 *
 * If `saveDataRecording` is `false` or the flag is already `true`, this method
 * does nothing. This design ensures the flag only moves from `false` to `true`
 * and cannot be manually reset, maintaining data integrity for compliance tracking.
 *
 * @param saveDataRecording - Whether to save the data recording flag (default: true).
 * When `false`, this method is a no-op regardless of current state.
 */
export type AnalyticsPrivacyControllerUpdateDataRecordingFlagAction = {
  type: `AnalyticsPrivacyController:updateDataRecordingFlag`;
  handler: AnalyticsPrivacyController['updateDataRecordingFlag'];
};

/**
 * Union of all AnalyticsPrivacyController action types.
 */
export type AnalyticsPrivacyControllerMethodActions =
  | AnalyticsPrivacyControllerCreateDataDeletionTaskAction
  | AnalyticsPrivacyControllerCheckDataDeleteStatusAction
  | AnalyticsPrivacyControllerUpdateDataRecordingFlagAction;
