/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { AnalyticsPrivacyController } from './AnalyticsPrivacyController';

/**
 * Creates a new delete regulation for the user.
 * This is necessary to respect the GDPR and CCPA regulations.
 *
 * @returns Promise containing the status of the request
 */
export type AnalyticsPrivacyControllerCreateDataDeletionTaskAction = {
  type: `AnalyticsPrivacyController:createDataDeletionTask`;
  handler: AnalyticsPrivacyController['createDataDeletionTask'];
};

/**
 * Check the latest delete regulation status.
 *
 * @returns Promise containing the date, delete status and collected data flag
 */
export type AnalyticsPrivacyControllerCheckDataDeleteStatusAction = {
  type: `AnalyticsPrivacyController:checkDataDeleteStatus`;
  handler: AnalyticsPrivacyController['checkDataDeleteStatus'];
};

/**
 * Get the latest delete regulation request date.
 *
 * @returns The date as a DD/MM/YYYY string, or undefined
 */
export type AnalyticsPrivacyControllerGetDeleteRegulationCreationDateAction = {
  type: `AnalyticsPrivacyController:getDeleteRegulationCreationDate`;
  handler: AnalyticsPrivacyController['getDeleteRegulationCreationDate'];
};

/**
 * Get the latest delete regulation request id.
 *
 * @returns The id string, or undefined
 */
export type AnalyticsPrivacyControllerGetDeleteRegulationIdAction = {
  type: `AnalyticsPrivacyController:getDeleteRegulationId`;
  handler: AnalyticsPrivacyController['getDeleteRegulationId'];
};

/**
 * Indicate if events have been recorded since the last deletion request.
 *
 * @returns true if events have been recorded since the last deletion request
 */
export type AnalyticsPrivacyControllerIsDataRecordedAction = {
  type: `AnalyticsPrivacyController:isDataRecorded`;
  handler: AnalyticsPrivacyController['isDataRecorded'];
};

/**
 * Update the data recording flag if needed.
 * This method should be called after tracking events to ensure
 * the data recording flag is properly updated for data deletion workflows.
 *
 * @param saveDataRecording - Whether to save the data recording flag (default: true)
 */
export type AnalyticsPrivacyControllerUpdateDataRecordingFlagAction = {
  type: `AnalyticsPrivacyController:updateDataRecordingFlag`;
  handler: AnalyticsPrivacyController['updateDataRecordingFlag'];
};

/**
 * Union of all AnalyticsPrivacyController action types.
 */
export type AnalyticsPrivacyControllerMethodActions =
  | AnalyticsPrivacyControllerCreateDataDeletionTaskAction
  | AnalyticsPrivacyControllerCheckDataDeleteStatusAction
  | AnalyticsPrivacyControllerGetDeleteRegulationCreationDateAction
  | AnalyticsPrivacyControllerGetDeleteRegulationIdAction
  | AnalyticsPrivacyControllerIsDataRecordedAction
  | AnalyticsPrivacyControllerUpdateDataRecordingFlagAction;
