import type {
  PerpsMarketCollectionTag,
  PerpsMarketDefinition,
} from '../types';

/**
 * Ordered list of all market collection tags for UI filter pills.
 * The order here determines display order in the consumer UI.
 */
export const PERPS_MARKET_COLLECTION_TAGS: readonly PerpsMarketCollectionTag[] =
  [
    'L1',
    'L2 / Scaling',
    'Bitcoin Ecosystem',
    'Solana Ecosystem',
    'Cosmos Ecosystem',
    'TON Ecosystem',
    'Hyperliquid Ecosystem',
    'Move Ecosystem',
    'Smart Contract Platform',
    'DeFi',
    'Exchange Token',
    'Memecoin',
    'Gaming / NFT',
    'AI / DePIN',
    'Infrastructure',
    'Oracle',
    'Interoperability',
    'Payments',
    'LSD / Liquid Staking',
    'RWA / Stablecoin',
    'ZK / Modular',
    'Privacy',
    'Storage / Data',
    'Store of Value',
    'Metaverse',
    'IoT / Infrastructure',
    'Political',
  ] as const;

/**
 * Canonical registry of all supported perps markets.
 * Each entry defines the ticker, maximum leverage, and thematic collections.
 */
export const PERPS_MARKET_DEFINITIONS: readonly PerpsMarketDefinition[] = [
  { ticker: 'BTC', maxLeverage: 40, collections: ['L1', 'Bitcoin Ecosystem', 'Store of Value'] },
  { ticker: 'ETH', maxLeverage: 25, collections: ['L1', 'Smart Contract Platform'] },
  { ticker: 'ATOM', maxLeverage: 5, collections: ['L1', 'Cosmos Ecosystem', 'Interoperability'] },
  { ticker: 'DYDX', maxLeverage: 5, collections: ['DeFi', 'Cosmos Ecosystem', 'Exchange Token'] },
  { ticker: 'SOL', maxLeverage: 20, collections: ['L1', 'Solana Ecosystem'] },
  { ticker: 'AVAX', maxLeverage: 10, collections: ['L1', 'Smart Contract Platform'] },
  { ticker: 'BNB', maxLeverage: 10, collections: ['L1', 'Exchange Token', 'Smart Contract Platform'] },
  { ticker: 'APE', maxLeverage: 5, collections: ['Gaming / NFT'] },
  { ticker: 'OP', maxLeverage: 5, collections: ['L2 / Scaling'] },
  { ticker: 'LTC', maxLeverage: 10, collections: ['L1', 'Bitcoin Ecosystem', 'Payments'] },
  { ticker: 'ARB', maxLeverage: 10, collections: ['L2 / Scaling'] },
  { ticker: 'DOGE', maxLeverage: 10, collections: ['L1', 'Memecoin', 'Payments'] },
  { ticker: 'INJ', maxLeverage: 5, collections: ['L1', 'Cosmos Ecosystem', 'DeFi'] },
  { ticker: 'SUI', maxLeverage: 10, collections: ['L1', 'Move Ecosystem'] },
  { ticker: 'kPEPE', maxLeverage: 10, collections: ['Memecoin'] },
  { ticker: 'CRV', maxLeverage: 10, collections: ['DeFi'] },
  { ticker: 'LDO', maxLeverage: 5, collections: ['DeFi', 'LSD / Liquid Staking'] },
  { ticker: 'LINK', maxLeverage: 10, collections: ['Infrastructure', 'Oracle'] },
  { ticker: 'STX', maxLeverage: 5, collections: ['L2 / Scaling', 'Bitcoin Ecosystem'] },
  { ticker: 'CFX', maxLeverage: 5, collections: ['L1', 'Smart Contract Platform'] },
  { ticker: 'GMX', maxLeverage: 3, collections: ['DeFi', 'Exchange Token'] },
  { ticker: 'SNX', maxLeverage: 3, collections: ['DeFi'] },
  { ticker: 'XRP', maxLeverage: 20, collections: ['L1', 'Payments'] },
  { ticker: 'BCH', maxLeverage: 10, collections: ['L1', 'Bitcoin Ecosystem', 'Payments'] },
  { ticker: 'APT', maxLeverage: 10, collections: ['L1', 'Move Ecosystem'] },
  { ticker: 'AAVE', maxLeverage: 10, collections: ['DeFi'] },
  { ticker: 'COMP', maxLeverage: 5, collections: ['DeFi'] },
  { ticker: 'WLD', maxLeverage: 10, collections: ['AI / DePIN'] },
  { ticker: 'YGG', maxLeverage: 3, collections: ['Gaming / NFT'] },
  { ticker: 'TRX', maxLeverage: 10, collections: ['L1', 'Smart Contract Platform'] },
  { ticker: 'kSHIB', maxLeverage: 10, collections: ['Memecoin'] },
  { ticker: 'UNI', maxLeverage: 10, collections: ['DeFi', 'Exchange Token'] },
  { ticker: 'SEI', maxLeverage: 5, collections: ['L1', 'Cosmos Ecosystem', 'DeFi'] },
  { ticker: 'RUNE', maxLeverage: 5, collections: ['Bitcoin Ecosystem', 'DeFi'] },
  { ticker: 'ZRO', maxLeverage: 5, collections: ['Infrastructure', 'Interoperability'] },
  { ticker: 'DOT', maxLeverage: 10, collections: ['L1', 'Interoperability'] },
  { ticker: 'BANANA', maxLeverage: 3, collections: ['Memecoin', 'DeFi'] },
  { ticker: 'TRB', maxLeverage: 3, collections: ['Infrastructure', 'Oracle'] },
  { ticker: 'FTT', maxLeverage: 3, collections: ['Exchange Token'] },
  { ticker: 'ARK', maxLeverage: 3, collections: ['L1'] },
  { ticker: 'BIGTIME', maxLeverage: 3, collections: ['Gaming / NFT'] },
  { ticker: 'KAS', maxLeverage: 3, collections: ['L1', 'Bitcoin Ecosystem'] },
  { ticker: 'BLUR', maxLeverage: 3, collections: ['Gaming / NFT', 'DeFi'] },
  { ticker: 'TIA', maxLeverage: 5, collections: ['L1', 'ZK / Modular', 'Cosmos Ecosystem'] },
  { ticker: 'BSV', maxLeverage: 3, collections: ['L1', 'Bitcoin Ecosystem'] },
  { ticker: 'ADA', maxLeverage: 10, collections: ['L1', 'Smart Contract Platform'] },
  { ticker: 'TON', maxLeverage: 10, collections: ['L1', 'TON Ecosystem'] },
  { ticker: 'MINA', maxLeverage: 3, collections: ['L1', 'ZK / Modular'] },
  { ticker: 'POLYX', maxLeverage: 3, collections: ['RWA / Stablecoin', 'Infrastructure'] },
  { ticker: 'GAS', maxLeverage: 3, collections: ['Infrastructure'] },
  { ticker: 'PENDLE', maxLeverage: 5, collections: ['DeFi', 'LSD / Liquid Staking'] },
  { ticker: 'FET', maxLeverage: 5, collections: ['AI / DePIN', 'Infrastructure'] },
  { ticker: 'NEAR', maxLeverage: 10, collections: ['L1', 'Smart Contract Platform'] },
  { ticker: 'MEME', maxLeverage: 3, collections: ['Memecoin'] },
  { ticker: 'ORDI', maxLeverage: 3, collections: ['Bitcoin Ecosystem'] },
  { ticker: 'NEO', maxLeverage: 5, collections: ['L1', 'Smart Contract Platform'] },
  { ticker: 'ZEN', maxLeverage: 5, collections: ['L1', 'Privacy'] },
  { ticker: 'FIL', maxLeverage: 5, collections: ['L1', 'Storage / Data'] },
  { ticker: 'PYTH', maxLeverage: 5, collections: ['Infrastructure', 'Oracle', 'Solana Ecosystem'] },
  { ticker: 'SUSHI', maxLeverage: 3, collections: ['DeFi', 'Exchange Token'] },
  { ticker: 'IMX', maxLeverage: 5, collections: ['Gaming / NFT', 'L2 / Scaling'] },
  { ticker: 'kBONK', maxLeverage: 10, collections: ['Memecoin', 'Solana Ecosystem'] },
  { ticker: 'GMT', maxLeverage: 3, collections: ['Gaming / NFT'] },
  { ticker: 'SUPER', maxLeverage: 3, collections: ['Gaming / NFT'] },
  { ticker: 'JUP', maxLeverage: 10, collections: ['DeFi', 'Solana Ecosystem', 'Exchange Token'] },
  { ticker: 'kLUNC', maxLeverage: 3, collections: ['Memecoin'] },
  { ticker: 'RSR', maxLeverage: 3, collections: ['DeFi', 'RWA / Stablecoin'] },
  { ticker: 'GALA', maxLeverage: 3, collections: ['Gaming / NFT'] },
  { ticker: 'JTO', maxLeverage: 5, collections: ['DeFi', 'Solana Ecosystem', 'LSD / Liquid Staking'] },
  { ticker: 'ACE', maxLeverage: 3, collections: ['Gaming / NFT'] },
  { ticker: 'WIF', maxLeverage: 5, collections: ['Memecoin', 'Solana Ecosystem'] },
  { ticker: 'CAKE', maxLeverage: 3, collections: ['DeFi', 'Exchange Token'] },
  { ticker: 'PEOPLE', maxLeverage: 3, collections: ['Memecoin'] },
  { ticker: 'ENS', maxLeverage: 5, collections: ['Infrastructure'] },
  { ticker: 'ETC', maxLeverage: 5, collections: ['L1', 'Bitcoin Ecosystem'] },
  { ticker: 'XAI', maxLeverage: 3, collections: ['Gaming / NFT', 'L2 / Scaling'] },
  { ticker: 'MANTA', maxLeverage: 3, collections: ['L2 / Scaling', 'ZK / Modular'] },
  { ticker: 'UMA', maxLeverage: 3, collections: ['Infrastructure', 'Oracle', 'DeFi'] },
  { ticker: 'ONDO', maxLeverage: 10, collections: ['RWA / Stablecoin', 'DeFi'] },
  { ticker: 'ALT', maxLeverage: 3, collections: ['L2 / Scaling', 'ZK / Modular'] },
  { ticker: 'ZETA', maxLeverage: 3, collections: ['L1', 'Interoperability'] },
  { ticker: 'DYM', maxLeverage: 3, collections: ['L1', 'ZK / Modular'] },
  { ticker: 'W', maxLeverage: 5, collections: ['L1', 'Interoperability'] },
  { ticker: 'STRK', maxLeverage: 5, collections: ['L2 / Scaling', 'ZK / Modular'] },
  { ticker: 'TAO', maxLeverage: 5, collections: ['L1', 'AI / DePIN'] },
  { ticker: 'AR', maxLeverage: 5, collections: ['L1', 'Storage / Data'] },
  { ticker: 'kFLOKI', maxLeverage: 5, collections: ['Memecoin'] },
  { ticker: 'BOME', maxLeverage: 3, collections: ['Memecoin', 'Solana Ecosystem'] },
  { ticker: 'ETHFI', maxLeverage: 5, collections: ['DeFi', 'LSD / Liquid Staking'] },
  { ticker: 'ENA', maxLeverage: 10, collections: ['DeFi', 'RWA / Stablecoin'] },
  { ticker: 'MNT', maxLeverage: 5, collections: ['L2 / Scaling', 'Exchange Token'] },
  { ticker: 'TNSR', maxLeverage: 3, collections: ['Gaming / NFT', 'Solana Ecosystem'] },
  { ticker: 'SAGA', maxLeverage: 3, collections: ['L1', 'Gaming / NFT'] },
  { ticker: 'MERL', maxLeverage: 3, collections: ['L2 / Scaling', 'Bitcoin Ecosystem'] },
  { ticker: 'HBAR', maxLeverage: 5, collections: ['L1', 'Smart Contract Platform'] },
  { ticker: 'POPCAT', maxLeverage: 3, collections: ['Memecoin', 'Solana Ecosystem'] },
  { ticker: 'EIGEN', maxLeverage: 5, collections: ['Infrastructure', 'LSD / Liquid Staking'] },
  { ticker: 'REZ', maxLeverage: 3, collections: ['DeFi', 'LSD / Liquid Staking'] },
  { ticker: 'NOT', maxLeverage: 3, collections: ['Memecoin', 'TON Ecosystem'] },
  { ticker: 'TURBO', maxLeverage: 3, collections: ['AI / DePIN', 'Memecoin'] },
  { ticker: 'BRETT', maxLeverage: 3, collections: ['Memecoin'] },
  { ticker: 'IO', maxLeverage: 3, collections: ['AI / DePIN'] },
  { ticker: 'ZK', maxLeverage: 5, collections: ['L2 / Scaling', 'ZK / Modular'] },
  { ticker: 'BLAST', maxLeverage: 3, collections: ['L2 / Scaling', 'DeFi'] },
  { ticker: 'RENDER', maxLeverage: 5, collections: ['AI / DePIN'] },
  { ticker: 'POL', maxLeverage: 5, collections: ['L2 / Scaling'] },
  { ticker: 'CELO', maxLeverage: 3, collections: ['L1', 'Payments'] },
  { ticker: 'HMSTR', maxLeverage: 3, collections: ['Memecoin', 'TON Ecosystem'] },
  { ticker: 'kNEIRO', maxLeverage: 3, collections: ['Memecoin'] },
  { ticker: 'GOAT', maxLeverage: 3, collections: ['AI / DePIN', 'Memecoin'] },
  { ticker: 'MOODENG', maxLeverage: 3, collections: ['Memecoin'] },
  { ticker: 'GRASS', maxLeverage: 3, collections: ['AI / DePIN'] },
  { ticker: 'PURR', maxLeverage: 3, collections: ['Memecoin', 'Hyperliquid Ecosystem'] },
  { ticker: 'PNUT', maxLeverage: 3, collections: ['Memecoin', 'Solana Ecosystem'] },
  { ticker: 'XLM', maxLeverage: 5, collections: ['L1', 'Payments'] },
  { ticker: 'CHILLGUY', maxLeverage: 3, collections: ['Memecoin', 'Solana Ecosystem'] },
  { ticker: 'SAND', maxLeverage: 5, collections: ['Gaming / NFT', 'Metaverse'] },
  { ticker: 'IOTA', maxLeverage: 3, collections: ['L1', 'IoT / Infrastructure'] },
  { ticker: 'ALGO', maxLeverage: 5, collections: ['L1', 'Smart Contract Platform'] },
  { ticker: 'HYPE', maxLeverage: 10, collections: ['L1', 'Exchange Token', 'Hyperliquid Ecosystem'] },
  { ticker: 'ME', maxLeverage: 3, collections: ['Gaming / NFT', 'Solana Ecosystem'] },
  { ticker: 'MOVE', maxLeverage: 3, collections: ['L1', 'Move Ecosystem'] },
  { ticker: 'VIRTUAL', maxLeverage: 5, collections: ['AI / DePIN'] },
  { ticker: 'PENGU', maxLeverage: 5, collections: ['Memecoin', 'Gaming / NFT', 'Solana Ecosystem'] },
  { ticker: 'USUAL', maxLeverage: 3, collections: ['DeFi', 'RWA / Stablecoin'] },
  { ticker: 'FARTCOIN', maxLeverage: 10, collections: ['Memecoin'] },
  { ticker: 'AIXBT', maxLeverage: 3, collections: ['AI / DePIN', 'Memecoin'] },
  { ticker: 'BIO', maxLeverage: 3, collections: ['AI / DePIN'] },
  { ticker: 'GRIFFAIN', maxLeverage: 3, collections: ['AI / DePIN', 'Memecoin'] },
  { ticker: 'SPX', maxLeverage: 5, collections: ['AI / DePIN', 'Memecoin'] },
  { ticker: 'S', maxLeverage: 5, collections: ['L1', 'Smart Contract Platform'] },
  { ticker: 'MORPHO', maxLeverage: 5, collections: ['DeFi'] },
  { ticker: 'TRUMP', maxLeverage: 10, collections: ['Memecoin', 'Political'] },
  { ticker: 'MELANIA', maxLeverage: 3, collections: ['Memecoin', 'Political'] },
  { ticker: 'ANIME', maxLeverage: 3, collections: ['Gaming / NFT', 'Memecoin'] },
  { ticker: 'VINE', maxLeverage: 3, collections: ['Memecoin'] },
  { ticker: 'VVV', maxLeverage: 3, collections: ['DeFi'] },
  { ticker: 'BERA', maxLeverage: 5, collections: ['L1', 'DeFi'] },
  { ticker: 'TST', maxLeverage: 3, collections: ['Memecoin'] },
  { ticker: 'LAYER', maxLeverage: 3, collections: ['LSD / Liquid Staking', 'Solana Ecosystem'] },
  { ticker: 'IP', maxLeverage: 3, collections: ['Infrastructure'] },
  { ticker: 'KAITO', maxLeverage: 5, collections: ['AI / DePIN', 'Infrastructure'] },
  { ticker: 'NIL', maxLeverage: 3, collections: ['L1', 'ZK / Modular'] },
  { ticker: 'PAXG', maxLeverage: 10, collections: ['RWA / Stablecoin'] },
  { ticker: 'BABY', maxLeverage: 3, collections: ['Memecoin'] },
  { ticker: 'WCT', maxLeverage: 3, collections: ['Infrastructure'] },
  { ticker: 'HYPER', maxLeverage: 3, collections: ['AI / DePIN'] },
  { ticker: 'ZORA', maxLeverage: 3, collections: ['Gaming / NFT', 'L2 / Scaling'] },
  { ticker: 'INIT', maxLeverage: 3, collections: ['L1', 'Smart Contract Platform'] },
  { ticker: 'DOOD', maxLeverage: 3, collections: ['Gaming / NFT', 'Memecoin'] },
  { ticker: 'NXPC', maxLeverage: 3, collections: [] },
  { ticker: 'SOPH', maxLeverage: 3, collections: ['L2 / Scaling', 'AI / DePIN'] },
  { ticker: 'RESOLV', maxLeverage: 3, collections: ['DeFi', 'RWA / Stablecoin'] },
  { ticker: 'SYRUP', maxLeverage: 3, collections: ['DeFi'] },
  { ticker: 'PUMP', maxLeverage: 10, collections: ['Memecoin', 'Solana Ecosystem'] },
  { ticker: 'PROVE', maxLeverage: 3, collections: ['ZK / Modular', 'Infrastructure'] },
  { ticker: 'XPL', maxLeverage: 10, collections: [] },
  { ticker: 'WLFI', maxLeverage: 5, collections: ['DeFi'] },
  { ticker: 'LINEA', maxLeverage: 3, collections: ['L2 / Scaling', 'ZK / Modular'] },
  { ticker: 'SKY', maxLeverage: 3, collections: ['DeFi', 'RWA / Stablecoin'] },
  { ticker: 'ASTER', maxLeverage: 5, collections: ['DeFi', 'Exchange Token'] },
  { ticker: 'AVNT', maxLeverage: 5, collections: [] },
  { ticker: 'STBL', maxLeverage: 3, collections: ['RWA / Stablecoin'] },
  { ticker: '0G', maxLeverage: 3, collections: ['AI / DePIN', 'Storage / Data'] },
  { ticker: 'HEMI', maxLeverage: 3, collections: ['L2 / Scaling', 'Bitcoin Ecosystem'] },
  { ticker: 'APEX', maxLeverage: 3, collections: ['DeFi', 'Exchange Token'] },
  { ticker: '2Z', maxLeverage: 3, collections: [] },
  { ticker: 'ZEC', maxLeverage: 10, collections: ['L1', 'Privacy'] },
  { ticker: 'MON', maxLeverage: 5, collections: ['L1', 'Smart Contract Platform'] },
  { ticker: 'MET', maxLeverage: 3, collections: ['L2 / Scaling'] },
  { ticker: 'MEGA', maxLeverage: 3, collections: ['L2 / Scaling'] },
  { ticker: 'CC', maxLeverage: 3, collections: [] },
  { ticker: 'ICP', maxLeverage: 5, collections: ['L1', 'Infrastructure'] },
  { ticker: 'AERO', maxLeverage: 3, collections: ['DeFi', 'Exchange Token'] },
  { ticker: 'STABLE', maxLeverage: 3, collections: ['RWA / Stablecoin'] },
  { ticker: 'FOGO', maxLeverage: 3, collections: [] },
  { ticker: 'LIT', maxLeverage: 5, collections: ['Infrastructure', 'Privacy'] },
  { ticker: 'XMR', maxLeverage: 5, collections: ['L1', 'Privacy'] },
  { ticker: 'AXS', maxLeverage: 5, collections: ['Gaming / NFT'] },
  { ticker: 'DASH', maxLeverage: 5, collections: ['L1', 'Privacy', 'Payments'] },
  { ticker: 'SKR', maxLeverage: 3, collections: [] },
  { ticker: 'AZTEC', maxLeverage: 3, collections: ['L2 / Scaling', 'ZK / Modular', 'Privacy'] },
  { ticker: 'CHIP', maxLeverage: 3, collections: [] },
] as const;

const marketsByTicker = new Map<string, PerpsMarketDefinition>(
  PERPS_MARKET_DEFINITIONS.map((m) => [m.ticker, m]),
);

/**
 * Look up a single market definition by its ticker symbol.
 * O(1) via pre-built Map.
 *
 * @param ticker - The ticker to look up (e.g. 'BTC', 'ETH').
 * @returns The matching definition, or `undefined` if not found.
 */
export function getMarketDefinitionByTicker(
  ticker: string,
): PerpsMarketDefinition | undefined {
  return marketsByTicker.get(ticker);
}

/**
 * Return all market definitions that belong to a given collection tag.
 *
 * @param collection - The collection tag to filter by.
 * @returns Array of matching market definitions (may be empty).
 */
export function getMarketDefinitionsByCollection(
  collection: PerpsMarketCollectionTag,
): PerpsMarketDefinition[] {
  return PERPS_MARKET_DEFINITIONS.filter((m) =>
    m.collections.includes(collection),
  );
}
