/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { NotificationServicesPushController } from './NotificationServicesPushController';

export type NotificationServicesPushControllerSubscribeToPushNotificationsAction =
  {
    type: `NotificationServicesPushController:subscribeToPushNotifications`;
    handler: NotificationServicesPushController['subscribeToPushNotifications'];
  };

/**
 * Enables push notifications for the application.
 *
 * This method sets up the necessary infrastructure for handling push notifications by:
 * 1. Registering the service worker to listen for messages.
 * 2. Fetching the Firebase Cloud Messaging (FCM) token from Firebase.
 * 3. Sending the FCM token to the server responsible for sending notifications, to register the device.
 *
 * @param addresses - An array of addresses to enable push notifications for.
 */
export type NotificationServicesPushControllerEnablePushNotificationsAction = {
  type: `NotificationServicesPushController:enablePushNotifications`;
  handler: NotificationServicesPushController['enablePushNotifications'];
};

/**
 * Disables push notifications for the application.
 * This removes the registration token on this device, and ensures we unsubscribe from any listeners
 */
export type NotificationServicesPushControllerDisablePushNotificationsAction = {
  type: `NotificationServicesPushController:disablePushNotifications`;
  handler: NotificationServicesPushController['disablePushNotifications'];
};

/**
 * Updates the triggers for push notifications.
 * This method is responsible for updating the server with the new set of addresses that should trigger push notifications.
 * It uses the current FCM token and a BearerToken for authentication.
 *
 * @param addresses - An array of addresses that should trigger push notifications.
 * @deprecated - this is not used anymore and will most likely be removed
 */
export type NotificationServicesPushControllerUpdateTriggerPushNotificationsAction =
  {
    type: `NotificationServicesPushController:updateTriggerPushNotifications`;
    handler: NotificationServicesPushController['updateTriggerPushNotifications'];
  };

/**
 * Union of all NotificationServicesPushController action types.
 */
export type NotificationServicesPushControllerMethodActions =
  | NotificationServicesPushControllerSubscribeToPushNotificationsAction
  | NotificationServicesPushControllerEnablePushNotificationsAction
  | NotificationServicesPushControllerDisablePushNotificationsAction
  | NotificationServicesPushControllerUpdateTriggerPushNotificationsAction;
