/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { PerpsController } from './PerpsController';

/**
 * Place a new order
 * Thin delegation to TradingService
 *
 * @param params - The operation parameters.
 * @returns The order result with order ID and status.
 */
export type PerpsControllerPlaceOrderAction = {
  type: `PerpsController:placeOrder`;
  handler: PerpsController['placeOrder'];
};

/**
 * Edit an existing order
 * Thin delegation to TradingService
 *
 * @param params - The operation parameters.
 * @returns The updated order result with order ID and status.
 */
export type PerpsControllerEditOrderAction = {
  type: `PerpsController:editOrder`;
  handler: PerpsController['editOrder'];
};

/**
 * Cancel an existing order
 *
 * @param params - The operation parameters.
 * @returns The cancellation result with status.
 */
export type PerpsControllerCancelOrderAction = {
  type: `PerpsController:cancelOrder`;
  handler: PerpsController['cancelOrder'];
};

/**
 * Cancel multiple orders in parallel
 * Batch version of cancelOrder() that cancels multiple orders simultaneously
 *
 * @param params - The operation parameters.
 * @returns The batch cancellation results for each order.
 */
export type PerpsControllerCancelOrdersAction = {
  type: `PerpsController:cancelOrders`;
  handler: PerpsController['cancelOrders'];
};

/**
 * Close a position (partial or full)
 * Thin delegation to TradingService
 *
 * @param params - The operation parameters.
 * @returns The order result from the close position request.
 */
export type PerpsControllerClosePositionAction = {
  type: `PerpsController:closePosition`;
  handler: PerpsController['closePosition'];
};

/**
 * Close multiple positions in parallel
 * Batch version of closePosition() that closes multiple positions simultaneously
 *
 * @param params - The operation parameters.
 * @returns The batch close results for each position.
 */
export type PerpsControllerClosePositionsAction = {
  type: `PerpsController:closePositions`;
  handler: PerpsController['closePositions'];
};

/**
 * Withdraw funds from trading account
 *
 * The withdrawal process varies by provider and may involve:
 * - Direct on-chain transfers
 * - Bridge operations
 * - Multi-step validation processes
 *
 * Check the specific provider documentation for detailed withdrawal flows.
 *
 * @param params Withdrawal parameters
 * @returns WithdrawResult with withdrawal ID and tracking info
 */
export type PerpsControllerWithdrawAction = {
  type: `PerpsController:withdraw`;
  handler: PerpsController['withdraw'];
};

/**
 * Get current positions
 * Thin delegation to MarketDataService
 *
 * For standalone mode, bypasses getActiveProvider() to allow position queries
 * without full perps initialization (e.g., for showing positions on token details page)
 *
 * @param params - The operation parameters.
 * @returns Array of open positions for the active provider.
 */
export type PerpsControllerGetPositionsAction = {
  type: `PerpsController:getPositions`;
  handler: PerpsController['getPositions'];
};

/**
 * Get historical user fills (trade executions)
 * Thin delegation to MarketDataService
 *
 * @param params - The operation parameters.
 * @returns Array of historical trade executions (fills).
 */
export type PerpsControllerGetOrderFillsAction = {
  type: `PerpsController:getOrderFills`;
  handler: PerpsController['getOrderFills'];
};

/**
 * Get historical user orders (order lifecycle)
 * Thin delegation to MarketDataService
 *
 * @param params - The operation parameters.
 * @returns Array of historical orders.
 */
export type PerpsControllerGetOrdersAction = {
  type: `PerpsController:getOrders`;
  handler: PerpsController['getOrders'];
};

/**
 * Get currently open orders (real-time status)
 * Thin delegation to MarketDataService
 *
 * For standalone mode, bypasses getActiveProvider() to allow open order queries
 * without full perps initialization (e.g., for background preloading)
 *
 * @param params - The operation parameters.
 * @returns A promise that resolves to the result.
 */
export type PerpsControllerGetOpenOrdersAction = {
  type: `PerpsController:getOpenOrders`;
  handler: PerpsController['getOpenOrders'];
};

/**
 * Get historical user funding history (funding payments)
 * Thin delegation to MarketDataService
 *
 * @param params - The operation parameters.
 * @returns Array of historical funding payments.
 */
export type PerpsControllerGetFundingAction = {
  type: `PerpsController:getFunding`;
  handler: PerpsController['getFunding'];
};

/**
 * Get account state (balances, etc.)
 * Thin delegation to MarketDataService
 *
 * For standalone mode, bypasses getActiveProvider() to allow account state queries
 * without full perps initialization (e.g., for checking if user has perps funds)
 *
 * @param params - The operation parameters.
 * @returns A promise that resolves to the result.
 */
export type PerpsControllerGetAccountStateAction = {
  type: `PerpsController:getAccountState`;
  handler: PerpsController['getAccountState'];
};

/**
 * Get historical portfolio data
 * Thin delegation to MarketDataService
 *
 * @param params - The operation parameters.
 * @returns The historical portfolio data points.
 */
export type PerpsControllerGetHistoricalPortfolioAction = {
  type: `PerpsController:getHistoricalPortfolio`;
  handler: PerpsController['getHistoricalPortfolio'];
};

/**
 * Get available markets with optional filtering
 * Thin delegation to MarketDataService
 *
 * For standalone mode, bypasses getActiveProvider() to allow market discovery
 * without full perps initialization (e.g., for discovery banners on spot screens)
 *
 * @param params - The operation parameters.
 * @returns Array of available markets matching the filter criteria.
 */
export type PerpsControllerGetMarketsAction = {
  type: `PerpsController:getMarkets`;
  handler: PerpsController['getMarkets'];
};

/**
 * Toggle between testnet and mainnet
 *
 * @returns The toggle result with success status and current network mode.
 */
export type PerpsControllerToggleTestnetAction = {
  type: `PerpsController:toggleTestnet`;
  handler: PerpsController['toggleTestnet'];
};

/**
 * Calculate trading fees for the active provider
 * Each provider implements its own fee structure
 *
 * @param params - The operation parameters.
 * @returns The fee calculation result for the trade.
 */
export type PerpsControllerCalculateFeesAction = {
  type: `PerpsController:calculateFees`;
  handler: PerpsController['calculateFees'];
};

/**
 * Disconnect provider and cleanup subscriptions
 * Call this when navigating away from Perps screens to prevent battery drain
 */
export type PerpsControllerDisconnectAction = {
  type: `PerpsController:disconnect`;
  handler: PerpsController['disconnect'];
};

/**
 * Refresh eligibility status
 */
export type PerpsControllerRefreshEligibilityAction = {
  type: `PerpsController:refreshEligibility`;
  handler: PerpsController['refreshEligibility'];
};

/**
 * Mark that the user has completed the tutorial/onboarding
 * This prevents the tutorial from showing again
 */
export type PerpsControllerMarkTutorialCompletedAction = {
  type: `PerpsController:markTutorialCompleted`;
  handler: PerpsController['markTutorialCompleted'];
};

export type PerpsControllerMarkFirstOrderCompletedAction = {
  type: `PerpsController:markFirstOrderCompleted`;
  handler: PerpsController['markFirstOrderCompleted'];
};

/**
 * Reset first-time user state for both networks
 * This is useful for testing the tutorial flow
 * Called by Reset Account feature in settings
 */
export type PerpsControllerResetFirstTimeUserStateAction = {
  type: `PerpsController:resetFirstTimeUserState`;
  handler: PerpsController['resetFirstTimeUserState'];
};

/**
 * Clear pending/bridging withdrawal and deposit requests
 * This is useful when users want to clear stuck pending indicators
 * Called by Reset Account feature in settings
 */
export type PerpsControllerClearPendingTransactionRequestsAction = {
  type: `PerpsController:clearPendingTransactionRequests`;
  handler: PerpsController['clearPendingTransactionRequests'];
};

/**
 * Get saved trade configuration for a market
 *
 * @param symbol - The trading pair symbol.
 * @returns The resulting string value.
 */
export type PerpsControllerGetTradeConfigurationAction = {
  type: `PerpsController:getTradeConfiguration`;
  handler: PerpsController['getTradeConfiguration'];
};

/**
 * Save trade configuration for a market
 *
 * @param symbol - Market symbol
 * @param leverage - Leverage value
 */
export type PerpsControllerSaveTradeConfigurationAction = {
  type: `PerpsController:saveTradeConfiguration`;
  handler: PerpsController['saveTradeConfiguration'];
};

/**
 * Save pending trade configuration for a market
 * This is a temporary configuration that expires after 5 minutes
 *
 * @param symbol - Market symbol
 * @param config - Pending trade configuration (includes optional selected payment token from Pay row)
 * @param config.amount - The amount value.
 * @param config.leverage - The leverage multiplier.
 * @param config.takeProfitPrice - The take profit price.
 * @param config.stopLossPrice - The stop loss price.
 * @param config.limitPrice - The limit price.
 * @param config.orderType - The order type.
 * @param config.selectedPaymentToken - The selected payment token.
 */
export type PerpsControllerSavePendingTradeConfigurationAction = {
  type: `PerpsController:savePendingTradeConfiguration`;
  handler: PerpsController['savePendingTradeConfiguration'];
};

/**
 * Get pending trade configuration for a market
 * Returns undefined if config doesn't exist or has expired (more than 5 minutes old)
 *
 * @param symbol - Market symbol
 * @returns Pending trade configuration or undefined
 */
export type PerpsControllerGetPendingTradeConfigurationAction = {
  type: `PerpsController:getPendingTradeConfiguration`;
  handler: PerpsController['getPendingTradeConfiguration'];
};

/**
 * Clear pending trade configuration for a market
 *
 * @param symbol - Market symbol
 */
export type PerpsControllerClearPendingTradeConfigurationAction = {
  type: `PerpsController:clearPendingTradeConfiguration`;
  handler: PerpsController['clearPendingTradeConfiguration'];
};

/**
 * Get saved market filter preferences
 * Handles backward compatibility with legacy string format
 *
 * @returns The saved sort option ID and direction.
 */
export type PerpsControllerGetMarketFilterPreferencesAction = {
  type: `PerpsController:getMarketFilterPreferences`;
  handler: PerpsController['getMarketFilterPreferences'];
};

/**
 * Save market filter preferences
 *
 * @param optionId - Sort/filter option ID
 * @param direction - Sort direction ('asc' or 'desc')
 */
export type PerpsControllerSaveMarketFilterPreferencesAction = {
  type: `PerpsController:saveMarketFilterPreferences`;
  handler: PerpsController['saveMarketFilterPreferences'];
};

/**
 * Set the selected payment token for the Perps order/deposit flow.
 * Pass null or a token with description PERPS_CONSTANTS.PerpsBalanceTokenDescription to select Perps balance.
 * Only required fields (address, chainId) are stored in state; description and symbol are optional.
 *
 * @param token - The token identifier.
 */
export type PerpsControllerSetSelectedPaymentTokenAction = {
  type: `PerpsController:setSelectedPaymentToken`;
  handler: PerpsController['setSelectedPaymentToken'];
};

/**
 * Reset the selected payment token to Perps balance (null).
 * Call when leaving the Perps order view so the next visit defaults to Perps balance.
 */
export type PerpsControllerResetSelectedPaymentTokenAction = {
  type: `PerpsController:resetSelectedPaymentToken`;
  handler: PerpsController['resetSelectedPaymentToken'];
};

/**
 * Get saved order book grouping for a market
 *
 * @param symbol - Market symbol
 * @returns The saved grouping value or undefined if not set
 */
export type PerpsControllerGetOrderBookGroupingAction = {
  type: `PerpsController:getOrderBookGrouping`;
  handler: PerpsController['getOrderBookGrouping'];
};

/**
 * Save order book grouping for a market
 *
 * @param symbol - Market symbol
 * @param grouping - Price grouping value
 */
export type PerpsControllerSaveOrderBookGroupingAction = {
  type: `PerpsController:saveOrderBookGrouping`;
  handler: PerpsController['saveOrderBookGrouping'];
};

/**
 * Union of all PerpsController action types.
 */
export type PerpsControllerMethodActions =
  | PerpsControllerPlaceOrderAction
  | PerpsControllerEditOrderAction
  | PerpsControllerCancelOrderAction
  | PerpsControllerCancelOrdersAction
  | PerpsControllerClosePositionAction
  | PerpsControllerClosePositionsAction
  | PerpsControllerWithdrawAction
  | PerpsControllerGetPositionsAction
  | PerpsControllerGetOrderFillsAction
  | PerpsControllerGetOrdersAction
  | PerpsControllerGetOpenOrdersAction
  | PerpsControllerGetFundingAction
  | PerpsControllerGetAccountStateAction
  | PerpsControllerGetHistoricalPortfolioAction
  | PerpsControllerGetMarketsAction
  | PerpsControllerToggleTestnetAction
  | PerpsControllerCalculateFeesAction
  | PerpsControllerDisconnectAction
  | PerpsControllerRefreshEligibilityAction
  | PerpsControllerMarkTutorialCompletedAction
  | PerpsControllerMarkFirstOrderCompletedAction
  | PerpsControllerResetFirstTimeUserStateAction
  | PerpsControllerClearPendingTransactionRequestsAction
  | PerpsControllerGetTradeConfigurationAction
  | PerpsControllerSaveTradeConfigurationAction
  | PerpsControllerSavePendingTradeConfigurationAction
  | PerpsControllerGetPendingTradeConfigurationAction
  | PerpsControllerClearPendingTradeConfigurationAction
  | PerpsControllerGetMarketFilterPreferencesAction
  | PerpsControllerSaveMarketFilterPreferencesAction
  | PerpsControllerSetSelectedPaymentTokenAction
  | PerpsControllerResetSelectedPaymentTokenAction
  | PerpsControllerGetOrderBookGroupingAction
  | PerpsControllerSaveOrderBookGroupingAction;
