/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { SignatureController } from './SignatureController';

/**
 * Reset the controller state to the initial state.
 */
export type SignatureControllerResetStateAction = {
  type: `SignatureController:resetState`;
  handler: SignatureController['resetState'];
};

/**
 * Reject all unapproved messages of any type.
 *
 * @param reason - A message to indicate why.
 */
export type SignatureControllerRejectUnapprovedAction = {
  type: `SignatureController:rejectUnapproved`;
  handler: SignatureController['rejectUnapproved'];
};

/**
 * Clears all unapproved messages from memory.
 */
export type SignatureControllerClearUnapprovedAction = {
  type: `SignatureController:clearUnapproved`;
  handler: SignatureController['clearUnapproved'];
};

/**
 * Called when a dApp uses the personal_sign method.
 * We currently provide personal_sign mostly for legacy dApps.
 *
 * @param messageParams - The params of the message to sign and return to the dApp.
 * @param request - The original request, containing the origin.
 * @param options - An options bag for the method.
 * @param options.traceContext - The parent context for any new traces.
 * @returns Promise resolving to the raw signature hash generated from the signature request.
 */
export type SignatureControllerNewUnsignedPersonalMessageAction = {
  type: `SignatureController:newUnsignedPersonalMessage`;
  handler: SignatureController['newUnsignedPersonalMessage'];
};

/**
 * Called when a dapp uses the eth_signTypedData method, per EIP-712.
 *
 * @param messageParams - The params of the message to sign and return to the dApp.
 * @param request - The original request, containing the origin.
 * @param versionString - The version of the signTypedData request.
 * @param signingOptions - Options for signing the typed message.
 * @param options - An options bag for the method.
 * @param options.traceContext - The parent context for any new traces.
 * @returns Promise resolving to the raw signature hash generated from the signature request.
 */
export type SignatureControllerNewUnsignedTypedMessageAction = {
  type: `SignatureController:newUnsignedTypedMessage`;
  handler: SignatureController['newUnsignedTypedMessage'];
};

/**
 * Provide a signature for a pending signature request that used `deferSetAsSigned`.
 * Changes the status of the signature request to `signed`.
 *
 * @param signatureRequestId - The ID of the signature request.
 * @param signature - The signature to provide.
 */
export type SignatureControllerSetDeferredSignSuccessAction = {
  type: `SignatureController:setDeferredSignSuccess`;
  handler: SignatureController['setDeferredSignSuccess'];
};

/**
 * Set custom metadata on a signature request.
 *
 * @param signatureRequestId - The ID of the signature request.
 * @param metadata - The custom metadata to set.
 */
export type SignatureControllerSetMessageMetadataAction = {
  type: `SignatureController:setMessageMetadata`;
  handler: SignatureController['setMessageMetadata'];
};

/**
 * Reject a pending signature request that used `deferSetAsSigned`.
 * Changes the status of the signature request to `rejected`.
 *
 * @param signatureRequestId - The ID of the signature request.
 */
export type SignatureControllerSetDeferredSignErrorAction = {
  type: `SignatureController:setDeferredSignError`;
  handler: SignatureController['setDeferredSignError'];
};

/**
 * Set the status of a signature request to 'inProgress'.
 *
 * @param signatureRequestId - The ID of the signature request.
 */
export type SignatureControllerSetTypedMessageInProgressAction = {
  type: `SignatureController:setTypedMessageInProgress`;
  handler: SignatureController['setTypedMessageInProgress'];
};

/**
 * Set the status of a signature request to 'inProgress'.
 *
 * @param signatureRequestId - The ID of the signature request.
 */
export type SignatureControllerSetPersonalMessageInProgressAction = {
  type: `SignatureController:setPersonalMessageInProgress`;
  handler: SignatureController['setPersonalMessageInProgress'];
};

/**
 * Union of all SignatureController action types.
 */
export type SignatureControllerMethodActions =
  | SignatureControllerResetStateAction
  | SignatureControllerRejectUnapprovedAction
  | SignatureControllerClearUnapprovedAction
  | SignatureControllerNewUnsignedPersonalMessageAction
  | SignatureControllerNewUnsignedTypedMessageAction
  | SignatureControllerSetDeferredSignSuccessAction
  | SignatureControllerSetMessageMetadataAction
  | SignatureControllerSetDeferredSignErrorAction
  | SignatureControllerSetTypedMessageInProgressAction
  | SignatureControllerSetPersonalMessageInProgressAction;
