/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { SampleGasPricesService } from './sample-gas-prices-service';

/**
 * Fetches the latest gas prices for the given chain and persists them to
 * state.
 *
 * @param args - The arguments to the function.
 * @param args.chainId - The chain ID for which to fetch gas prices.
 */
export type SampleGasPricesServiceFetchGasPricesAction = {
  type: `SampleGasPricesService:fetchGasPrices`;
  handler: SampleGasPricesService['fetchGasPrices'];
};

/**
 * Union of all SampleGasPricesService action types.
 */
export type SampleGasPricesServiceMethodActions =
  SampleGasPricesServiceFetchGasPricesAction;
