/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { AuthenticationController } from './AuthenticationController';

export type AuthenticationControllerPerformSignInAction = {
  type: `AuthenticationController:performSignIn`;
  handler: AuthenticationController['performSignIn'];
};

export type AuthenticationControllerPerformSignOutAction = {
  type: `AuthenticationController:performSignOut`;
  handler: AuthenticationController['performSignOut'];
};

/**
 * Will return a bearer token.
 * Logs a user in if a user is not logged in.
 *
 * @returns profile for the session.
 */
export type AuthenticationControllerGetBearerTokenAction = {
  type: `AuthenticationController:getBearerToken`;
  handler: AuthenticationController['getBearerToken'];
};

/**
 * Will return a session profile.
 * Logs a user in if a user is not logged in.
 *
 * @param entropySourceId - The entropy source ID used to derive the key,
 * when multiple sources are available (Multi-SRP).
 * @returns profile for the session.
 */
export type AuthenticationControllerGetSessionProfileAction = {
  type: `AuthenticationController:getSessionProfile`;
  handler: AuthenticationController['getSessionProfile'];
};

export type AuthenticationControllerGetUserProfileLineageAction = {
  type: `AuthenticationController:getUserProfileLineage`;
  handler: AuthenticationController['getUserProfileLineage'];
};

export type AuthenticationControllerIsSignedInAction = {
  type: `AuthenticationController:isSignedIn`;
  handler: AuthenticationController['isSignedIn'];
};

/**
 * Union of all AuthenticationController action types.
 */
export type AuthenticationControllerMethodActions =
  | AuthenticationControllerPerformSignInAction
  | AuthenticationControllerPerformSignOutAction
  | AuthenticationControllerGetBearerTokenAction
  | AuthenticationControllerGetSessionProfileAction
  | AuthenticationControllerGetUserProfileLineageAction
  | AuthenticationControllerIsSignedInAction;
