import {
  selectDerivationMethod,
  deriveWrappingKey,
  wrapKey,
  unwrapKey,
  arrayBufferToBase64,
  base64ToArrayBuffer,
} from './crypto';
import type {
  PasskeyRecord,
  CredentialCreationResult,
  AssertionResult,
  CreationParams,
  AssertionParams,
} from './types';

/**
 * Generate random userHandle (64 bytes) and prfSalt (32 bytes) for passkey creation.
 *
 * @returns Creation params for the platform ceremony adapter.
 */
export function prepareCreationParams(): CreationParams {
  return {
    userHandle: globalThis.crypto.getRandomValues(new Uint8Array(64)),
    prfSalt: globalThis.crypto.getRandomValues(new Uint8Array(32)),
  };
}

/**
 * After passkey ceremony: derive wrapping key, wrap the vault encryption key, build record.
 *
 * @param encryptionKey - Serialized vault encryption key from KeyringController.exportEncryptionKey()
 * @param encryptionSalt - Vault salt (from KeyringController state or vault JSON)
 * @param ceremonyResult - Normalized output from the platform ceremony adapter
 * @param prfSalt - PRF salt generated by prepareCreationParams()
 * @returns PasskeyRecord to persist via PasskeyController.setPasskeyRecord()
 */
export async function buildPasskeyRecord(
  encryptionKey: string,
  encryptionSalt: string,
  ceremonyResult: CredentialCreationResult,
  prfSalt: Uint8Array,
): Promise<PasskeyRecord> {
  const derivationMethod = selectDerivationMethod(ceremonyResult);

  const ikm: ArrayBuffer =
    derivationMethod === 'prf' && ceremonyResult.prfFirst
      ? ceremonyResult.prfFirst
      : (ceremonyResult.userHandle.buffer as ArrayBuffer);

  const wrappingKey = await deriveWrappingKey(
    ikm,
    ceremonyResult.credentialId.buffer as ArrayBuffer,
  );
  const { ciphertext, iv } = await wrapKey(encryptionKey, wrappingKey);

  const record: PasskeyRecord = {
    credentialId: arrayBufferToBase64(
      ceremonyResult.credentialId.buffer as ArrayBuffer,
    ),
    derivationMethod,
    wrappedEncryptionKey: ciphertext,
    iv,
    encryptionSalt,
  };

  if (derivationMethod === 'prf') {
    record.prfSalt = arrayBufferToBase64(prfSalt.buffer as ArrayBuffer);
  }

  return record;
}

/**
 * Before unlock ceremony: extract params from stored record.
 *
 * @param record - Stored PasskeyRecord
 * @returns Params for the platform ceremony adapter's getAssertion()
 */
export function prepareAssertionParams(record: PasskeyRecord): AssertionParams {
  const credentialId = new Uint8Array(base64ToArrayBuffer(record.credentialId));
  return {
    credentialId,
    prfSalt: record.prfSalt
      ? new Uint8Array(base64ToArrayBuffer(record.prfSalt))
      : undefined,
    usePrf: record.derivationMethod === 'prf',
  };
}

/**
 * After passkey assertion: derive wrapping key, unwrap the vault encryption key.
 *
 * @param record - Stored PasskeyRecord
 * @param assertionResult - Normalized output from the platform ceremony adapter
 * @returns The serialized vault encryption key (pass to submitEncryptionKey)
 */
export async function unwrapEncryptionKeyFromAssertion(
  record: PasskeyRecord,
  assertionResult: AssertionResult,
): Promise<string> {
  let ikm: ArrayBuffer;

  if (record.derivationMethod === 'prf' && assertionResult.prfFirst) {
    ikm = assertionResult.prfFirst;
  } else if (assertionResult.userHandle) {
    ikm = assertionResult.userHandle;
  } else {
    throw new Error('Passkey assertion missing required key material');
  }

  const credentialIdBytes = new Uint8Array(
    base64ToArrayBuffer(record.credentialId),
  );
  const wrappingKey = await deriveWrappingKey(
    ikm,
    credentialIdBytes.buffer as ArrayBuffer,
  );
  return unwrapKey(record.wrappedEncryptionKey, record.iv, wrappingKey);
}
