import * as indexModule from '.';

describe('index module', () => {
  it('has expected JavaScript exports', () => {
    expect(indexModule).toMatchInlineSnapshot(`
      Object {
        "GetGrantedExecutionPermissionsResultStruct": Struct {
          "coercer": [Function],
          "entries": [Function],
          "refiner": [Function],
          "schema": Struct {
            "coercer": [Function],
            "entries": [Function],
            "refiner": [Function],
            "schema": Object {
              "chainId": Struct {
                "coercer": [Function],
                "entries": [Function],
                "refiner": [Function],
                "schema": null,
                "type": "string",
                "validator": [Function],
              },
              "context": Struct {
                "coercer": [Function],
                "entries": [Function],
                "refiner": [Function],
                "schema": null,
                "type": "string",
                "validator": [Function],
              },
              "delegationManager": Struct {
                "coercer": [Function],
                "entries": [Function],
                "refiner": [Function],
                "schema": null,
                "type": "string",
                "validator": [Function],
              },
              "dependencies": Struct {
                "coercer": [Function],
                "entries": [Function],
                "refiner": [Function],
                "schema": Struct {
                  "coercer": [Function],
                  "entries": [Function],
                  "refiner": [Function],
                  "schema": Object {
                    "factory": Struct {
                      "coercer": [Function],
                      "entries": [Function],
                      "refiner": [Function],
                      "schema": null,
                      "type": "string",
                      "validator": [Function],
                    },
                    "factoryData": Struct {
                      "coercer": [Function],
                      "entries": [Function],
                      "refiner": [Function],
                      "schema": null,
                      "type": "string",
                      "validator": [Function],
                    },
                  },
                  "type": "object",
                  "validator": [Function],
                },
                "type": "array",
                "validator": [Function],
              },
              "from": Struct {
                "coercer": [Function],
                "entries": [Function],
                "refiner": [Function],
                "schema": null,
                "type": "string",
                "validator": [Function],
              },
              "permission": Struct {
                "coercer": [Function],
                "entries": [Function],
                "refiner": [Function],
                "schema": Object {
                  "data": Struct {
                    "coercer": [Function],
                    "entries": [Function],
                    "refiner": [Function],
                    "schema": null,
                    "type": "record",
                    "validator": [Function],
                  },
                  "isAdjustmentAllowed": Struct {
                    "coercer": [Function],
                    "entries": [Function],
                    "refiner": [Function],
                    "schema": null,
                    "type": "boolean",
                    "validator": [Function],
                  },
                  "type": Struct {
                    "coercer": [Function],
                    "entries": [Function],
                    "refiner": [Function],
                    "schema": null,
                    "type": "string",
                    "validator": [Function],
                  },
                },
                "type": "object",
                "validator": [Function],
              },
              "to": Struct {
                "coercer": [Function],
                "entries": [Function],
                "refiner": [Function],
                "schema": null,
                "type": "string",
                "validator": [Function],
              },
            },
            "type": "object",
            "validator": [Function],
          },
          "type": "array",
          "validator": [Function],
        },
        "GetSupportedExecutionPermissionsResultStruct": Struct {
          "coercer": [Function],
          "entries": [Function],
          "refiner": [Function],
          "schema": null,
          "type": "record",
          "validator": [Function],
        },
        "GrantedExecutionPermissionStruct": Struct {
          "coercer": [Function],
          "entries": [Function],
          "refiner": [Function],
          "schema": Object {
            "chainId": Struct {
              "coercer": [Function],
              "entries": [Function],
              "refiner": [Function],
              "schema": null,
              "type": "string",
              "validator": [Function],
            },
            "context": Struct {
              "coercer": [Function],
              "entries": [Function],
              "refiner": [Function],
              "schema": null,
              "type": "string",
              "validator": [Function],
            },
            "delegationManager": Struct {
              "coercer": [Function],
              "entries": [Function],
              "refiner": [Function],
              "schema": null,
              "type": "string",
              "validator": [Function],
            },
            "dependencies": Struct {
              "coercer": [Function],
              "entries": [Function],
              "refiner": [Function],
              "schema": Struct {
                "coercer": [Function],
                "entries": [Function],
                "refiner": [Function],
                "schema": Object {
                  "factory": Struct {
                    "coercer": [Function],
                    "entries": [Function],
                    "refiner": [Function],
                    "schema": null,
                    "type": "string",
                    "validator": [Function],
                  },
                  "factoryData": Struct {
                    "coercer": [Function],
                    "entries": [Function],
                    "refiner": [Function],
                    "schema": null,
                    "type": "string",
                    "validator": [Function],
                  },
                },
                "type": "object",
                "validator": [Function],
              },
              "type": "array",
              "validator": [Function],
            },
            "from": Struct {
              "coercer": [Function],
              "entries": [Function],
              "refiner": [Function],
              "schema": null,
              "type": "string",
              "validator": [Function],
            },
            "permission": Struct {
              "coercer": [Function],
              "entries": [Function],
              "refiner": [Function],
              "schema": Object {
                "data": Struct {
                  "coercer": [Function],
                  "entries": [Function],
                  "refiner": [Function],
                  "schema": null,
                  "type": "record",
                  "validator": [Function],
                },
                "isAdjustmentAllowed": Struct {
                  "coercer": [Function],
                  "entries": [Function],
                  "refiner": [Function],
                  "schema": null,
                  "type": "boolean",
                  "validator": [Function],
                },
                "type": Struct {
                  "coercer": [Function],
                  "entries": [Function],
                  "refiner": [Function],
                  "schema": null,
                  "type": "string",
                  "validator": [Function],
                },
              },
              "type": "object",
              "validator": [Function],
            },
            "to": Struct {
              "coercer": [Function],
              "entries": [Function],
              "refiner": [Function],
              "schema": null,
              "type": "string",
              "validator": [Function],
            },
          },
          "type": "object",
          "validator": [Function],
        },
        "SupportedExecutionPermissionConfigStruct": Struct {
          "coercer": [Function],
          "entries": [Function],
          "refiner": [Function],
          "schema": Object {
            "chainIds": Struct {
              "coercer": [Function],
              "entries": [Function],
              "refiner": [Function],
              "schema": Struct {
                "coercer": [Function],
                "entries": [Function],
                "refiner": [Function],
                "schema": null,
                "type": "string",
                "validator": [Function],
              },
              "type": "array",
              "validator": [Function],
            },
            "ruleTypes": Struct {
              "coercer": [Function],
              "entries": [Function],
              "refiner": [Function],
              "schema": Struct {
                "coercer": [Function],
                "entries": [Function],
                "refiner": [Function],
                "schema": null,
                "type": "string",
                "validator": [Function],
              },
              "type": "array",
              "validator": [Function],
            },
          },
          "type": "object",
          "validator": [Function],
        },
        "createBlockCacheMiddleware": [Function],
        "createBlockRefMiddleware": [Function],
        "createBlockRefRewriteMiddleware": [Function],
        "createBlockTrackerInspectorMiddleware": [Function],
        "createFetchMiddleware": [Function],
        "createInflightCacheMiddleware": [Function],
        "createRetryOnEmptyMiddleware": [Function],
        "createWalletMiddleware": [Function],
        "providerAsMiddleware": [Function],
        "providerAsMiddlewareV2": [Function],
      }
    `);
  });
});
