/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { AnalyticsController } from './AnalyticsController';

/**
 * Track an analytics event.
 *
 * Events are only tracked if analytics is enabled.
 *
 * @param event - Analytics event with properties and sensitive properties
 */
export type AnalyticsControllerTrackEventAction = {
  type: `AnalyticsController:trackEvent`;
  handler: AnalyticsController['trackEvent'];
};

/**
 * Identify a user for analytics.
 *
 * @param traits - User traits/properties
 */
export type AnalyticsControllerIdentifyAction = {
  type: `AnalyticsController:identify`;
  handler: AnalyticsController['identify'];
};

/**
 * Track a page view.
 *
 * @param name - The name of the UI item being viewed (pages for web, screen for mobile)
 * @param properties - UI item properties
 */
export type AnalyticsControllerTrackViewAction = {
  type: `AnalyticsController:trackView`;
  handler: AnalyticsController['trackView'];
};

/**
 * Opt in to analytics for regular account.
 * This updates the user's opt-in status for regular account.
 */
export type AnalyticsControllerOptInForRegularAccountAction = {
  type: `AnalyticsController:optInForRegularAccount`;
  handler: AnalyticsController['optInForRegularAccount'];
};

/**
 * Opt out of analytics for regular account.
 * This updates the user's opt-in status for regular account.
 */
export type AnalyticsControllerOptOutForRegularAccountAction = {
  type: `AnalyticsController:optOutForRegularAccount`;
  handler: AnalyticsController['optOutForRegularAccount'];
};

/**
 * Opt in to analytics for social account.
 * This updates the user's opt-in status for social account.
 */
export type AnalyticsControllerOptInForSocialAccountAction = {
  type: `AnalyticsController:optInForSocialAccount`;
  handler: AnalyticsController['optInForSocialAccount'];
};

/**
 * Opt out of analytics for social account.
 * This updates the user's opt-in status for social account.
 */
export type AnalyticsControllerOptOutForSocialAccountAction = {
  type: `AnalyticsController:optOutForSocialAccount`;
  handler: AnalyticsController['optOutForSocialAccount'];
};

/**
 * Union of all AnalyticsController action types.
 */
export type AnalyticsControllerMethodActions =
  | AnalyticsControllerTrackEventAction
  | AnalyticsControllerIdentifyAction
  | AnalyticsControllerTrackViewAction
  | AnalyticsControllerOptInForRegularAccountAction
  | AnalyticsControllerOptOutForRegularAccountAction
  | AnalyticsControllerOptInForSocialAccountAction
  | AnalyticsControllerOptOutForSocialAccountAction;
