/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { AnalyticsController } from './AnalyticsController';

/**
 * Track an analytics event.
 *
 * Events are only tracked if analytics is enabled.
 *
 * @param eventName - The name of the event
 * @param properties - Event properties
 */
export type AnalyticsControllerTrackEventAction = {
  type: `AnalyticsController:trackEvent`;
  handler: AnalyticsController['trackEvent'];
};

/**
 * Identify a user for analytics.
 *
 * @param traits - User traits/properties
 */
export type AnalyticsControllerIdentifyAction = {
  type: `AnalyticsController:identify`;
  handler: AnalyticsController['identify'];
};

/**
 * Track a page view.
 *
 * @param name - The name of the UI item being viewed (pages for web, screen for mobile)
 * @param properties - UI item properties
 */
export type AnalyticsControllerTrackViewAction = {
  type: `AnalyticsController:trackView`;
  handler: AnalyticsController['trackView'];
};

/**
 * Opt in to analytics.
 * This updates the user's opt-in status.
 */
export type AnalyticsControllerOptInAction = {
  type: `AnalyticsController:optIn`;
  handler: AnalyticsController['optIn'];
};

/**
 * Opt out of analytics.
 * This updates the user's opt-in status.
 */
export type AnalyticsControllerOptOutAction = {
  type: `AnalyticsController:optOut`;
  handler: AnalyticsController['optOut'];
};

/**
 * Opt in to analytics through social account.
 * This updates the user's social opt-in status.
 */
export type AnalyticsControllerSocialOptInAction = {
  type: `AnalyticsController:socialOptIn`;
  handler: AnalyticsController['socialOptIn'];
};

/**
 * Opt out of analytics through social account.
 * This updates the user's social opt-in status.
 */
export type AnalyticsControllerSocialOptOutAction = {
  type: `AnalyticsController:socialOptOut`;
  handler: AnalyticsController['socialOptOut'];
};

/**
 * Get the analytics ID from the controller state.
 *
 * @returns The current analytics ID.
 */
export type AnalyticsControllerGetAnalyticsIdAction = {
  type: `AnalyticsController:getAnalyticsId`;
  handler: AnalyticsController['getAnalyticsId'];
};

/**
 * Get the enabled status from the controller state.
 * This is computed from user state via the state machine.
 *
 * @returns The current enabled status.
 */
export type AnalyticsControllerIsEnabledAction = {
  type: `AnalyticsController:isEnabled`;
  handler: AnalyticsController['isEnabled'];
};

/**
 * Get the opted in status from the controller state.
 *
 * @returns The current opted in status.
 */
export type AnalyticsControllerIsOptedInAction = {
  type: `AnalyticsController:isOptedIn`;
  handler: AnalyticsController['isOptedIn'];
};

/**
 * Get the social opted in status from the controller state.
 *
 * @returns The current social opted in status.
 */
export type AnalyticsControllerIsSocialOptedInAction = {
  type: `AnalyticsController:isSocialOptedIn`;
  handler: AnalyticsController['isSocialOptedIn'];
};

/**
 * Union of all AnalyticsController action types.
 */
export type AnalyticsControllerMethodActions =
  | AnalyticsControllerTrackEventAction
  | AnalyticsControllerIdentifyAction
  | AnalyticsControllerTrackViewAction
  | AnalyticsControllerOptInAction
  | AnalyticsControllerOptOutAction
  | AnalyticsControllerSocialOptInAction
  | AnalyticsControllerSocialOptOutAction
  | AnalyticsControllerGetAnalyticsIdAction
  | AnalyticsControllerIsEnabledAction
  | AnalyticsControllerIsOptedInAction
  | AnalyticsControllerIsSocialOptedInAction;
