/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { AnalyticsController } from './AnalyticsController';

/**
 * Track an analytics event.
 *
 * Events are only tracked if analytics is enabled.
 *
 * @param eventName - The name of the event
 * @param properties - Event properties
 */
export type AnalyticsControllerTrackEventAction = {
  type: `AnalyticsController:trackEvent`;
  handler: AnalyticsController['trackEvent'];
};

/**
 * Identify a user for analytics.
 *
 * @param userId - The user identifier (e.g., metametrics ID)
 * @param traits - User traits/properties
 */
export type AnalyticsControllerIdentifyAction = {
  type: `AnalyticsController:identify`;
  handler: AnalyticsController['identify'];
};

/**
 * Track a page view.
 *
 * @param pageName - The name of the page
 * @param properties - Page properties
 */
export type AnalyticsControllerTrackPageAction = {
  type: `AnalyticsController:trackPage`;
  handler: AnalyticsController['trackPage'];
};

/**
 * Enable analytics tracking.
 */
export type AnalyticsControllerEnableAction = {
  type: `AnalyticsController:enable`;
  handler: AnalyticsController['enable'];
};

/**
 * Disable analytics tracking.
 */
export type AnalyticsControllerDisableAction = {
  type: `AnalyticsController:disable`;
  handler: AnalyticsController['disable'];
};

/**
 * Opt in to analytics.
 */
export type AnalyticsControllerOptInAction = {
  type: `AnalyticsController:optIn`;
  handler: AnalyticsController['optIn'];
};

/**
 * Opt out of analytics.
 */
export type AnalyticsControllerOptOutAction = {
  type: `AnalyticsController:optOut`;
  handler: AnalyticsController['optOut'];
};

/**
 * Union of all AnalyticsController action types.
 */
export type AnalyticsControllerMethodActions =
  | AnalyticsControllerTrackEventAction
  | AnalyticsControllerIdentifyAction
  | AnalyticsControllerTrackPageAction
  | AnalyticsControllerEnableAction
  | AnalyticsControllerDisableAction
  | AnalyticsControllerOptInAction
  | AnalyticsControllerOptOutAction;
