export const USER_STORAGE_FEATURE_PREFIX = 'multichain_accounts';

export const USER_STORAGE_WALLETS_FEATURE_KEY = `${USER_STORAGE_FEATURE_PREFIX}_wallets`;
export const USER_STORAGE_WALLETS_FEATURE_ENTRY_KEY = 'wallet';

export const USER_STORAGE_GROUPS_FEATURE_KEY = `${USER_STORAGE_FEATURE_PREFIX}_groups`;
