import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebar configuration for the MetaMask Core developer documentation site.
 *
 * Using `autogenerated` so that Docusaurus builds the sidebar automatically
 * from the directory structure under `docs/developers/`.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
