/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { SampleGasPricesController } from './sample-gas-prices-controller';

/**
 * Fetches the latest gas prices for the given chain and persists them to
 * state.
 *
 * @param args - The arguments to the function.
 * @param args.chainId - The chain ID for which to fetch gas prices.
 */
export type SampleGasPricesControllerUpdateGasPricesAction = {
  type: `SampleGasPricesController:updateGasPrices`;
  handler: SampleGasPricesController['updateGasPrices'];
};

/**
 * Union of all SampleGasPricesController action types.
 */
export type SampleGasPricesControllerMethodActions =
  SampleGasPricesControllerUpdateGasPricesAction;
