/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { SamplePetnamesController } from './sample-petnames-controller';

/**
 * Registers the given name with the given address (relative to the given
 * chain).
 *
 * @param chainId - The chain ID that the address belongs to.
 * @param address - The account address to name.
 * @param name - The name to assign to the address.
 */
export type SamplePetnamesControllerAssignPetnameAction = {
  type: `SamplePetnamesController:assignPetname`;
  handler: SamplePetnamesController['assignPetname'];
};

/**
 * Union of all SamplePetnamesController action types.
 */
export type SamplePetnamesControllerMethodActions =
  SamplePetnamesControllerAssignPetnameAction;
