/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { UserProfileService } from './user-profile-service';

/**
 * Makes a request to the API in order to update the user profile.
 *
 * @returns The response from the API.
 */
export type UserProfileServiceUpdateProfileAction = {
  type: `UserProfileService:updateProfile`;
  handler: UserProfileService['updateProfile'];
};

/**
 * Union of all UserProfileService action types.
 */
export type UserProfileServiceMethodActions =
  UserProfileServiceUpdateProfileAction;
