import * as path from 'node:path';

import type { ControllerInfo } from './parse-controller';

/**
 * Capitalizes the first letter of a string.
 *
 * @param str - The string to capitalize.
 * @returns The capitalized string.
 */
function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

/**
 * Generates the content for the action types file.
 *
 * @param controller - The controller information object.
 * @returns The content for the action types file.
 */
export function generateActionTypesContent(controller: ControllerInfo): string {
  const baseFileName = path.basename(controller.filePath, '.ts');
  const controllerImportPath = `./${baseFileName}`;

  let content = `/**
 * This file is auto generated by \`@metamask/messenger-generate-action-types\`.
 * Do not edit manually.
 */

import type { ${controller.name} } from '${controllerImportPath}';

`;

  const actionTypeNames: string[] = [];

  for (const method of controller.methods) {
    const actionTypeName = `${controller.name}${capitalize(method.name)}Action`;
    const actionString = `${controller.name}:${method.name}`;

    actionTypeNames.push(actionTypeName);

    if (method.jsDoc) {
      content += `${method.jsDoc}\n`;
    }

    content += `export type ${actionTypeName} = {
  type: \`${actionString}\`;
  handler: ${controller.name}['${method.name}'];
};\n\n`;
  }

  if (actionTypeNames.length > 0) {
    const unionTypeName = `${controller.name}MethodActions`;
    content += `/**
 * Union of all ${controller.name} action types.
 */
export type ${unionTypeName} = ${actionTypeNames.join(' | ')};\n`;
  }

  return `${content.trimEnd()}\n`;
}
