/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { MoneyAccountService } from './MoneyAccountService';

/**
 * Creates a Money keyring derived from the primary HD keyring, and returns
 * the associated account.
 *
 * If a Money keyring already exists, returns undefined.
 *
 * @returns The account of the newly created Money keyring, or undefined if one already existed.
 */
export type MoneyAccountServiceCreateMoneyAccountAction = {
  type: `MoneyAccountService:createMoneyAccount`;
  handler: MoneyAccountService['createMoneyAccount'];
};

/**
 * Returns the account associated with the Money keyring, or undefined if none exists.
 *
 * @returns The Money keyring account, or undefined if none exists.
 */
export type MoneyAccountServiceGetMoneyAccountAction = {
  type: `MoneyAccountService:getMoneyAccount`;
  handler: MoneyAccountService['getMoneyAccount'];
};

/**
 * Returns the account wallet associated with the Money keyring, or undefined if none exists.
 *
 * @returns The Money keyring account wallet, or undefined if none exists.
 */
export type MoneyAccountServiceGetMoneyAccountWalletAction = {
  type: `MoneyAccountService:getMoneyAccountWallet`;
  handler: MoneyAccountService['getMoneyAccountWallet'];
};

/**
 * Returns the account group associated with the Money keyring, or undefined if none exists.
 *
 * @returns The account group of the Money keyring, or undefined if none exists.
 */
export type MoneyAccountServiceGetMoneyAccountGroupAction = {
  type: `MoneyAccountService:getMoneyAccountGroup`;
  handler: MoneyAccountService['getMoneyAccountGroup'];
};

/**
 * Union of all MoneyAccountService action types.
 */
export type MoneyAccountServiceMethodActions =
  | MoneyAccountServiceCreateMoneyAccountAction
  | MoneyAccountServiceGetMoneyAccountAction
  | MoneyAccountServiceGetMoneyAccountWalletAction
  | MoneyAccountServiceGetMoneyAccountGroupAction;
