import type { KubbFile } from '@kubb/fabric-core/types';
import type { SchemaObject } from '@kubb/oas';
import type { OperationSchema } from '@kubb/plugin-oas';
import { createGenerator } from '@kubb/plugin-oas/generators';
import { getBanner, getFooter } from '@kubb/plugin-oas/utils';
import { pluginTsName } from '@kubb/plugin-ts';

import { pluginSuperstructName } from '../../kubb-plugin-superstruct';
import { camelCase, pascalCase } from '../../utils/casing';
import type { PluginQueryCore } from '../types';

/**
 * Returns whether an operation schema contains at least one required
 * property, which determines whether the generated parameter is required.
 *
 * @param schema - The raw OpenAPI schema of the operation parameters.
 * @returns Whether at least one property is required.
 */
function hasRequiredProperties(schema: SchemaObject | undefined): boolean {
  if (!schema) {
    return false;
  }
  const { required } = schema as { required?: string[] | boolean };
  if (Array.isArray(required)) {
    return required.length > 0;
  }
  return Boolean(required);
}

/**
 * Renders a property access, using dot notation when the property name is a
 * valid identifier and bracket notation otherwise.
 *
 * @param objectName - The name of the object being accessed.
 * @param propertyName - The property being accessed.
 * @returns The rendered property access.
 */
function accessProperty(objectName: string, propertyName: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(propertyName)
    ? `${objectName}.${propertyName}`
    : `${objectName}[${JSON.stringify(propertyName)}]`;
}

/**
 * Converts an OpenAPI path into either a string literal (no path parameters)
 * or a template literal that reads path parameters from a `pathParams`
 * object.
 *
 * @param operationPath - The OpenAPI path, e.g. `/v1/spot-prices/{coinId}`.
 * @returns The rendered URL expression.
 */
function renderUrl(operationPath: string): string {
  if (!operationPath.includes('{')) {
    return JSON.stringify(operationPath);
  }
  const template = operationPath.replace(
    /\{([^}]+)\}/gu,
    (_match, parameterName: string) =>
      `\${${accessProperty('pathParams', parameterName)}}`,
  );
  return `\`${template}\``;
}

/**
 * The resolved name and file of a generated artifact in another plugin, used
 * to build cross-plugin imports.
 */
type ResolvedSymbol = {
  name: string;
  path: KubbFile.Path;
};

/**
 * Generator that emits a TanStack `query-core` binding per operation:
 * a query key factory, a query options factory and a `fetch` convenience
 * function that validates the response against the generated
 * `@metamask/superstruct` struct.
 */
export const queryCoreGenerator = createGenerator<PluginQueryCore>({
  name: 'query-core',

  async operation({ operation, generator, config }) {
    const { pluginManager, plugin, mode, oas } = generator.context;
    const { queryKeyPrefix, runtimeImportPath } = plugin.options;

    const operationSchemas = generator.getSchemas(operation);
    const operationId = operation.getOperationId();
    const baseName = camelCase(operationId);

    const file = pluginManager.getFile({
      name: pluginManager.resolveName({
        name: operationId,
        pluginKey: plugin.key,
        type: 'file',
      }),
      extname: '.ts',
      mode,
      pluginKey: plugin.key,
    });

    /**
     * Resolves the name and file path of a type generated by `plugin-ts` for
     * this operation.
     *
     * @param schemaName - The operation schema name, e.g. `GetPetsQueryParams`.
     * @returns The resolved type name and file path.
     */
    const resolveType = (schemaName: string): ResolvedSymbol => ({
      name: pluginManager.resolveName({
        name: schemaName,
        pluginKey: [pluginTsName],
        type: 'type',
      }),
      path: pluginManager.resolvePath({
        baseName: `${pluginManager.resolveName({
          name: operationId,
          pluginKey: [pluginTsName],
          type: 'file',
        })}.ts`,
        pluginKey: [pluginTsName],
        options: { type: 'file' },
      }) as KubbFile.Path,
    });

    /**
     * Resolves the name and file path of a struct generated by
     * `plugin-superstruct` for this operation.
     *
     * @param schemaName - The operation schema name, e.g. `GetPetsQueryResponse`.
     * @returns The resolved struct name and file path.
     */
    const resolveStruct = (schemaName: string): ResolvedSymbol => ({
      name: pluginManager.resolveName({
        name: schemaName,
        pluginKey: [pluginSuperstructName],
        type: 'const',
      }),
      path: pluginManager.resolvePath({
        baseName: `${pluginManager.resolveName({
          name: operationId,
          pluginKey: [pluginSuperstructName],
          type: 'file',
        })}.ts`,
        pluginKey: [pluginSuperstructName],
        options: { type: 'file' },
      }) as KubbFile.Path,
    });

    const response = resolveType(operationSchemas.response.name);
    const responseStruct = resolveStruct(operationSchemas.response.name);

    const pathParamsSchema: OperationSchema | undefined =
      operationSchemas.pathParams;
    const queryParamsSchema: OperationSchema | undefined =
      operationSchemas.queryParams;

    const pathParams = pathParamsSchema
      ? resolveType(pathParamsSchema.name)
      : undefined;
    const queryParams = queryParamsSchema
      ? resolveType(queryParamsSchema.name)
      : undefined;
    const queryParamsOptional = queryParamsSchema
      ? !hasRequiredProperties(queryParamsSchema.schema)
      : false;

    const queryKeyName = `${baseName}QueryKey`;
    const queryOptionsName = `${baseName}QueryOptions`;
    const fetcherName = baseName.startsWith('get')
      ? `fetch${baseName.slice('get'.length)}`
      : `fetch${pascalCase(baseName)}`;

    // Parameters shared by all three generated functions (minus `client`,
    // which the query key factory does not need).
    const parameterEntries: Array<{ signature: string; forward: string }> = [];
    if (pathParams) {
      parameterEntries.push({
        signature: `pathParams: ${pathParams.name}`,
        forward: 'pathParams',
      });
    }
    if (queryParams) {
      parameterEntries.push({
        signature: `params${queryParamsOptional ? '?' : ''}: ${queryParams.name}`,
        forward: 'params',
      });
    }

    const parameterSignatures = parameterEntries
      .map((entry) => entry.signature)
      .join(', ');
    const parameterForwards = parameterEntries
      .map((entry) => entry.forward)
      .join(', ');
    const withLeadingComma = (value: string): string =>
      value.length > 0 ? `, ${value}` : '';

    const queryKeyParts = [
      JSON.stringify(queryKeyPrefix),
      JSON.stringify(baseName),
      ...(pathParams ? ['pathParams'] : []),
      ...(queryParams
        ? [queryParamsOptional ? '...(params ? [params] : [])' : 'params']
        : []),
    ];

    const method = operation.method.toLowerCase();
    const summary = operation.getSummary();
    const description = operation.getDescription();
    const endpoint = `${method.toUpperCase()} ${operation.path}`;
    const docLines = [summary, description]
      .filter(Boolean)
      .map((line) => ` * ${line as string}`);

    const queryKeySource = `
/**
 * Query key for \`${endpoint}\`.
 */
export const ${queryKeyName} = (${parameterSignatures}) =>
  [${queryKeyParts.join(', ')}] as const;
`;

    const requestArguments = [
      `method: '${method}'`,
      `url: ${renderUrl(operation.path)}`,
      ...(queryParams ? ['params'] : []),
      'signal',
    ];

    const queryOptionsSource = `
/**
${docLines.length > 0 ? `${docLines.join('\n')}\n *\n` : ''} * Returns the TanStack Query options for \`${endpoint}\`. The response is
 * validated against {@link ${responseStruct.name}} before it is returned.
 */
export function ${queryOptionsName}(
  client: ApiRequestClient${withLeadingComma(parameterSignatures)},
  options?: FetchOptions,
): FetchQueryOptions<${response.name}> {
  return {
    queryKey: ${queryKeyName}(${parameterForwards}),
    queryFn: async ({ signal }: QueryFunctionContext) => {
      const data = await client.request<${response.name}>({
        ${requestArguments.join(',\n        ')},
      });
      assert(data, ${responseStruct.name});
      return data;
    },
    ...getQueryOptionsOverrides(options),
  };
}
`;

    const fetcherSource = `
/**
${docLines.length > 0 ? `${docLines.join('\n')}\n *\n` : ''} * Fetches \`${endpoint}\` through the client's QueryClient, deduplicating
 * concurrent calls and reusing fresh cached data.
 */
export async function ${fetcherName}(
  client: ApiRequestClient${withLeadingComma(parameterSignatures)},
  options?: FetchOptions,
): Promise<${response.name}> {
  return client.queryClient.fetchQuery(
    ${queryOptionsName}(client${withLeadingComma(parameterForwards)}, options),
  );
}
`;

    const typeImports = [
      response,
      ...(pathParams ? [pathParams] : []),
      ...(queryParams ? [queryParams] : []),
    ];

    return [
      {
        ...file,
        banner: getBanner({ oas, output: plugin.options.output, config }),
        footer: getFooter({ oas, output: plugin.options.output }),
        sources: [
          {
            name: queryKeyName,
            value: queryKeySource.trim(),
            isExportable: true,
            isIndexable: true,
          },
          {
            name: queryOptionsName,
            value: queryOptionsSource.trim(),
            isExportable: true,
            isIndexable: true,
          },
          {
            name: fetcherName,
            value: fetcherSource.trim(),
            isExportable: true,
            isIndexable: true,
          },
        ],
        imports: [
          {
            name: ['FetchQueryOptions', 'QueryFunctionContext'],
            path: '@tanstack/query-core',
            isTypeOnly: true,
          },
          {
            name: ['assert'],
            path: '@metamask/superstruct',
          },
          {
            name: ['getQueryOptionsOverrides'],
            path: runtimeImportPath,
          },
          {
            name: ['ApiRequestClient', 'FetchOptions'],
            path: runtimeImportPath,
            isTypeOnly: true,
          },
          {
            name: [responseStruct.name],
            path: responseStruct.path,
            root: file.path,
          },
          {
            name: typeImports.map((typeImport) => typeImport.name),
            path: response.path,
            root: file.path,
            isTypeOnly: true,
          },
        ],
      },
    ];
  },
});
