/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { ConnectivityController } from './ConnectivityController';

/**
 * Sets the connectivity status.
 *
 * @param status - The connectivity status to set.
 */
export type ConnectivityControllerSetStatusAction = {
  type: `ConnectivityController:setStatus`;
  handler: ConnectivityController['setStatus'];
};

/**
 * Union of all ConnectivityController action types.
 */
export type ConnectivityControllerMethodActions =
  ConnectivityControllerSetStatusAction;
