/**
 * This file is auto generated by `scripts/generate-method-action-types.ts`.
 * Do not edit manually.
 */

import type { ConnectivityController } from './ConnectivityController';

/**
 * Initializes the controller by fetching the initial connectivity status.
 */
export type ConnectivityControllerInitAction = {
  type: `ConnectivityController:init`;
  handler: ConnectivityController['init'];
};

/**
 * Sets the connectivity status.
 *
 * @param status - The connectivity status to set.
 */
export type ConnectivityControllerSetConnectivityStatusAction = {
  type: `ConnectivityController:setConnectivityStatus`;
  handler: ConnectivityController['setConnectivityStatus'];
};

/**
 * Union of all ConnectivityController action types.
 */
export type ConnectivityControllerMethodActions =
  | ConnectivityControllerInitAction
  | ConnectivityControllerSetConnectivityStatusAction;
