name: Lint Suppressions

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
  merge_group:

permissions:
  contents: read

jobs:
  lint-suppressions:
    name: Lint suppressions
    if: ${{ github.event_name != 'merge_group' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v3
        with:
          is-high-risk-environment: false
          persist-credentials: false
          node-version: ${{ matrix.node-version }}
          fetch-depth: 2
      - name: Run yarn lint:suppressions
        shell: bash
        run: |
          if yarn lint:suppressions; then
            exit 0
          fi
          if [[ "$IS_WAIVED" == 'true' ]]; then
            echo "::warning::Suppressions were added, which the '$WAIVER_LABEL' label allows."
            exit 0
          fi
          echo "These files are owned by @MetaMask/core-platform, who can apply the '$WAIVER_LABEL' label if the suppressions have to be added."
          exit 1
        env:
          WAIVER_LABEL: allow-new-suppressions
          IS_WAIVED: ${{ contains(github.event.pull_request.labels.*.name, 'allow-new-suppressions') }}
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi
