name: Publish Release

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: false
      SLACK_WEBHOOK_URL:
        required: true

permissions:
  contents: read

concurrency:
  group: publish-release
  queue: max

jobs:
  build:
    name: Build release artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v3
        with:
          is-high-risk-environment: true
          persist-credentials: false
          ref: ${{ github.sha }}
      - name: Build
        run: yarn build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: publish-release-artifacts-${{ github.sha }}
          include-hidden-files: true
          retention-days: 4
          path: |
            ./packages/**/dist
            ./node_modules/.yarn-state.yml

  publish-npm-dry-run:
    name: Dry run publish to NPM
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v3
        with:
          is-high-risk-environment: true
          persist-credentials: false
          ref: ${{ github.sha }}
          skip-install: true
      - name: Restore build artifacts
        uses: actions/download-artifact@v7
        with:
          name: publish-release-artifacts-${{ github.sha }}
      - name: Dry run publish to NPM
        uses: MetaMask/action-npm-publish@v6
        with:
          dry-run: true
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          subteam: S042S7RE4AE # @metamask-npm-publishers

  publish-npm:
    name: Publish to NPM
    environment: npm-publish
    runs-on: ubuntu-latest
    needs: publish-npm-dry-run
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v3
        with:
          is-high-risk-environment: true
          persist-credentials: false
          ref: ${{ github.sha }}
          skip-install: true
      - name: Restore build artifacts
        uses: actions/download-artifact@v7
        with:
          name: publish-release-artifacts-${{ github.sha }}
      - name: Publish to NPM
        uses: MetaMask/action-npm-publish@v6
        with:
          dry-run: false
          npm-token: ${{ secrets.NPM_TOKEN }}

  publish-release:
    name: Publish release to GitHub
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: publish-npm
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v3
        with:
          is-high-risk-environment: true
          persist-credentials: false
          ref: ${{ github.sha }}
          skip-install: true
      - uses: MetaMask/action-publish-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
