name: Shared ChangeLog Check

on:
  workflow_call:
    inputs:
      base-branch:
        required: false
        type: string
      event-type:
        description: 'The event type'
        type: string
      head-ref:
        required: true
        type: string
      pr-number:
        description: 'The pull request number'
        required: false
        type: string
      repo:
        description: 'The repository to check'
        required: true
        type: string
    secrets:
      gh-token:
        required: true

jobs:
  shared_changelog_check:
    runs-on: ubuntu-latest
    steps:
      - name: Conditional Skip or Execute
        run: |
          if [[ "${{ inputs.event-type }}" == "merge_group" ]]; then
            echo "Merge group event detected, auto-succeeding."
            exit 0
          fi
          echo "Proceeding with pull request checks."

      - name: Check out target repository
        if: ${{ inputs.event-type == 'pull_request' }}
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.head-ref }}
          path: target-repo
          fetch-depth: 0

      - name: Checkout github-tools repository
        if: ${{ inputs.event-type == 'pull_request' }}
        uses: actions/checkout@v4
        with:
          repository: MetaMask/core
          ref: changelog-checker
          path: github-tools

      - name: Enable Corepack
        if: ${{ inputs.event-type == 'pull_request' }}
        run: corepack enable
        shell: bash

      - name: Set up Node.js
        if: ${{ inputs.event-type == 'pull_request' }}
        uses: actions/setup-node@v4
        with:
          node-version-file: ./github-tools/.nvmrc
          cache-dependency-path: ./github-tools/yarn.lock
          cache: yarn

      - name: Install dependencies
        if: ${{ inputs.event-type == 'pull_request' }}
        run: yarn --immutable
        shell: bash
        working-directory: ./github-tools

      - name: Check PR Labels
        if: ${{ inputs.event-type == 'pull_request' }}
        id: label-check
        env:
          GITHUB_TOKEN: ${{ secrets.gh-token }}
          GITHUB_REPO: ${{ inputs.repo }}
          PR_NUMBER: ${{ inputs.pr-number }}
        run: |
          # Fetch labels and check for no-changelog
          if labels=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${GITHUB_REPO}/issues/${PR_NUMBER}/labels"); then
            if echo "$labels" | jq -e '.[] | select(.name == "no-changelog")' > /dev/null; then
              echo "no-changelog label found, skipping changelog check."
              echo "skip_check=true" >> "$GITHUB_OUTPUT"
            else
              echo "No no-changelog label found, proceeding with check."
              echo "skip_check=false" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "::error::Failed to fetch labels. Assuming changelog check is needed."
            echo "skip_check=false" >> "$GITHUB_OUTPUT"
          fi
        shell: bash

      - name: Check Changelog
        if: ${{ inputs.event-type == 'pull_request' && steps.label-check.outputs.skip_check != 'true' }}
        id: changelog-check
        shell: bash
        working-directory: ./github-tools
        run: |
          yarn run changelog:check ../target-repo ${{ inputs.base-branch || 'main' }}
