name: Shared ChangeLog Check

on:
  workflow_call:
    inputs:
      base-branch:
        required: false
        type: string
      event-type:
        description: 'The event type'
        type: string
      feature-branch:
        required: true
        type: string
      is-monorepo:
        description: 'Set to true for monorepo projects'
        required: false
        type: boolean
        default: false
      pr-number:
        description: 'The pull request number'
        required: false
        type: string
      repo:
        description: 'The repository to check'
        required: true
        type: string
    secrets:
      gh-token:
        required: true

jobs:
  shared_changelog_check:
    runs-on: ubuntu-latest
    steps:
      - name: Conditional Skip or Execute
        run: |
          if [[ "${{ inputs.event-type }}" == "merge_group" ]]; then
            echo "Merge group event detected, auto-succeeding."
            exit 0
          fi
          echo "Proceeding with pull request checks."

      - name: Check out target repository
        if: ${{ inputs.event-type == 'pull_request' }}
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.feature-branch }}
          path: target-repo
          fetch-depth: 0

      - name: Checkout github-tools repository
        if: ${{ inputs.event-type == 'pull_request' }}
        uses: actions/checkout@v4
        with:
          repository: MetaMask/core
          ref: changelog-checker
          path: github-tools

      - name: Enable Corepack
        if: ${{ inputs.event-type == 'pull_request' }}
        run: corepack enable
        shell: bash

      - name: Set up Node.js
        if: ${{ inputs.event-type == 'pull_request' }}
        uses: actions/setup-node@v4
        with:
          node-version-file: ./github-tools/.nvmrc
          cache-dependency-path: ./github-tools/yarn.lock
          cache: yarn

      - name: Install dependencies
        if: ${{ inputs.event-type == 'pull_request' }}
        run: yarn --immutable
        shell: bash
        working-directory: ./github-tools

      - name: Check PR Labels
        if: ${{ inputs.event-type == 'pull_request' }}
        id: label-check
        env:
          GITHUB_TOKEN: ${{ secrets.gh-token }}
          GITHUB_REPO: ${{ inputs.repo }}
          PR_NUMBER: ${{ inputs.pr-number }}
        run: |
          # Fetch labels from the GitHub API
          if ! labels=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${GITHUB_REPO}/issues/${PR_NUMBER}/labels"); then
            echo "::error::Failed to fetch labels from GitHub API."
            exit 1
          fi

          # Proceed with checking for the 'no-changelog' label using jq
          if echo "$labels" | jq -e '.[] | select(.name == "no-changelog")'; then
            echo "No-changelog label found, skipping changelog check."
            echo "SKIP_CHANGELOG=true" >> "$GITHUB_ENV"
          else
            echo "SKIP_CHANGELOG=false" >> "$GITHUB_ENV"
            echo "No-changelog label not found, proceeding with changelog check."
          fi
        shell: bash

      - name: Check Changelog
        if: ${{ inputs.event-type == 'pull_request' && env.SKIP_CHANGELOG != 'true' }}
        id: changelog-check
        shell: bash
        env:
          IS_MONOREPO: ${{ inputs.is-monorepo || 'false' }}
          REPO_PATH: ../target-repo
          HEAD_REF: ${{ inputs.feature-branch }}
          BASE_REF: ${{ inputs.base-branch || 'main' }}
        working-directory: ./github-tools
        run: |
          yarn run changelog:check
